In [1]:
import os

train_path='/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/train/'
test_path='/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/test'
train_list=os.listdir(train_path)
test_list=os.listdir(test_path)

In [2]:
import pandas as pd  

train=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/train.csv")

In [3]:
train=train.sort_values(['id','path','label'])
train

             id                  path label
39661  AAACWKPZ  ./train/AAACWKPZ.ogg  fake
39539  AAAQOZYI  ./train/AAAQOZYI.ogg  fake
655    AAAWBXQE  ./train/AAAWBXQE.ogg  real
29647  AABHDRLX  ./train/AABHDRLX.ogg  real
16890  AABXXHMU  ./train/AABXXHMU.ogg  real
...         ...                   ...   ...
19183  ZZZMJSBX  ./train/ZZZMJSBX.ogg  fake
20744  ZZZRTSKN  ./train/ZZZRTSKN.ogg  fake
25482  ZZZSAANM  ./train/ZZZSAANM.ogg  real
22209  ZZZSYEYS  ./train/ZZZSYEYS.ogg  fake
1125   ZZZTCIWY  ./train/ZZZTCIWY.ogg  fake

[55438 rows x 3 columns]

In [4]:
import natsort
train_list=natsort.natsorted(train_list)

In [5]:
train['label'].isnull().sum()

0

In [6]:
train_list

['AAACWKPZ.ogg',
 'AAAQOZYI.ogg',
 'AAAWBXQE.ogg',
 'AABHDRLX.ogg',
 'AABXXHMU.ogg',
 'AACAYDKC.ogg',
 'AACBAWMZ.ogg',
 'AACEAXVU.ogg',
 'AACHVERO.ogg',
 'AACYAWEH.ogg',
 'AADDNUMU.ogg',
 'AADKWHEE.ogg',
 'AADPDAER.ogg',
 'AADQUEFI.ogg',
 'AAECEROJ.ogg',
 'AAEYTHSY.ogg',
 'AAFFVAWD.ogg',
 'AAFNYPXE.ogg',
 'AAGDMPXZ.ogg',
 'AAGIITHH.ogg',
 'AAGXILIN.ogg',
 'AAGZDQDL.ogg',
 'AAHKQWBB.ogg',
 'AAIGXLUD.ogg',
 'AAIINGWH.ogg',
 'AAIKZLBQ.ogg',
 'AAIXOVVV.ogg',
 'AAIYWHUF.ogg',
 'AAJEQLVT.ogg',
 'AAJKXPIW.ogg',
 'AAJMPRLS.ogg',
 'AAJSFGQB.ogg',
 'AAKKEAOL.ogg',
 'AAKXVWXI.ogg',
 'AALITDLH.ogg',
 'AALMMBOZ.ogg',
 'AALVLTSV.ogg',
 'AAMMREFE.ogg',
 'AANJJHYA.ogg',
 'AANOXTME.ogg',
 'AANUFJBH.ogg',
 'AAOEAZJW.ogg',
 'AAOFKKOG.ogg',
 'AAOYUWCN.ogg',
 'AAPELQFY.ogg',
 'AAPGWSKV.ogg',
 'AAPWJSUB.ogg',
 'AAQBLCRK.ogg',
 'AAQBNHMD.ogg',
 'AAQBQXCT.ogg',
 'AAQFLJFN.ogg',
 'AAQJRBNN.ogg',
 'AAQNTEKV.ogg',
 'AAQQXFSY.ogg',
 'AARBSIOH.ogg',
 'AARGVJZI.ogg',
 'AARGWRKZ.ogg',
 'AARRJAAQ.ogg',
 'AASWUMSW.ogg',
 'AATCFCVI.ogg',
 'AATLVEWK.ogg',
 'AATQICFM.ogg',
 'AATTJCGE.ogg',
 'AATTWSHA.ogg',
 'AAUAYKVM.ogg',
 'AAUEYCPM.ogg',
 'AAUSMRIH.ogg',
 'AAUTECVW.ogg',
 'AAWRAXMA.ogg',
 'AAWWBNIZ.ogg',
 'AAWWHHJX.ogg',
 'AAWZUHOB.ogg',
 'AAXQREUD.ogg',
 'AAXSBNDD.ogg',
 'AAXYCDPY.ogg',
 'AAYKMDBZ.ogg',
 'AAYPWYKF.ogg',
 'AAYTHXYW.ogg',
 'AAYYBEHJ.ogg',
 'AAZJOTGS.ogg',
 'AAZTWMFP.ogg',
 'AAZYAGMM.ogg',
 'ABAENKHV.ogg',
 'ABAFLSLF.ogg',
 'ABBIUGTR.ogg',
 'ABBZBMWL.ogg',
 'ABCPBMFW.ogg',
 'ABCVBHOB.ogg',
 'ABDOJNBI.ogg',
 'ABEFAEHN.ogg',
 'ABEMMSDM.ogg',
 'ABEOIKVE.ogg',
 'ABFGDXNL.ogg',
 'ABFJWPVZ.ogg',
 'ABFLRFQS.ogg',
 'ABFLVQJN.ogg',
 'ABFQLXGA.ogg',
 'ABGTOQQP.ogg',
 'ABHCEUXO.ogg',
 'ABHKMALR.ogg',
 'ABHPHEQR.ogg',
 'ABICOCXR.ogg',
 'ABJOLJDE.ogg',
 'ABKCBVEX.ogg',
 'ABKEQPLS.ogg',
 'ABKFHZQH.ogg',
 'ABKGIXCK.ogg',
 'ABKUMPGG.ogg',
 'ABKXHBIM.ogg',
 'ABLARKBT.ogg',
 'ABLIHAZW.ogg',
 'ABLNKKUX.ogg',
 'ABLWKUWO.ogg',
 'ABMDYAQT.ogg',
 'ABMPTGUJ.ogg',
 'ABMTFRFR.ogg',
 'ABNJDLFT.ogg',
 'ABNPAPHJ.ogg',
 'ABNSMWQL.ogg',
 'ABNYBNQV.ogg',
 'ABOAJFJU.ogg',
 'ABODBMGT.ogg',
 'ABOGAUEA.ogg',
 'ABOHAMXE.ogg',
 'ABOQWAGI.ogg',
 'ABOUKFBY.ogg',
 'ABOZOOGW.ogg',
 'ABPBTZOA.ogg',
 'ABPERQHZ.ogg',
 'ABPFZVZA.ogg',
 'ABPNIJHE.ogg',
 'ABPPUMMV.ogg',
 'ABPQJSIJ.ogg',
 'ABQFMETL.ogg',
 'ABRQWDWI.ogg',
 'ABRXILJS.ogg',
 'ABSHFXDX.ogg',
 'ABSNZUNO.ogg',
 'ABSPZPGI.ogg',
 'ABSWVZJA.ogg',
 'ABSXQNYR.ogg',
 'ABTLKJXD.ogg',
 'ABTNXFZS.ogg',
 'ABTPCQFA.ogg',
 'ABUHXIXM.ogg',
 'ABUNGWUU.ogg',
 'ABUQBWXC.ogg',
 'ABUUKHXR.ogg',
 'ABVBMDVV.ogg',
 'ABVBWXRP.ogg',
 'ABVGOCCV.ogg',
 'ABVGQMUB.ogg',
 'ABVWWSBB.ogg',
 'ABWCFFHK.ogg',
 'ABWUXCMN.ogg',
 'ABXJPTKW.ogg',
 'ABYCORVQ.ogg',
 'ABYKGYGO.ogg',
 'ABYNSDDG.ogg',
 'ABYOZVEE.ogg',
 'ABYRDEYH.ogg',
 'ABYWCRPI.ogg',
 'ABYZABZD.ogg',
 'ABYZNHTZ.ogg',
 'ABZCSMEE.ogg',
 'ABZRXUIA.ogg',
 'ACADZSLP.ogg',
 'ACAQLVEP.ogg',
 'ACAXJQVH.ogg',
 'ACCFXCMA.ogg',
 'ACCIDWEB.ogg',
 'ACCIREEY.ogg',
 'ACCJJVII.ogg',
 'ACCRYQFF.ogg',
 'ACCVDILY.ogg',
 'ACDLJRDR.ogg',
 'ACDRCJLG.ogg',
 'ACDYPDEM.ogg',
 'ACERXOAR.ogg',
 'ACEVNLTT.ogg',
 'ACEZIJAB.ogg',
 'ACFGHOWF.ogg',
 'ACFQUFYO.ogg',
 'ACFWDRVT.ogg',
 'ACGFRPRI.ogg',
 'ACGUAHMM.ogg',
 'ACHJDZOZ.ogg',
 'ACHMYSZY.ogg',
 'ACHORSDD.ogg',
 'ACHRSWBA.ogg',
 'ACHVQDUS.ogg',
 'ACIFENNO.ogg',
 'ACIHPMPW.ogg',
 'ACILIPFX.ogg',
 'ACIWOKDJ.ogg',
 'ACJUMQTR.ogg',
 'ACKCEXWX.ogg',
 'ACKSBUPD.ogg',
 'ACLGRMWV.ogg',
 'ACLJSORS.ogg',
 'ACLQGXBK.ogg',
 'ACMIDJBL.ogg',
 'ACMMKTIX.ogg',
 'ACMVOVPG.ogg',
 'ACMVWCLI.ogg',
 'ACMWONON.ogg',
 'ACNMORJU.ogg',
 'ACOCDNKO.ogg',
 'ACOGLDLN.ogg',
 'ACOHIIDN.ogg',
 'ACOYEPCS.ogg',
 'ACPGWVHU.ogg',
 'ACPNWAZP.ogg',
 'ACPPUGMA.ogg',
 'ACQBNMSF.ogg',
 'ACQYANTU.ogg',
 'ACRFDLZL.ogg',
 'ACRLASKU.ogg',
 'ACRLDUAX.ogg',
 'ACRXBUQB.ogg',
 'ACSANEKN.ogg',
 'ACSBLOUY.ogg',
 'ACSCYAQJ.ogg',
 'ACSTVSFE.ogg',
 'ACTDYAIM.ogg',
 'ACTOJCHP.ogg',
 'ACTVDSPZ.ogg',
 'ACUUCPDE.ogg',
 'ACVBIICI.ogg',
 'ACVLQWUT.ogg',
 'ACWBHUHH.ogg',
 'ACWCEZKR.ogg',
 'ACWJDIYF.ogg',
 'ACWJFMDA.ogg',
 'ACWPMQUS.ogg',
 'ACXQVBZU.ogg',
 'ACXSNPAG.ogg',
 'ACYDVUSW.ogg',
 'ACYDXMGH.ogg',
 'ACYNKSXM.ogg',
 'ACYPSUDL.ogg',
 'ACYWILHM.ogg',
 'ACZDWFJU.ogg',
 'ACZHJEMZ.ogg',
 'ACZQHZVX.ogg',
 'ACZYGLME.ogg',
 'ADBJJUZZ.ogg',
 'ADBMDAGD.ogg',
 'ADCHBQBA.ogg',
 'ADCIPVAL.ogg',
 'ADCOOLKZ.ogg',
 'ADCPMILG.ogg',
 'ADCVPSTQ.ogg',
 'ADDBUOGS.ogg',
 'ADDGDTIE.ogg',
 'ADDVJJOY.ogg',
 'ADECASSY.ogg',
 'ADEJFHOY.ogg',
 'ADESWDSC.ogg',
 'ADEVHVOE.ogg',
 'ADFBFFAQ.ogg',
 'ADFGBALZ.ogg',
 'ADFSOSBE.ogg',
 'ADFWZJRH.ogg',
 'ADGBKOGD.ogg',
 'ADGOEVLE.ogg',
 'ADGQHEZF.ogg',
 'ADGYLZAM.ogg',
 'ADHFLHEJ.ogg',
 'ADHFTIVB.ogg',
 'ADHJIKDG.ogg',
 'ADHRVVOP.ogg',
 'ADHSMHLP.ogg',
 'ADHWFMHZ.ogg',
 'ADIEYDPE.ogg',
 'ADITNUUO.ogg',
 'ADIVLXIX.ogg',
 'ADJDIWTE.ogg',
 'ADJGZNRP.ogg',
 'ADJKHDIW.ogg',
 'ADJPBUAD.ogg',
 'ADKBXRUV.ogg',
 'ADKELMJC.ogg',
 'ADKFQOID.ogg',
 'ADKHDYQV.ogg',
 'ADKRPWYK.ogg',
 'ADLACGUG.ogg',
 'ADLDAJMK.ogg',
 'ADLKVZEI.ogg',
 'ADLMZFOF.ogg',
 'ADLNYCMI.ogg',
 'ADLQFSRE.ogg',
 'ADMEGPRK.ogg',
 'ADMFGENI.ogg',
 'ADMQLVFV.ogg',
 'ADNGIXGH.ogg',
 'ADNISKIT.ogg',
 'ADNKTIJQ.ogg',
 'ADNMWDJP.ogg',
 'ADNNCBGZ.ogg',
 'ADNPUEYS.ogg',
 'ADNYCZPD.ogg',
 'ADNYUCEB.ogg',
 'ADOEZJIO.ogg',
 'ADPKWOHB.ogg',
 'ADQHEJLV.ogg',
 'ADQKGTQJ.ogg',
 'ADQTWRSE.ogg',
 'ADQWFHBR.ogg',
 'ADRNQPXO.ogg',
 'ADSDIJTR.ogg',
 'ADSNZACB.ogg',
 'ADSRKXVU.ogg',
 'ADSRXWKO.ogg',
 'ADSSBDPL.ogg',
 'ADSTEZYN.ogg',
 'ADSTJJIB.ogg',
 'ADSXGIKP.ogg',
 'ADTAAQCP.ogg',
 'ADTBVZIW.ogg',
 'ADTDYZQZ.ogg',
 'ADTJOXOA.ogg',
 'ADTQJQCI.ogg',
 'ADTUELXB.ogg',
 'ADUABJXF.ogg',
 'ADUBKOVZ.ogg',
 'ADUIUEAW.ogg',
 'ADUQCTQP.ogg',
 'ADUQOFSI.ogg',
 'ADVMSMTV.ogg',
 'ADVQXYIM.ogg',
 'ADWOYWAP.ogg',
 'ADWXBJDH.ogg',
 'ADXBGMXE.ogg',
 'ADYANHIO.ogg',
 'ADYGUSBE.ogg',
 'ADYJKHHY.ogg',
 'ADYPROEM.ogg',
 'ADYQNAPY.ogg',
 'ADZOBSNB.ogg',
 'ADZQZRLW.ogg',
 'ADZUQMJO.ogg',
 'AEAAVDAF.ogg',
 'AEBMFJWF.ogg',
 'AEBNACWI.ogg',
 'AEBPSOHM.ogg',
 'AEBZNUBU.ogg',
 'AECPNGMA.ogg',
 'AECRBGUJ.ogg',
 'AECVJJQK.ogg',
 'AEDCYQQT.ogg',
 'AEDHXXYD.ogg',
 'AEDPCSZJ.ogg',
 'AEDZPTDI.ogg',
 'AEEACJIW.ogg',
 'AEEOHCVR.ogg',
 'AEEUECPE.ogg',
 'AEEURZUP.ogg',
 'AEFBUARF.ogg',
 'AEFMVYBW.ogg',
 'AEFWQMYP.ogg',
 'AEGEBHFT.ogg',
 'AEGWUBEU.ogg',
 'AEHCWTPB.ogg',
 'AEHDZWQM.ogg',
 'AEHVGZKG.ogg',
 'AEIAQJXV.ogg',
 'AEIKQDHC.ogg',
 'AEIRDQKD.ogg',
 'AEIZRMHG.ogg',
 'AEJFIPHV.ogg',
 'AEJJCUCT.ogg',
 'AEJMEDNT.ogg',
 'AEKDGZXN.ogg',
 'AEKOBTOE.ogg',
 'AEKSMDCO.ogg',
 'AELDKNXQ.ogg',
 'AELSBQQL.ogg',
 'AEMDYPFZ.ogg',
 'AEMHVPVW.ogg',
 'AEMKIWDO.ogg',
 'AEMMWATT.ogg',
 'AEMZZPPA.ogg',
 'AENBNFSI.ogg',
 'AENRBUAL.ogg',
 'AENTVFFM.ogg',
 'AENTYNMG.ogg',
 'AENWKPQE.ogg',
 'AEOFNIMF.ogg',
 'AEOHOHBW.ogg',
 'AEOXUSYR.ogg',
 'AEPGTXMC.ogg',
 'AEQHYULU.ogg',
 'AERPPYWP.ogg',
 'AERTUDRE.ogg',
 'AESCIYMY.ogg',
 'AESNSXZH.ogg',
 'AETIFRQU.ogg',
 'AETMLJQY.ogg',
 'AETMNHHW.ogg',
 'AETOGHFY.ogg',
 'AETWPQPP.ogg',
 'AEUDCUAC.ogg',
 'AEUWOAIB.ogg',
 'AEUYTICZ.ogg',
 'AEVCRCFP.ogg',
 'AEVJCMCP.ogg',
 'AEVKUTWY.ogg',
 'AEVNJDXP.ogg',
 'AEWICJRW.ogg',
 'AEWJZEME.ogg',
 'AEWTPDON.ogg',
 'AEWVHKYT.ogg',
 'AEXGOQDL.ogg',
 'AEXKWYDW.ogg',
 'AEXNBZLD.ogg',
 'AEXWQOKG.ogg',
 'AEXYVJTN.ogg',
 'AEYBZATW.ogg',
 'AEYLNOZG.ogg',
 'AEYOLXXC.ogg',
 'AEYSCGLW.ogg',
 'AEYXWGZQ.ogg',
 'AEZDKBEY.ogg',
 'AEZDYISN.ogg',
 'AEZYLUQL.ogg',
 'AFAAYJSI.ogg',
 'AFACNPAK.ogg',
 'AFADRIRJ.ogg',
 'AFAGCXCK.ogg',
 'AFALXUGS.ogg',
 'AFAMVIHQ.ogg',
 'AFANLUMA.ogg',
 'AFBLGBET.ogg',
 'AFBLTGOK.ogg',
 'AFBQLTEG.ogg',
 'AFBXWLNK.ogg',
 'AFBZWKVM.ogg',
 'AFCEQCVZ.ogg',
 'AFCYFLUW.ogg',
 'AFDJUTMO.ogg',
 'AFDPMDHK.ogg',
 'AFEHOGCJ.ogg',
 'AFEYUVPQ.ogg',
 'AFFLBOVF.ogg',
 'AFGCNCUU.ogg',
 'AFHOVMJV.ogg',
 'AFIFNCLP.ogg',
 'AFIKKLUO.ogg',
 'AFIROKXK.ogg',
 'AFIUYGOA.ogg',
 'AFJMVZLF.ogg',
 'AFJPEUHJ.ogg',
 'AFJWZYRF.ogg',
 'AFKXTQZF.ogg',
 'AFLFVIKD.ogg',
 'AFLHPTQF.ogg',
 'AFLZWGMH.ogg',
 'AFMGPDKW.ogg',
 'AFNLQZQL.ogg',
 'AFNXJSXO.ogg',
 'AFOPZPTL.ogg',
 'AFPGGOGL.ogg',
 'AFPVFIAV.ogg',
 'AFPWRHRB.ogg',
 'AFQEFLJL.ogg',
 'AFQGQEQK.ogg',
 'AFQHSXTQ.ogg',
 'AFQRCQUU.ogg',
 'AFQSNMRI.ogg',
 'AFRBXNQG.ogg',
 'AFRGMQYW.ogg',
 'AFRMTWGE.ogg',
 'AFROULCH.ogg',
 'AFRPSDEM.ogg',
 'AFRPUJGI.ogg',
 'AFRVVHPK.ogg',
 'AFSEQMNR.ogg',
 'AFSJNYYL.ogg',
 'AFSJRKTL.ogg',
 'AFSQIJVH.ogg',
 'AFSVCRLI.ogg',
 'AFSVSBSD.ogg',
 'AFTARWGF.ogg',
 'AFTBNETW.ogg',
 'AFTKYLGZ.ogg',
 'AFTZDSCV.ogg',
 'AFUEJCDS.ogg',
 'AFUKENUG.ogg',
 'AFUYLVDO.ogg',
 'AFVONUFK.ogg',
 'AFVTCTBV.ogg',
 'AFVWWUVV.ogg',
 'AFVXVZCM.ogg',
 'AFWDAERX.ogg',
 'AFWIEFWW.ogg',
 'AFWJNPMB.ogg',
 'AFWTBXQH.ogg',
 'AFWUUVYE.ogg',
 'AFXBKPRE.ogg',
 'AFXPGSFR.ogg',
 'AFYDFEQE.ogg',
 'AFYNCSIZ.ogg',
 'AFYOEBAF.ogg',
 'AFYZJFSO.ogg',
 'AFZGHEGW.ogg',
 'AFZJCVEA.ogg',
 'AFZNNBMJ.ogg',
 'AFZQULOH.ogg',
 'AFZWGKYO.ogg',
 'AGAALQTR.ogg',
 'AGAGSFMQ.ogg',
 'AGAPPMIX.ogg',
 'AGARSDKA.ogg',
 'AGASUWQT.ogg',
 'AGAUSEOT.ogg',
 'AGBAFONA.ogg',
 'AGBESGIE.ogg',
 'AGBGCXLZ.ogg',
 'AGBGYVPT.ogg',
 'AGBOALAT.ogg',
 'AGBUUVJE.ogg',
 'AGCHKVRQ.ogg',
 'AGCLFAQW.ogg',
 'AGCPUJHS.ogg',
 'AGCXORSP.ogg',
 'AGDAVVQQ.ogg',
 'AGDEVNQT.ogg',
 'AGDQIQFV.ogg',
 'AGDUPIND.ogg',
 'AGECTYKU.ogg',
 'AGEFYCBJ.ogg',
 'AGFDJUHD.ogg',
 'AGGDYNKC.ogg',
 'AGGGZLDV.ogg',
 'AGGMNOKU.ogg',
 'AGGXLHHC.ogg',
 'AGGXPHJD.ogg',
 'AGHATMQF.ogg',
 'AGIAJKYN.ogg',
 'AGIDDTIO.ogg',
 'AGILFEGO.ogg',
 'AGIQONAU.ogg',
 'AGIWVZKG.ogg',
 'AGJJZMVD.ogg',
 'AGJVQMDF.ogg',
 'AGJZCNCE.ogg',
 'AGKJBCAS.ogg',
 'AGKYVNAD.ogg',
 'AGLBDSJI.ogg',
 'AGLLRTPA.ogg',
 'AGLZYODF.ogg',
 'AGMWNVRF.ogg',
 'AGNBHAYY.ogg',
 'AGNQKNGC.ogg',
 'AGNZMIYK.ogg',
 'AGOHEFCJ.ogg',
 'AGOYCZEA.ogg',
 'AGPFLSOQ.ogg',
 'AGPQRXSM.ogg',
 'AGPTZJVF.ogg',
 'AGPYZILJ.ogg',
 'AGPZJCTE.ogg',
 'AGQCQXKL.ogg',
 'AGQCZWTI.ogg',
 'AGQFSDWT.ogg',
 'AGTLOBCF.ogg',
 'AGTPLHYB.ogg',
 'AGUGWFPO.ogg',
 'AGUNIFYQ.ogg',
 'AGUUHNCQ.ogg',
 'AGUZUPLU.ogg',
 'AGVAQSQO.ogg',
 'AGVEEARW.ogg',
 'AGVHCDDI.ogg',
 'AGVJCHVD.ogg',
 'AGVMGXSE.ogg',
 'AGVTOYVT.ogg',
 'AGWBLKOF.ogg',
 'AGWLICGR.ogg',
 'AGWMDZHB.ogg',
 'AGWXWLJP.ogg',
 'AGXMUWTF.ogg',
 'AGXXOJFP.ogg',
 'AGXYQIWN.ogg',
 'AGYCNBTW.ogg',
 'AGYLMIXE.ogg',
 'AGYZIVWR.ogg',
 'AGZPKXZS.ogg',
 'AHAAHLII.ogg',
 'AHAKRHKG.ogg',
 'AHBBPEMI.ogg',
 'AHCJYNJY.ogg',
 'AHDHDSEI.ogg',
 'AHDHXRRS.ogg',
 'AHDLDDUW.ogg',
 'AHDXYXNM.ogg',
 'AHDYOPHA.ogg',
 'AHEDSKDV.ogg',
 'AHEESOWJ.ogg',
 'AHENKMTJ.ogg',
 'AHFALZBA.ogg',
 'AHFCJALQ.ogg',
 'AHFNTEYW.ogg',
 'AHFVYCEQ.ogg',
 'AHGHLXSI.ogg',
 'AHGWLYDO.ogg',
 'AHHCNALZ.ogg',
 'AHHHPVXP.ogg',
 'AHHKSEZU.ogg',
 'AHHRIEZK.ogg',
 'AHHSAEJC.ogg',
 'AHIGTLCR.ogg',
 'AHIHQUVW.ogg',
 'AHIZVYUL.ogg',
 'AHJDQCGC.ogg',
 'AHJGLZQK.ogg',
 'AHJIBBAN.ogg',
 'AHJQEQQY.ogg',
 'AHJXGNEV.ogg',
 'AHKOYGQT.ogg',
 'AHLFJSQN.ogg',
 'AHLZMMEQ.ogg',
 'AHMAAWJD.ogg',
 'AHNKISAV.ogg',
 'AHNWFVNZ.ogg',
 'AHOJUHUF.ogg',
 'AHOLOSXE.ogg',
 'AHOVCIUA.ogg',
 'AHPMGUFF.ogg',
 'AHPUYDZQ.ogg',
 'AHPZBRGZ.ogg',
 'AHQCHOZM.ogg',
 'AHQHPOWN.ogg',
 'AHQJBAEO.ogg',
 'AHQNWZOY.ogg',
 'AHQPKPWQ.ogg',
 'AHRVGKVS.ogg',
 'AHRYQXUU.ogg',
 'AHSOCDYE.ogg',
 'AHSVTKRX.ogg',
 'AHTGUDEZ.ogg',
 'AHUEGHST.ogg',
 'AHUQLBHS.ogg',
 'AHUUSJOB.ogg',
 'AHVGNTRH.ogg',
 'AHVSZZGR.ogg',
 'AHVZLBGD.ogg',
 'AHWARRXT.ogg',
 'AHWDQGEF.ogg',
 'AHWMRDHV.ogg',
 'AHWQXQGQ.ogg',
 'AHWWLXXU.ogg',
 'AHXEIWPG.ogg',
 'AHXHREHW.ogg',
 'AHXLKIOJ.ogg',
 'AHXMGMPN.ogg',
 'AHXSBEFB.ogg',
 'AHYJVYRQ.ogg',
 'AHYTRPWQ.ogg',
 'AHYUUOKD.ogg',
 'AHZJXKGU.ogg',
 'AHZNAIDB.ogg',
 'AHZYJDTJ.ogg',
 'AIAGVZTM.ogg',
 'AIALEWIS.ogg',
 'AIAPAZIG.ogg',
 'AIAWJKGB.ogg',
 'AIBHCRTA.ogg',
 'AIBKDEPJ.ogg',
 'AIBNKKTD.ogg',
 'AIBTGPHR.ogg',
 'AIBXWDGX.ogg',
 'AICDZCBI.ogg',
 'AICNVWNS.ogg',
 'AICPVDQI.ogg',
 'AICQBQNH.ogg',
 'AICTFDLS.ogg',
 'AICWGBIU.ogg',
 'AIDHLGBC.ogg',
 'AIDJWOKA.ogg',
 'AIDTLCPO.ogg',
 'AIDWDJUD.ogg',
 'AIEHFHRX.ogg',
 'AIENUOJF.ogg',
 'AIEYUBGS.ogg',
 'AIEZGUQP.ogg',
 'AIFAIMIL.ogg',
 'AIFFTCRA.ogg',
 'AIFKCALK.ogg',
 'AIGEMOBQ.ogg',
 'AIGLPJKJ.ogg',
 'AIGNDNXA.ogg',
 'AIGZSPYB.ogg',
 'AIHQDZKQ.ogg',
 'AIHWUKPA.ogg',
 'AIIBGBFV.ogg',
 'AIIWGURU.ogg',
 'AIIZYHUL.ogg',
 'AIJWMRBH.ogg',
 'AIJYUZOW.ogg',
 'AIKCHPNB.ogg',
 'AIKMLOVD.ogg',
 'AIKPDOES.ogg',
 'AIMZABGQ.ogg',
 'AINLHFKV.ogg',
 'AINNBHJS.ogg',
 'AIODDNBO.ogg',
 'AIONYGQJ.ogg',
 'AIPGEZXI.ogg',
 'AIPGFSGT.ogg',
 'AIPSVYPD.ogg',
 'AIQJPTMG.ogg',
 'AIQQQVXS.ogg',
 'AIQWULRX.ogg',
 'AIRQOATZ.ogg',
 'AIRTCHLM.ogg',
 'AISAUROZ.ogg',
 'AISBKBEJ.ogg',
 'AISDUJXR.ogg',
 'AISGGETB.ogg',
 'AISPOPMG.ogg',
 'AISTCFGB.ogg',
 'AITDUZSK.ogg',
 'AITGONWI.ogg',
 'AITNPRBX.ogg',
 'AITUWDRP.ogg',
 'AIULKIVE.ogg',
 'AIUOCNCF.ogg',
 'AIURFHMM.ogg',
 'AIUUXFNP.ogg',
 'AIVDIIYO.ogg',
 'AIVEZTLG.ogg',
 'AIVFNGIE.ogg',
 'AIVWEUKX.ogg',
 'AIWADXHX.ogg',
 'AIWAGPQV.ogg',
 'AIWLSPNW.ogg',
 'AIWQMJLI.ogg',
 'AIWTLUAW.ogg',
 'AIXFJBKY.ogg',
 'AIXHYDNK.ogg',
 'AIXPMMFQ.ogg',
 'AIXTCNBY.ogg',
 'AIXZPKTV.ogg',
 'AIYFWIBQ.ogg',
 'AIYUHKXV.ogg',
 'AIYVYURF.ogg',
 'AIYYJOTF.ogg',
 'AIZAKRGX.ogg',
 'AIZPIRKF.ogg',
 'AIZPQTGC.ogg',
 'AIZUYWLJ.ogg',
 'AJBBOGBI.ogg',
 'AJBFABSU.ogg',
 'AJBSHFMM.ogg',
 'AJBTDTLP.ogg',
 'AJBTFEKQ.ogg',
 'AJBTONYS.ogg',
 'AJBWBSLF.ogg',
 'AJBYDNEE.ogg',
 'AJCQUYEA.ogg',
 'AJDCSEFP.ogg',
 'AJDEIHLH.ogg',
 'AJDFZAST.ogg',
 'AJDJNHAX.ogg',
 'AJEEHGWH.ogg',
 'AJEEZSQV.ogg',
 'AJEOUQOA.ogg',
 'AJFGGKEV.ogg',
 'AJFNUCOQ.ogg',
 'AJFQNPMQ.ogg',
 'AJGTYVOA.ogg',
 'AJGUQXNG.ogg',
 'AJGZARXD.ogg',
 'AJHPIGHL.ogg',
 'AJIAVABC.ogg',
 'AJIHLVIK.ogg',
 'AJIRAXRP.ogg',
 'AJIRPNDJ.ogg',
 'AJJSURAR.ogg',
 'AJKFOBAY.ogg',
 'AJKICDSA.ogg',
 'AJKIDODQ.ogg',
 'AJKLDVND.ogg',
 'AJKOJSYY.ogg',
 'AJKRNRZI.ogg',
 'AJKSMJPZ.ogg',
 'AJLEKGSH.ogg',
 'AJLKWLKO.ogg',
 'AJLPHOXD.ogg',
 'AJMMMHCS.ogg',
 'AJMNXSND.ogg',
 'AJMQPQNP.ogg',
 'AJMZRSAS.ogg',
 'AJNBKOJC.ogg',
 'AJNBTLJG.ogg',
 'AJNHIQTS.ogg',
 'AJNJPVEM.ogg',
 'AJOBHLGL.ogg',
 'AJOLSXZK.ogg',
 'AJOSGWOI.ogg',
 'AJOYFNMS.ogg',
 'AJPKCXPA.ogg',
 'AJPKWURJ.ogg',
 'AJPNKBWZ.ogg',
 'AJPSSKBD.ogg',
 'AJQJHTCG.ogg',
 'AJQNRTTZ.ogg',
 'AJQUQREE.ogg',
 'AJQZKSVP.ogg',
 'AJRBNWGC.ogg',
 'AJRJNVRN.ogg',
 'AJRKDDJB.ogg',
 'AJRPMMBT.ogg',
 'AJSFXQCO.ogg',
 'AJTDNKAA.ogg',
 'AJTIBKDD.ogg',
 'AJTPMNCF.ogg',
 'AJUBTAOJ.ogg',
 'AJUQLRZT.ogg',
 'AJUSUGDF.ogg',
 'AJUUNRCL.ogg',
 'AJVGIHPT.ogg',
 'AJVNKKQZ.ogg',
 'AJVUHIKA.ogg',
 'AJVZYPZM.ogg',
 'AJWSGVNU.ogg',
 'AJWWROIZ.ogg',
 'AJWXBYDV.ogg',
 'AJWZVGYQ.ogg',
 'AJXGGEWK.ogg',
 'AJXOLTIK.ogg',
 'AJXRDEWE.ogg',
 'AJXYHFTT.ogg',
 'AJYFLCUM.ogg',
 'AJYKQUND.ogg',
 'AJYTMDPR.ogg',
 'AJYVMMXL.ogg',
 'AJYWNBUN.ogg',
 'AJYXWCSX.ogg',
 'AJZIXPAQ.ogg',
 'AJZRGJRC.ogg',
 'AKAFJQIQ.ogg',
 'AKAOQATA.ogg',
 'AKARVISS.ogg',
 'AKATDYQY.ogg',
 'AKAWIOTJ.ogg',
 'AKAXQIFV.ogg',
 'AKBOCJDQ.ogg',
 'AKBOOKWP.ogg',
 'AKBYXDIJ.ogg',
 'AKBZWEAO.ogg',
 'AKCMMVXO.ogg',
 'AKCWBZCG.ogg',
 'AKCZXFJK.ogg',
 'AKDCNLFW.ogg',
 'AKDEGHKT.ogg',
 'AKDHVILH.ogg',
 'AKEEKPEY.ogg',
 'AKEGKQNM.ogg',
 'AKENQBZF.ogg',
 'AKENWNCS.ogg',
 'AKENYJXT.ogg',
 'AKETLKSR.ogg',
 'AKEWLEVH.ogg',
 'AKFLOOHC.ogg',
 'AKGEZENQ.ogg',
 'AKGGXHQN.ogg',
 'AKGYSFGZ.ogg',
 'AKICDHVP.ogg',
 'AKICOEWM.ogg',
 'AKIJCVDI.ogg',
 'AKINHLRE.ogg',
 'AKIVXKHY.ogg',
 'AKJFWEVN.ogg',
 'AKJIAQTQ.ogg',
 'AKJWOGIJ.ogg',
 'AKKTFFGR.ogg',
 'AKKXIUZP.ogg',
 'AKLFGKDY.ogg',
 'AKLHOOFX.ogg',
 'AKLJZFUP.ogg',
 'AKLKPSUW.ogg',
 'AKLOKBGI.ogg',
 'AKLRNIEB.ogg',
 'AKOAQNHD.ogg',
 'AKOHYRJS.ogg',
 'AKOKVMAZ.ogg',
 'AKONRVMN.ogg',
 'AKOSOOMH.ogg',
 'AKPEPGAV.ogg',
 'AKPQVOME.ogg',
 'AKPSIZYR.ogg',
 'AKPUUBZJ.ogg',
 'AKQNHIAB.ogg',
 'AKQOLGKG.ogg',
 'AKQPMDCG.ogg',
 'AKRCRNDX.ogg',
 'AKRCYUMZ.ogg',
 'AKRKSEGR.ogg',
 'AKRYZNFX.ogg',
 'AKSBEDFZ.ogg',
 'AKSJTTYE.ogg',
 'AKSMPCOJ.ogg',
 'AKSRUOJV.ogg',
 'AKSZZXKT.ogg',
 'AKTHFKUH.ogg',
 'AKTUNTOW.ogg',
 'AKULBGIU.ogg',
 'AKULFXLG.ogg',
 'AKUPPIKH.ogg',
 'AKVGARWY.ogg',
 'AKVGCQDA.ogg',
 'AKVKQPFD.ogg',
 'AKVLQJIL.ogg',
 'AKVLVALO.ogg',
 'AKVYLYBQ.ogg',
 'AKWRMHMD.ogg',
 'AKWSISHL.ogg',
 'AKXEYBRY.ogg',
 'AKXFXZZG.ogg',
 'AKXLJPRX.ogg',
 'AKXLTZMU.ogg',
 'AKZRNPZD.ogg',
 'AKZTJYKP.ogg',
 'AKZUVEER.ogg',
 'AKZYHHJB.ogg',
 'ALAQUICV.ogg',
 'ALAQYZKJ.ogg',
 'ALAXYGNO.ogg',
 'ALBEXIOR.ogg',
 'ALBFNSMA.ogg',
 'ALBKCPGL.ogg',
 'ALBTVPAU.ogg',
 'ALBYWZGG.ogg',
 'ALCFUPBC.ogg',
 'ALCJGLII.ogg',
 'ALCOPRTA.ogg',
 'ALCWCCFT.ogg',
 'ALDBWRIZ.ogg',
 'ALDUCZCW.ogg',
 'ALEKIKZU.ogg',
 'ALETTBZH.ogg',
 'ALEZOAYY.ogg',
 'ALFHAZRH.ogg',
 'ALFVKBTQ.ogg',
 'ALFWKHIF.ogg',
 'ALGRYBFL.ogg',
 'ALGVLKVB.ogg',
 'ALGWJQMZ.ogg',
 'ALHTABEH.ogg',
 'ALHUUXIA.ogg',
 'ALIJEHEB.ogg',
 'ALIJNFRF.ogg',
 'ALIYGGTF.ogg',
 'ALJDGTKE.ogg',
 'ALJRZMBU.ogg',
 'ALJSBCDQ.ogg',
 'ALJUXRNQ.ogg',
 'ALKAOVNU.ogg',
 'ALKIUKHA.ogg',
 'ALKMVJWQ.ogg',
 'ALKRDVFF.ogg',
 'ALLHXIXS.ogg',
 'ALLMSOUQ.ogg',
 'ALLQOPBP.ogg',
 'ALLXCXXT.ogg',
 'ALLXYWYP.ogg',
 'ALMAPCIY.ogg',
 'ALMRKNPR.ogg',
 'ALMVHLWP.ogg',
 'ALNATJVU.ogg',
 'ALNUKCDQ.ogg',
 'ALNUYTRG.ogg',
 'ALOCVASW.ogg',
 'ALODTWUB.ogg',
 'ALOIRSSL.ogg',
 'ALOLZWEP.ogg',
 'ALOXHEML.ogg',
 'ALPDTTFM.ogg',
 'ALPFZXWE.ogg',
 'ALPXPRSG.ogg',
 'ALQFACBZ.ogg',
 'ALQQCIDE.ogg',
 'ALQSTIKZ.ogg',
 'ALRDVQWR.ogg',
 'ALRLDEKG.ogg',
 'ALRTKBMG.ogg',
 'ALSPOUQC.ogg',
 'ALSUQFDZ.ogg',
 'ALUMTIAL.ogg',
 'ALUOSDMB.ogg',
 'ALUXSHFV.ogg',
 'ALVWEEJU.ogg',
 'ALWFDQID.ogg',
 'ALWTQMZG.ogg',
 'ALXEHQLG.ogg',
 'ALXJLRDR.ogg',
 'ALXLIYVG.ogg',
 ...]

In [7]:
test=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/test.csv")
test

               id                   path
0      TEST_00000  ./test/TEST_00000.ogg
1      TEST_00001  ./test/TEST_00001.ogg
2      TEST_00002  ./test/TEST_00002.ogg
3      TEST_00003  ./test/TEST_00003.ogg
4      TEST_00004  ./test/TEST_00004.ogg
...           ...                    ...
49995  TEST_49995  ./test/TEST_49995.ogg
49996  TEST_49996  ./test/TEST_49996.ogg
49997  TEST_49997  ./test/TEST_49997.ogg
49998  TEST_49998  ./test/TEST_49998.ogg
49999  TEST_49999  ./test/TEST_49999.ogg

[50000 rows x 2 columns]

In [8]:
import librosa
import librosa.display
import numpy as np  


x=librosa.load(train_path+train_list[0])[0]

In [9]:
S = librosa.feature.melspectrogram(y=x, sr=8000, n_mels=200)
log_S = librosa.power_to_db(S, ref=np.max)
mfcc = librosa.feature.mfcc(S=log_S, n_mfcc=30)
n_mfcc = librosa.feature.delta(mfcc, order=2)
n_mfcc = n_mfcc.flatten()
n_mfcc=n_mfcc[:500]

In [10]:
n_mfcc[499]

5.36542

In [11]:
n_mfcc.shape

(500,)

In [12]:
train_len=len(train_list)
test_len=len(test_list)

In [13]:
train_data=pd.DataFrame(index=range(train_len),columns=(['id','label']))
test_data=pd.DataFrame(index=range(test_len),columns=(['id']))

In [14]:
train_data['id']=train['id']
train_data['label']=train['label']

In [15]:
train_data

             id label
0      RUNQPNJF  real
1      JFAWUOGJ  fake
2      RDKEKEVX  real
3      QYHJDOFK  real
4      RSPQNHAO  real
...         ...   ...
55433  NJGPMAJL  real
55434  SZXIACUZ  fake
55435  PXLBTGRH  fake
55436  CGGQGPOQ  fake
55437  CPMKEDIS  fake

[55438 rows x 2 columns]

In [16]:
train_feature=pd.DataFrame(index=range(train_data.shape[0]),columns=range(n_mfcc.shape[0]))

In [17]:
train_feature

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
train_feature.shape

(55438, 500)

In [19]:
train_data.iloc[0,1]

'real'

In [20]:
test_data

        id
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
...    ...
49995  NaN
49996  NaN
49997  NaN
49998  NaN
49999  NaN

[50000 rows x 1 columns]

In [21]:
train_feature=pd.DataFrame(index=range(train_data.shape[0]),columns=range(n_mfcc.shape[0]))

In [22]:
train_feature.shape

(55438, 500)

In [23]:
x=librosa.load(train_path+train_list[2])[0]
S = librosa.feature.melspectrogram(y=x, sr=8000, n_mels=200)
log_S = librosa.power_to_db(S, ref=np.max)
mfcc = librosa.feature.mfcc(S=log_S, n_mfcc=30)
n_mfcc = librosa.feature.delta(mfcc, order=2)
n_mfcc=n_mfcc.flatten()
n_mfcc=n_mfcc[:800]
n_mfcc.shape

(800,)

In [24]:
import numpy as np
import librosa

sample_rate = 24000

for i in range(train_feature.shape[0]):
    x = librosa.load(train_path + train_list[i])[0]
    S = librosa.feature.melspectrogram(y=x, sr=sample_rate, n_mels=128)
    log_S = librosa.power_to_db(S, ref=np.max)
    mfcc = librosa.feature.mfcc(S=log_S, n_mfcc=20)
    mfcc_shape = mfcc.shape[1]

    # width 값을 mfcc_shape에 맞게 조정, 홀수이고 3 이상이어야 함
    if mfcc_shape < 3:
        width = 3  # mfcc_shape가 3보다 작으면 최소값 3으로 설정
    else:
        width = min(9, mfcc_shape - 1)  # mfcc_shape가 충분히 크면 9 이하로 조정
        if width % 2 == 0:
            width -= 1  # width가 짝수이면 홀수로 조정
    
    n_mfcc = librosa.feature.delta(mfcc, order=2, width=width)
    n_mfcc = n_mfcc.flatten()
    n_mfcc = n_mfcc[:500]
    
    for j in range(train_feature.shape[1]):
        if n_mfcc.shape[0] < 500:
            break
        train_feature.iloc[i, j] = n_mfcc[j]

In [25]:
train_feature

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,2.462114,2.462114,2.462114,2.462114,2.462114,3.825338,1.849125,-3.901479,-10.857851,-15.208128,...,-1.557468,-1.602663,-0.901839,-0.041508,0.13061,0.117529,0.288372,0.463069,0.203786,0.351013
1,-26.95857,-26.95857,-26.95857,-26.95857,-26.95857,-18.773539,0.99282,15.668339,19.088379,13.842461,...,-0.953924,-1.64228,-1.260267,0.298093,1.216972,1.590881,1.329067,0.956695,-0.253202,-0.620271
2,-9.628985,-9.628985,-9.628985,-9.628985,-9.628985,-1.919923,4.84776,7.224621,5.89034,3.961345,...,-0.212863,1.299378,1.898516,0.112505,-0.580593,-1.434617,0.010282,1.776501,0.51692,-2.136731
3,12.093678,12.093678,12.093678,12.093678,12.093678,16.202955,10.19401,-1.007229,-12.084692,-14.215332,...,3.453687,3.453687,3.453687,3.453687,3.453687,-3.274634,-3.274634,-3.274634,-3.274634,-3.274634
4,6.152809,6.152809,6.152809,6.152809,6.152809,2.481608,-3.940148,-7.325555,-5.819144,-2.624498,...,3.863179,2.032282,-0.59366,-0.780144,-0.247933,-0.105259,0.713699,1.691604,1.221165,0.245212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-8.06578,-8.06578,-8.06578,-8.06578,-8.06578,-10.777797,-6.011,-3.421314,0.113273,4.047371,...,4.325721,1.66089,-1.213816,-4.284922,-6.577037,-5.921885,-3.198617,0.29929,2.348603,3.260621
55434,-4.888532,-4.888532,-4.888532,-4.888532,-4.888532,1.468083,7.882121,10.28591,5.91484,-1.267801,...,-2.794201,-4.133718,-3.66019,-1.33096,1.852136,4.773663,5.629941,4.367256,0.928552,-2.316092
55435,35.083488,35.083488,35.083488,35.083488,35.083488,39.492382,29.740372,15.406304,-5.376789,-22.054562,...,1.502026,0.435017,0.364931,0.932592,1.880554,2.894395,3.153069,2.594543,1.161963,-1.127994
55436,1.958727,1.958727,1.958727,1.958727,1.958727,2.648844,-1.941248,-6.831968,-8.407947,-5.832794,...,-0.198021,1.303136,2.19466,1.569944,0.054429,-2.411168,-4.089002,-3.459533,-1.373131,1.120932
55437,1.164575,1.164575,1.164575,1.164575,1.164575,4.851145,5.559158,5.168675,4.803593,3.724522,...,0.260086,-1.601962,-2.601966,-1.808017,-0.180262,0.977579,0.519932,-1.254609,-1.603076,-1.510921

In [26]:
Y=pd.DataFrame(train['label'])

In [27]:
save_data=pd.concat([train_feature,Y],axis=1)

In [28]:
save_data

,0,1,2,3,4,5,6,7,8,9,...,491,492,493,494,495,496,497,498,499,label
0,2.462114,2.462114,2.462114,2.462114,2.462114,3.825338,1.849125,-3.901479,-10.857851,-15.208128,...,-1.602663,-0.901839,-0.041508,0.13061,0.117529,0.288372,0.463069,0.203786,0.351013,real
1,-26.95857,-26.95857,-26.95857,-26.95857,-26.95857,-18.773539,0.99282,15.668339,19.088379,13.842461,...,-1.64228,-1.260267,0.298093,1.216972,1.590881,1.329067,0.956695,-0.253202,-0.620271,fake
2,-9.628985,-9.628985,-9.628985,-9.628985,-9.628985,-1.919923,4.84776,7.224621,5.89034,3.961345,...,1.299378,1.898516,0.112505,-0.580593,-1.434617,0.010282,1.776501,0.51692,-2.136731,real
3,12.093678,12.093678,12.093678,12.093678,12.093678,16.202955,10.19401,-1.007229,-12.084692,-14.215332,...,3.453687,3.453687,3.453687,3.453687,-3.274634,-3.274634,-3.274634,-3.274634,-3.274634,real
4,6.152809,6.152809,6.152809,6.152809,6.152809,2.481608,-3.940148,-7.325555,-5.819144,-2.624498,...,2.032282,-0.59366,-0.780144,-0.247933,-0.105259,0.713699,1.691604,1.221165,0.245212,real
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-8.06578,-8.06578,-8.06578,-8.06578,-8.06578,-10.777797,-6.011,-3.421314,0.113273,4.047371,...,1.66089,-1.213816,-4.284922,-6.577037,-5.921885,-3.198617,0.29929,2.348603,3.260621,real
55434,-4.888532,-4.888532,-4.888532,-4.888532,-4.888532,1.468083,7.882121,10.28591,5.91484,-1.267801,...,-4.133718,-3.66019,-1.33096,1.852136,4.773663,5.629941,4.367256,0.928552,-2.316092,fake
55435,35.083488,35.083488,35.083488,35.083488,35.083488,39.492382,29.740372,15.406304,-5.376789,-22.054562,...,0.435017,0.364931,0.932592,1.880554,2.894395,3.153069,2.594543,1.161963,-1.127994,fake
55436,1.958727,1.958727,1.958727,1.958727,1.958727,2.648844,-1.941248,-6.831968,-8.407947,-5.832794,...,1.303136,2.19466,1.569944,0.054429,-2.411168,-4.089002,-3.459533,-1.373131,1.120932,fake
55437,1.164575,1.164575,1.164575,1.164575,1.164575,4.851145,5.559158,5.168675,4.803593,3.724522,...,-1.601962,-2.601966,-1.808017,-0.180262,0.977579,0.519932,-1.254609,-1.603076,-1.510921,fake

In [29]:
save_data2=save_data

In [30]:
save_data2=save_data.dropna(axis=0)

In [31]:
save_data2

,0,1,2,3,4,5,6,7,8,9,...,491,492,493,494,495,496,497,498,499,label
0,2.462114,2.462114,2.462114,2.462114,2.462114,3.825338,1.849125,-3.901479,-10.857851,-15.208128,...,-1.602663,-0.901839,-0.041508,0.13061,0.117529,0.288372,0.463069,0.203786,0.351013,real
1,-26.95857,-26.95857,-26.95857,-26.95857,-26.95857,-18.773539,0.99282,15.668339,19.088379,13.842461,...,-1.64228,-1.260267,0.298093,1.216972,1.590881,1.329067,0.956695,-0.253202,-0.620271,fake
2,-9.628985,-9.628985,-9.628985,-9.628985,-9.628985,-1.919923,4.84776,7.224621,5.89034,3.961345,...,1.299378,1.898516,0.112505,-0.580593,-1.434617,0.010282,1.776501,0.51692,-2.136731,real
3,12.093678,12.093678,12.093678,12.093678,12.093678,16.202955,10.19401,-1.007229,-12.084692,-14.215332,...,3.453687,3.453687,3.453687,3.453687,-3.274634,-3.274634,-3.274634,-3.274634,-3.274634,real
4,6.152809,6.152809,6.152809,6.152809,6.152809,2.481608,-3.940148,-7.325555,-5.819144,-2.624498,...,2.032282,-0.59366,-0.780144,-0.247933,-0.105259,0.713699,1.691604,1.221165,0.245212,real
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-8.06578,-8.06578,-8.06578,-8.06578,-8.06578,-10.777797,-6.011,-3.421314,0.113273,4.047371,...,1.66089,-1.213816,-4.284922,-6.577037,-5.921885,-3.198617,0.29929,2.348603,3.260621,real
55434,-4.888532,-4.888532,-4.888532,-4.888532,-4.888532,1.468083,7.882121,10.28591,5.91484,-1.267801,...,-4.133718,-3.66019,-1.33096,1.852136,4.773663,5.629941,4.367256,0.928552,-2.316092,fake
55435,35.083488,35.083488,35.083488,35.083488,35.083488,39.492382,29.740372,15.406304,-5.376789,-22.054562,...,0.435017,0.364931,0.932592,1.880554,2.894395,3.153069,2.594543,1.161963,-1.127994,fake
55436,1.958727,1.958727,1.958727,1.958727,1.958727,2.648844,-1.941248,-6.831968,-8.407947,-5.832794,...,1.303136,2.19466,1.569944,0.054429,-2.411168,-4.089002,-3.459533,-1.373131,1.120932,fake
55437,1.164575,1.164575,1.164575,1.164575,1.164575,4.851145,5.559158,5.168675,4.803593,3.724522,...,-1.601962,-2.601966,-1.808017,-0.180262,0.977579,0.519932,-1.254609,-1.603076,-1.510921,fake

In [32]:
save_data2.to_csv("train data0703(500).csv")