In [38]:
import os

train_path='/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/train/'
test_path='/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/test'
train_list=os.listdir(train_path)
test_list=os.listdir(test_path)

In [39]:
train_list

['PKBLZAUU.ogg',
 'ETAELAYF.ogg',
 'RNKVABJV.ogg',
 'MWVVAKDS.ogg',
 'MEBIPRFU.ogg',
 'OWRZKOFX.ogg',
 'PSSBCPZK.ogg',
 'JZCFPRZC.ogg',
 'FISJGZLV.ogg',
 'ACTVDSPZ.ogg',
 'KVUBQKZE.ogg',
 'JOTESUYZ.ogg',
 'QHUROVOB.ogg',
 'HIVJNPXS.ogg',
 'CVDYRRXU.ogg',
 'RBXNEYUY.ogg',
 'OEJADUTH.ogg',
 'MWCPVSOG.ogg',
 'FUJQMMZS.ogg',
 'CFQZALUW.ogg',
 'SMYXXFJA.ogg',
 'PPIPGETE.ogg',
 'ULPPEURA.ogg',
 'SDQKIMDB.ogg',
 'NVSVQNBB.ogg',
 'DLRPKBGP.ogg',
 'IPUDOTFG.ogg',
 'AANJJHYA.ogg',
 'ZYVAKHHA.ogg',
 'SXUZLVAY.ogg',
 'CWXABNNX.ogg',
 'NYQHKSSH.ogg',
 'GPQSBBYB.ogg',
 'ZLFIJLAH.ogg',
 'GTDMFMMA.ogg',
 'YHHQCYPU.ogg',
 'ADNMWDJP.ogg',
 'PVUURAVA.ogg',
 'THFUYYJJ.ogg',
 'NZSREHRW.ogg',
 'QUAFTBCZ.ogg',
 'BOERQAML.ogg',
 'ODYZCZMF.ogg',
 'RGOOOHZI.ogg',
 'DJCFTDLD.ogg',
 'FMFDRIGQ.ogg',
 'DRPWVDIR.ogg',
 'MLSJDGIV.ogg',
 'NKNXRYJD.ogg',
 'RSRYNJAW.ogg',
 'RSEKFTUR.ogg',
 'EZEEXKWQ.ogg',
 'MWAKERFD.ogg',
 'EWTZRCWT.ogg',
 'RHSPYUPH.ogg',
 'STVKXSQV.ogg',
 'AYWECGGI.ogg',
 'ZYOSPOSH.ogg',
 'JBJHEZDW.ogg',
 'YUHFBVUA.ogg',
 'RJKMXSBO.ogg',
 'DXNSPGVX.ogg',
 'HVXTZWSZ.ogg',
 'WQZXPVXC.ogg',
 'FTHTLYOC.ogg',
 'ILBRCCVA.ogg',
 'OVJYHYWS.ogg',
 'WGJNRDOU.ogg',
 'EOQUFWLV.ogg',
 'LBHDLYHP.ogg',
 'SLVXUTOQ.ogg',
 'QWOJYIHE.ogg',
 'TUXQMMAB.ogg',
 'NMBQFKQS.ogg',
 'YOYMQEYA.ogg',
 'LKSXTXRJ.ogg',
 'ZQYDGHQK.ogg',
 'BHPFZHMJ.ogg',
 'DIBSZRGC.ogg',
 'ZWDTTPIQ.ogg',
 'ZBPLFGBV.ogg',
 'DVFVBILD.ogg',
 'KJHSIITW.ogg',
 'MQDBZLNM.ogg',
 'OKPDOOEW.ogg',
 'NDYCUHYL.ogg',
 'UKBBTTQY.ogg',
 'KJFDEYNI.ogg',
 'PACUUTXN.ogg',
 'XDEUXGYP.ogg',
 'VUWEHTRT.ogg',
 'PPXGYDKO.ogg',
 'DKBYOVNI.ogg',
 'DGHHBZUM.ogg',
 'ENSGUOOT.ogg',
 'EPETIWWB.ogg',
 'TGSVXFVP.ogg',
 'YTEAZFUF.ogg',
 'SJIQFMUU.ogg',
 'RJMQBGWT.ogg',
 'FNUGZKBQ.ogg',
 'IWEVRZDL.ogg',
 'YHDVBYOQ.ogg',
 'AFUEJCDS.ogg',
 'HDZHAJZA.ogg',
 'VJOCCWKW.ogg',
 'ECPJMXQN.ogg',
 'AXLAVJBS.ogg',
 'HSJUOJGX.ogg',
 'KCXZXJOS.ogg',
 'CJPHEYEN.ogg',
 'NLQXDVRI.ogg',
 'SPXYWUCU.ogg',
 'KILJVVCI.ogg',
 'XRTXUMFI.ogg',
 'QGDWSDDV.ogg',
 'QJUCJMQK.ogg',
 'DTGUVJET.ogg',
 'PLMYURWT.ogg',
 'YKWMYLDT.ogg',
 'JGFNDKLL.ogg',
 'MZVDYACV.ogg',
 'REPLLKUF.ogg',
 'UDNVXCGE.ogg',
 'UZVASHAQ.ogg',
 'XPWRADHM.ogg',
 'IVNZDTXP.ogg',
 'YXCVTPZA.ogg',
 'DEZCNMKI.ogg',
 'LKUUUBAM.ogg',
 'CIEQIWSZ.ogg',
 'CQOFDLHK.ogg',
 'EMYCXDLO.ogg',
 'RNXGJXDI.ogg',
 'AZDLPYED.ogg',
 'RUFATYOZ.ogg',
 'QNLIAZOG.ogg',
 'BBJMOITN.ogg',
 'KJTSJQIN.ogg',
 'QCQHWWYY.ogg',
 'KOIPDIOM.ogg',
 'IAGGJWFQ.ogg',
 'JNLPGUUM.ogg',
 'TGZKINQM.ogg',
 'CYUWIUAS.ogg',
 'REFEGNWH.ogg',
 'LYLXCBZL.ogg',
 'LHWDVLNO.ogg',
 'NJEPTWJL.ogg',
 'XANMYRKU.ogg',
 'FAKMNMBN.ogg',
 'RFJNFKUS.ogg',
 'TWVCLVRV.ogg',
 'IRFGCRXY.ogg',
 'AVHLYYFU.ogg',
 'IHOGOITH.ogg',
 'KVJONDJW.ogg',
 'WHZGAWEF.ogg',
 'ABTLKJXD.ogg',
 'GKLVNGNC.ogg',
 'AEVCRCFP.ogg',
 'MEBYHRKI.ogg',
 'PUDKRNBH.ogg',
 'RSTKFSHD.ogg',
 'UBHPFHSS.ogg',
 'TJHXHKPI.ogg',
 'YKXWBXCT.ogg',
 'IDWDTXTN.ogg',
 'NIBZNJQJ.ogg',
 'UXZDDXWL.ogg',
 'LPTGNYVJ.ogg',
 'ONYQCAUV.ogg',
 'IHDPGETG.ogg',
 'QYPMVNVX.ogg',
 'VNOBHMSQ.ogg',
 'GSIDGIKL.ogg',
 'YJJXUGVE.ogg',
 'KVTISAGG.ogg',
 'ZCVEPILD.ogg',
 'DZASJMET.ogg',
 'DGNGQOYU.ogg',
 'ZORPFGII.ogg',
 'QMVTANHL.ogg',
 'SJEVBNWU.ogg',
 'RBFENKCV.ogg',
 'BZDLMAAM.ogg',
 'YANABVQQ.ogg',
 'QPKTTOWA.ogg',
 'LNDKSOEZ.ogg',
 'FVGVPAMK.ogg',
 'XPUNQKAS.ogg',
 'XVNIWOUE.ogg',
 'PVBNWWJZ.ogg',
 'WYDCTAZA.ogg',
 'VAQOCNFK.ogg',
 'XPWWRSSO.ogg',
 'CASPPUQX.ogg',
 'MMBJFKZF.ogg',
 'FBYMBWYY.ogg',
 'NCWECUOC.ogg',
 'XFTZEALE.ogg',
 'TZHUBRXD.ogg',
 'JXBQOZNI.ogg',
 'EEDULWXE.ogg',
 'EEEUXZPB.ogg',
 'GPNWCQDE.ogg',
 'BZPXSZPQ.ogg',
 'ZANYOYDE.ogg',
 'UBXFPADZ.ogg',
 'QENRVFWK.ogg',
 'IHSEFGCL.ogg',
 'EOERIXFO.ogg',
 'PRUKKMKE.ogg',
 'BXITZAFC.ogg',
 'SUAEXXSU.ogg',
 'XMKXIZRF.ogg',
 'FERZMYJX.ogg',
 'ANYIWUPE.ogg',
 'ZVDIBVZW.ogg',
 'ZVQCCIUP.ogg',
 'UWTUVHIH.ogg',
 'DVICWLZZ.ogg',
 'UNVUAWON.ogg',
 'MGAUJLXT.ogg',
 'QVSCLQDQ.ogg',
 'WOLCKMPB.ogg',
 'BTNLHZCV.ogg',
 'DALRXMFQ.ogg',
 'KDCKGUFR.ogg',
 'VKWRAMXN.ogg',
 'VSCWQIQH.ogg',
 'UTPHKWIR.ogg',
 'KVLVVGRY.ogg',
 'OAJLYXBU.ogg',
 'CADVBEQV.ogg',
 'RNMDEQZL.ogg',
 'XLKEKQED.ogg',
 'HOSKXCNL.ogg',
 'BQLAPNCS.ogg',
 'SMBMBIWY.ogg',
 'AXEOBUVC.ogg',
 'FCETGRPO.ogg',
 'ECPNHCRQ.ogg',
 'ADQHEJLV.ogg',
 'EYKIPLXD.ogg',
 'CWHMCFRC.ogg',
 'JRSFMRTS.ogg',
 'AUGPQKEA.ogg',
 'RUUHOHMT.ogg',
 'AMJDTIXD.ogg',
 'XCSMHLXJ.ogg',
 'OGZAMSEZ.ogg',
 'XMYMTSJQ.ogg',
 'XUPRTPNA.ogg',
 'EQTOWLRK.ogg',
 'NSQDSZRM.ogg',
 'RWRDNCCK.ogg',
 'XFAEXCHQ.ogg',
 'UIDXTEAH.ogg',
 'TEKLYNWF.ogg',
 'ITHYRZRA.ogg',
 'NJGBJWNC.ogg',
 'OKJYHLVU.ogg',
 'YAIVIIIM.ogg',
 'VEIBDSQK.ogg',
 'JTTJIQGO.ogg',
 'DCNLRTDX.ogg',
 'ZSSSOPFI.ogg',
 'DBGMBNRZ.ogg',
 'UJAEENSO.ogg',
 'QLGBAJDE.ogg',
 'UYPGCRTU.ogg',
 'HTYGJOHF.ogg',
 'REZRDJRT.ogg',
 'NXVXHUTL.ogg',
 'DLHJVYWG.ogg',
 'MOIXLCJT.ogg',
 'EUVFXEGN.ogg',
 'FIXVLOYF.ogg',
 'MUTVKDSP.ogg',
 'SMSKBNCZ.ogg',
 'QXKASXMP.ogg',
 'SPVETTCE.ogg',
 'NUWTXSDO.ogg',
 'AKEGKQNM.ogg',
 'ECUZCQVA.ogg',
 'NBFOHYCI.ogg',
 'JPGFQOOV.ogg',
 'IKHHTDYM.ogg',
 'XUUSDDYM.ogg',
 'EBSXANHR.ogg',
 'IXFXIHXK.ogg',
 'VXEHLMPG.ogg',
 'NGMAXWCD.ogg',
 'SSYJCRVA.ogg',
 'FCQJBPYO.ogg',
 'JBDGZXAA.ogg',
 'KAWHOFJT.ogg',
 'DOLUKIAZ.ogg',
 'ZJYHPTQR.ogg',
 'EKQNKRNB.ogg',
 'MAEYBIAU.ogg',
 'EJLFDBAE.ogg',
 'YZFCUOCN.ogg',
 'DRGUTSQF.ogg',
 'JXEDALMH.ogg',
 'IAAHZYOH.ogg',
 'AGJZCNCE.ogg',
 'UXKYFEBE.ogg',
 'BLSMSDER.ogg',
 'UURDPZPS.ogg',
 'PKAKMYLI.ogg',
 'WWTEBFMV.ogg',
 'BVVCTLIN.ogg',
 'GBINXFAF.ogg',
 'WKQYIXUZ.ogg',
 'SZSQPYPR.ogg',
 'RMCFPSVW.ogg',
 'WJRPDOGB.ogg',
 'ETYOKIWO.ogg',
 'JNPJBLYE.ogg',
 'HXNROLWU.ogg',
 'IBBIIFQW.ogg',
 'RPOJBWTI.ogg',
 'QMHOWTQR.ogg',
 'XBVSBYIB.ogg',
 'BIJPYFDJ.ogg',
 'YMCYZKEI.ogg',
 'UEXJTDXI.ogg',
 'VQOXWLWN.ogg',
 'FILGQUSP.ogg',
 'WQVXJZIR.ogg',
 'QZAHBPHD.ogg',
 'UKJXUJIQ.ogg',
 'VMFGRPLO.ogg',
 'WTMXVOMF.ogg',
 'VBYZDRQI.ogg',
 'ZLKFJKKR.ogg',
 'NTKEWKKX.ogg',
 'UWFNMHLA.ogg',
 'XAOOKSUA.ogg',
 'BVYNDGFZ.ogg',
 'SYKWRRLA.ogg',
 'CLJQREQF.ogg',
 'ORNYIOEU.ogg',
 'DAZPLJLX.ogg',
 'SSHYDJXA.ogg',
 'IGYVLQMM.ogg',
 'QNXHMIMS.ogg',
 'FBMHIIPQ.ogg',
 'PFKRFXEA.ogg',
 'NKDIHLGC.ogg',
 'CUILQPMU.ogg',
 'CCLLLYEN.ogg',
 'PSSDBJPZ.ogg',
 'ZBVVCATM.ogg',
 'MXYSJGLP.ogg',
 'ZKCSYOQO.ogg',
 'TIDIOOCC.ogg',
 'YATRETMW.ogg',
 'QZOIFOYV.ogg',
 'QAUSUEDB.ogg',
 'CCQBVQQQ.ogg',
 'EQUCZPFN.ogg',
 'QFSEGPSR.ogg',
 'XOWODSBX.ogg',
 'PONLDJLA.ogg',
 'YLVBGNNH.ogg',
 'KBIZYJZT.ogg',
 'NQONEHCE.ogg',
 'HIEBBBZA.ogg',
 'PXBBEWOD.ogg',
 'RVHEUDSD.ogg',
 'YNJXHVST.ogg',
 'YBWYECVF.ogg',
 'IDFTGYKD.ogg',
 'MEWAFFCS.ogg',
 'IYZRPKFM.ogg',
 'GAUPLBOZ.ogg',
 'SMGVZLYA.ogg',
 'PTSASGSH.ogg',
 'FXBARIHX.ogg',
 'RYGHOKSR.ogg',
 'EGFDFQKX.ogg',
 'XUNVFBND.ogg',
 'TEJQLYFZ.ogg',
 'XAORVNNQ.ogg',
 'FADUJTRP.ogg',
 'NDQWWROM.ogg',
 'KAJQZZZS.ogg',
 'HXAJARSI.ogg',
 'SMRHPQCI.ogg',
 'LQERTXVW.ogg',
 'ZCLEZDXC.ogg',
 'SDKEFNTR.ogg',
 'RHHXJQKF.ogg',
 'WTMAYTIZ.ogg',
 'KSHAZYET.ogg',
 'PKKTCEUH.ogg',
 'IUFJXGCH.ogg',
 'JLIXOQLH.ogg',
 'KNYPGCNA.ogg',
 'SSFWHYPV.ogg',
 'AQRPWMGR.ogg',
 'KGGFSAOM.ogg',
 'GFUDPARV.ogg',
 'FUFPKTMZ.ogg',
 'DMEGAAWG.ogg',
 'AJRKDDJB.ogg',
 'GKYOUQAD.ogg',
 'GCVBGAYP.ogg',
 'ETYMMLFF.ogg',
 'VKFELTVG.ogg',
 'MEAQAVWF.ogg',
 'ZDQWNGZO.ogg',
 'JBHNOVAU.ogg',
 'EPCOPHSI.ogg',
 'PYGWNAUG.ogg',
 'TAQDRXVU.ogg',
 'ARADUZCJ.ogg',
 'NRYRFZQP.ogg',
 'KVHVAHKE.ogg',
 'NAHTNUTF.ogg',
 'KYJBQEPE.ogg',
 'TJSPOYUZ.ogg',
 'ENGRGBNM.ogg',
 'OOUOLJDM.ogg',
 'REGGHYUR.ogg',
 'UHNWEOMC.ogg',
 'VIPMWTPN.ogg',
 'OTHHJYYQ.ogg',
 'CLISUDNG.ogg',
 'MWCCJLVI.ogg',
 'RVNZHDEB.ogg',
 'QZRTJMIT.ogg',
 'NUDCIFEN.ogg',
 'KWEKQYAK.ogg',
 'PVMTDBOA.ogg',
 'NHMRYAZF.ogg',
 'KFKNNMYC.ogg',
 'POROSRTU.ogg',
 'UYTWMLKF.ogg',
 'PJIDDJJM.ogg',
 'UIMHYCZM.ogg',
 'DWDVNBPZ.ogg',
 'YEJMFTRD.ogg',
 'LUTNHMYP.ogg',
 'ACILIPFX.ogg',
 'JIAMFPAW.ogg',
 'PBQSXOKW.ogg',
 'AUZLGVYE.ogg',
 'XIATBHRP.ogg',
 'NLVDALJE.ogg',
 'REPKEBTX.ogg',
 'JROSNUEZ.ogg',
 'QKKZJYFD.ogg',
 'FLSBYERJ.ogg',
 'HXHYAKRN.ogg',
 'QEJRGFAA.ogg',
 'ZVJRKGGO.ogg',
 'KWGGZOTX.ogg',
 'TBVCCZTW.ogg',
 'CEASFVGJ.ogg',
 'OUCARFSC.ogg',
 'FEEJHXDZ.ogg',
 'JEBIZYOW.ogg',
 'XJXGJNUE.ogg',
 'EYDXOMDC.ogg',
 'KCJHCKCV.ogg',
 'OUALDXII.ogg',
 'PWIMZHYW.ogg',
 'VFLXIMXS.ogg',
 'LWRLNKOQ.ogg',
 'NMIFYMXT.ogg',
 'DQSPZUQP.ogg',
 'RHYMBVKI.ogg',
 'ZFGXLXQS.ogg',
 'JPKNXOJA.ogg',
 'LNOIKVUE.ogg',
 'TPCJWEHJ.ogg',
 'HCWNEKHO.ogg',
 'DLQEGNUW.ogg',
 'BWWVKLOE.ogg',
 'FQAGCLDH.ogg',
 'DZCKEXGZ.ogg',
 'OZMNSSTO.ogg',
 'MHKDXYXO.ogg',
 'DWCXQVBA.ogg',
 'TKYJDDBE.ogg',
 'RFHSSRXV.ogg',
 'UONOQMDW.ogg',
 'GZMCJKOT.ogg',
 'DNNWROWQ.ogg',
 'IOQZMKKK.ogg',
 'DWOKVZYD.ogg',
 'ECIJTJNM.ogg',
 'HUUBVUEL.ogg',
 'OMFMWMUU.ogg',
 'VBDWCATE.ogg',
 'ORISQDVX.ogg',
 'TYJMTQCD.ogg',
 'YEVJICTP.ogg',
 'MPZHXDUO.ogg',
 'UVXPZQQD.ogg',
 'AITGONWI.ogg',
 'VBJHRFUW.ogg',
 'XBUTSGUB.ogg',
 'UEBMDJBK.ogg',
 'MMXKCNPF.ogg',
 'NPIIXSIR.ogg',
 'CNPZPDZG.ogg',
 'QKPXRNXE.ogg',
 'BZTQBGHU.ogg',
 'JIPJUTHQ.ogg',
 'PNHOJMUF.ogg',
 'EGXPFMBP.ogg',
 'GTOWUFWA.ogg',
 'WZMHMSOU.ogg',
 'NPSRGWBK.ogg',
 'CCAHCVOA.ogg',
 'GTETCOBY.ogg',
 'RTFOJSSW.ogg',
 'ZXVPIDWW.ogg',
 'GHZZOHGE.ogg',
 'BYGIBFQV.ogg',
 'COFMWPYC.ogg',
 'OCMILJWW.ogg',
 'EVGVATCL.ogg',
 'UYPYYYUO.ogg',
 'EFJTKDBX.ogg',
 'PKPACUEW.ogg',
 'VUMCRSIH.ogg',
 'SNRYGKVD.ogg',
 'HLSNQLIY.ogg',
 'ZIXPGDIG.ogg',
 'NQTULWRV.ogg',
 'YBZPFCVN.ogg',
 'ENXUIFRN.ogg',
 'ISGYYFGU.ogg',
 'VMMRZCDJ.ogg',
 'MLAVZXFK.ogg',
 'NCILRNAU.ogg',
 'QOUDYDFS.ogg',
 'OKGIGWNU.ogg',
 'YZCLKHSA.ogg',
 'BXLKXQIK.ogg',
 'JPVZAYOG.ogg',
 'GKHHSGGZ.ogg',
 'BJNDLBMO.ogg',
 'VEMNRCVS.ogg',
 'NBJCIIDF.ogg',
 'PVZZFEEB.ogg',
 'ITXKXGSG.ogg',
 'ZHQRCLSY.ogg',
 'VKDVERVX.ogg',
 'DHLAGYUU.ogg',
 'TRRUQSHC.ogg',
 'TMMIDCWB.ogg',
 'CUYCGXGO.ogg',
 'VXOFEXZO.ogg',
 'NJMFYSMH.ogg',
 'VDSLIKSX.ogg',
 'KOGGITBH.ogg',
 'BEGNBEUM.ogg',
 'JUYYBOIA.ogg',
 'HJKDHHNB.ogg',
 'GOZHBBAJ.ogg',
 'UMXIHZIM.ogg',
 'XLKIXWRM.ogg',
 'MCNRKKMV.ogg',
 'GGRWUPXN.ogg',
 'XHWXHIHM.ogg',
 'LTLFZIEI.ogg',
 'PGRNDKEL.ogg',
 'FLTBBNZT.ogg',
 'TAGYXACN.ogg',
 'VCVHFYVA.ogg',
 'CIOOIUBT.ogg',
 'XUNMIAFK.ogg',
 'PIWTVUML.ogg',
 'YSVEVVIM.ogg',
 'UCJMLYVH.ogg',
 'VPMYIECK.ogg',
 'QIXDHZSZ.ogg',
 'CVGSOOVN.ogg',
 'DZRAPXHR.ogg',
 'BXZKXAJD.ogg',
 'RJFWGESK.ogg',
 'VZLDOFQL.ogg',
 'TEDTUVFX.ogg',
 'ASFEKXQN.ogg',
 'XUJKKUDN.ogg',
 'AQLCYOUN.ogg',
 'MOVFSFFY.ogg',
 'XWSQUOOM.ogg',
 'WNCUOFPG.ogg',
 'CVPLUZTQ.ogg',
 'BRARZROC.ogg',
 'EFUAZAQC.ogg',
 'TFHNSFSD.ogg',
 'MKQNLLDJ.ogg',
 'TBFOYUGI.ogg',
 'MFRWDRXF.ogg',
 'LRLYKNKM.ogg',
 'HMVIZKUY.ogg',
 'PDKSRSDV.ogg',
 'EBDAZXTL.ogg',
 'TZXJYONM.ogg',
 'YZFGEFBY.ogg',
 'XHRBGHCC.ogg',
 'GCOWZEFZ.ogg',
 'PITRFDJS.ogg',
 'KBKVJGUH.ogg',
 'EVDYUAYZ.ogg',
 'HENCAEPO.ogg',
 'DJXGFILU.ogg',
 'OGWBCFPW.ogg',
 'ZYQSFRFX.ogg',
 'YJZKWYBA.ogg',
 'GFGUOJPW.ogg',
 'IKENDQHE.ogg',
 'SPNFSCCW.ogg',
 'RNDSEWOB.ogg',
 'ECFTYZSK.ogg',
 'XJKOLPSS.ogg',
 'RBFTQGYB.ogg',
 'HZQBFEXJ.ogg',
 'RIOSOAQO.ogg',
 'KECBYTUS.ogg',
 'DJXPIXUC.ogg',
 'GMFNKUFU.ogg',
 'XGDROFIF.ogg',
 'TMLDOURA.ogg',
 'KATUSONN.ogg',
 'IRYUVBDN.ogg',
 'SYHACYDT.ogg',
 'VKJHICQX.ogg',
 'IFWRRMPT.ogg',
 'HQVSYZGM.ogg',
 'XJAGIJMK.ogg',
 'ZPYDKZHC.ogg',
 'ZERMNXSQ.ogg',
 'IVQTNFKA.ogg',
 'QYIBIGPV.ogg',
 'HPZJUZGQ.ogg',
 'DTWUMQVT.ogg',
 'ILDXBWBR.ogg',
 'ITXZIGDK.ogg',
 'HHUFFKIK.ogg',
 'KQSMPKUZ.ogg',
 'FCWZQVPQ.ogg',
 'LJWIQDSR.ogg',
 'UNMTSTNT.ogg',
 'WXFYIFCJ.ogg',
 'NQKRSHZJ.ogg',
 'NPABTQPO.ogg',
 'MLGWVPCN.ogg',
 'PWGSPAGA.ogg',
 'GYSFVYAR.ogg',
 'IZHCXASA.ogg',
 'LKBUJPVZ.ogg',
 'XUHPWLUS.ogg',
 'MQJZGCGB.ogg',
 'JFMMORMC.ogg',
 'HBFBKOAV.ogg',
 'EPUIMRMP.ogg',
 'OAXHENPE.ogg',
 'UYHIFMUD.ogg',
 'FJHPUYJK.ogg',
 'WHYSPAJT.ogg',
 'PSSVRJKJ.ogg',
 'CVHPHQBX.ogg',
 'WAWKRPYV.ogg',
 'DQMOQHOI.ogg',
 'QFPEPAGH.ogg',
 'LQNBQAZT.ogg',
 'FQBJJBOH.ogg',
 'SGWQVCEB.ogg',
 'AMGGPNBN.ogg',
 'HZTVGYAI.ogg',
 'WAJNVKYT.ogg',
 'NVFXBPCQ.ogg',
 'ETRADZOR.ogg',
 'UZSJUBCH.ogg',
 'XRMOLZLJ.ogg',
 'DYKPKYOL.ogg',
 'GPMSECAF.ogg',
 'ECIDXDDJ.ogg',
 'IPWOSDSV.ogg',
 'UDLRSHPI.ogg',
 'BXMEBSNB.ogg',
 'AOLBFVXC.ogg',
 'LHNSNOFC.ogg',
 'MBDIJAEB.ogg',
 'NAYDFQEO.ogg',
 'LNYCSVVT.ogg',
 'JCRVVFGQ.ogg',
 'MSPOVGCF.ogg',
 'XDZGINYO.ogg',
 'MAYAQFTD.ogg',
 'QFEZKRRH.ogg',
 'SNQRLSQB.ogg',
 'LXRDNLNJ.ogg',
 'VVZSJSVQ.ogg',
 'GZKWFNMX.ogg',
 'HZBQSHMW.ogg',
 'AITUWDRP.ogg',
 'CEYECTRD.ogg',
 'DATRBQKU.ogg',
 'BFSKYVQU.ogg',
 'ZTKLEUOE.ogg',
 'JDCFXHLX.ogg',
 'CIXUAHEC.ogg',
 'UBGVWKQG.ogg',
 'ZXYHDSHE.ogg',
 'KAANCUGH.ogg',
 'KQBHBORM.ogg',
 'BLIXNPYP.ogg',
 'FWACIRPG.ogg',
 'SEGNELNP.ogg',
 'FOQIQVBK.ogg',
 'YLXHNTMU.ogg',
 'KVNAAFDE.ogg',
 'VXSICEGG.ogg',
 'ABOHAMXE.ogg',
 'YYLHQWPD.ogg',
 'NGCDSOKW.ogg',
 'RRNWHXJL.ogg',
 'SJUVMFKR.ogg',
 'SKUVTFQV.ogg',
 'SHZAFGWR.ogg',
 'JZFTKABB.ogg',
 'PXOBXUFU.ogg',
 'ASAAWLCL.ogg',
 'VSOUSAFN.ogg',
 'AGBGCXLZ.ogg',
 'NBFAHCBF.ogg',
 'IIIMSVZP.ogg',
 'ZEALAWCY.ogg',
 'BGLGKCJN.ogg',
 'PLHYRIBA.ogg',
 'ZVAAEYSE.ogg',
 'EGEMVVCK.ogg',
 'BZUQVSAC.ogg',
 'ISEMCFTM.ogg',
 'PJFCSOTU.ogg',
 'MUWFZQWO.ogg',
 'QOGAPYMF.ogg',
 'QOLNIZKW.ogg',
 'UGGRBWQX.ogg',
 'SFMREQBJ.ogg',
 'BGHMAVIE.ogg',
 'UDLFOGPQ.ogg',
 'TQDEKLYG.ogg',
 'JRVDWIEF.ogg',
 'NSVWPGAO.ogg',
 'LGOLVSCC.ogg',
 'JFXJZNGW.ogg',
 'PXEJPVJB.ogg',
 'ZYKFXJGP.ogg',
 'VOAXUPIG.ogg',
 'PJQWEWNP.ogg',
 'VZVFECYI.ogg',
 'TFWHPKZU.ogg',
 'YHMBKPXC.ogg',
 'RPBXHKWL.ogg',
 'UDTFBQWF.ogg',
 'TQMAFESA.ogg',
 'HZFDGHUM.ogg',
 'RASETVLT.ogg',
 'QBPLRCTV.ogg',
 'SVEKBCLM.ogg',
 'VJYTMKOQ.ogg',
 'DYDSHPHR.ogg',
 'FDRPVTEA.ogg',
 'GZKYKQUY.ogg',
 'GYYPVZNK.ogg',
 'BGCWLYVM.ogg',
 'UYTIMCQV.ogg',
 'AXOHDRKR.ogg',
 'NKGSUXUR.ogg',
 'UANFNPJM.ogg',
 'CSWQOMGB.ogg',
 'MTUIOTKY.ogg',
 'WRROPEOU.ogg',
 'WHRWJIKV.ogg',
 'AIURFHMM.ogg',
 'JEJVBEKW.ogg',
 'SBHUSHAY.ogg',
 'BOAEXSUW.ogg',
 'RLBXCIEL.ogg',
 'QEMVZSHV.ogg',
 'JPCCXUPH.ogg',
 'IRQMYSFP.ogg',
 'UIDEXVUB.ogg',
 'WIWBXYUE.ogg',
 'UBDEQEVX.ogg',
 'BSKSFBIH.ogg',
 'OVYNFIRV.ogg',
 'MRKDKHSB.ogg',
 'MSJWSJQG.ogg',
 'IXYHNNTY.ogg',
 'OESUDRWF.ogg',
 'CQYKUYZX.ogg',
 'CRBUDGZF.ogg',
 'FWXKXRTE.ogg',
 'HZVLBVEC.ogg',
 'TBSKDNSN.ogg',
 'DHTFBUCG.ogg',
 'GLWWTYOH.ogg',
 'PTKKUECD.ogg',
 'XWHAJEOZ.ogg',
 'TBZEIRQO.ogg',
 'HRXPBQTJ.ogg',
 'DPZDMRJM.ogg',
 'BKLDKVJA.ogg',
 'UUYUYEEF.ogg',
 'ASOGZMJX.ogg',
 'ZPFEFGWN.ogg',
 'RAIDANNK.ogg',
 'ROYGGNTB.ogg',
 'EFXGWPYW.ogg',
 'NZTWROXV.ogg',
 'OMXIEFWZ.ogg',
 'WEMWJFMI.ogg',
 'UUWUHMHL.ogg',
 'RUWOBZNI.ogg',
 'WFOWJOWI.ogg',
 'KGLZLIAG.ogg',
 'YELCIZYO.ogg',
 'RGCNTERW.ogg',
 'IFSYKPSL.ogg',
 'QGRSVTHR.ogg',
 'ZXZRXDCK.ogg',
 'CDDIOKRQ.ogg',
 'ARQPLZIH.ogg',
 'ZPRNNXAU.ogg',
 'RKQUSJGN.ogg',
 'KLJLTQKQ.ogg',
 'TBCZQUWJ.ogg',
 'YTYJPECR.ogg',
 'LUTMVAMO.ogg',
 'MGDGNXSM.ogg',
 'QBHRXJCG.ogg',
 'EHTTCZOG.ogg',
 'LSLAZWYX.ogg',
 'NLWJPXIW.ogg',
 'UQSEAFIS.ogg',
 'KONCQSMD.ogg',
 'EQADFPGW.ogg',
 'NOCKFSOR.ogg',
 'ZSSOCHZQ.ogg',
 'PIDNEASV.ogg',
 'WYTPJHFF.ogg',
 'OSJSQBNT.ogg',
 'NGGSATHT.ogg',
 'YTNBESGG.ogg',
 'DDNNULOU.ogg',
 'QCYMFKAB.ogg',
 'YERSXLRA.ogg',
 'VNRYTWFB.ogg',
 'FXQZLOXZ.ogg',
 'XXJHJRUJ.ogg',
 'DQCRHDQS.ogg',
 'LLJZSVNU.ogg',
 'JFJWCXAW.ogg',
 'ADIVLXIX.ogg',
 'MZSUHTNF.ogg',
 'HSUGWXSN.ogg',
 'CYXCMGJM.ogg',
 'MDZSNOED.ogg',
 'BAIYJBNR.ogg',
 'WROUXNLS.ogg',
 'UCOYYFHL.ogg',
 'SBCSGAUZ.ogg',
 'IFBDLLOF.ogg',
 'NLRCSRMP.ogg',
 'JKPFTQXB.ogg',
 'ZWRAXWJS.ogg',
 'OKRYGWZZ.ogg',
 'BZFZGZKW.ogg',
 'KEWPVSIY.ogg',
 'LBHFUNJN.ogg',
 'LJPEVCRE.ogg',
 'PCRVZRFR.ogg',
 'CWHZHHMB.ogg',
 'ESFEICOD.ogg',
 'XWHVCJLP.ogg',
 'ELMDWRNK.ogg',
 'JVMAFHPE.ogg',
 'ZAOCIBPO.ogg',
 'VIEOATBM.ogg',
 'ZAKUYHHZ.ogg',
 'FIFBNHGU.ogg',
 'HCENIRUE.ogg',
 'TIHFWPCN.ogg',
 'GIRALGUQ.ogg',
 'VUPABQNR.ogg',
 'HSOZNBJM.ogg',
 'VSDYFCCS.ogg',
 'BRLHLNSP.ogg',
 'ZCYXHUPU.ogg',
 'MCBOGDBA.ogg',
 'LYFQQOCC.ogg',
 'MGEEQHQT.ogg',
 'UAXTRWDE.ogg',
 'GUCPIESC.ogg',
 'WRCPUXKN.ogg',
 'RJBQUDOU.ogg',
 'WUWKMSZR.ogg',
 'VFDORODZ.ogg',
 'KDPDGRVB.ogg',
 'TAXSZPQB.ogg',
 'IMKIPVJL.ogg',
 'AGCXORSP.ogg',
 'RSAGCZOL.ogg',
 'MYZZEERA.ogg',
 'TERYHJJD.ogg',
 'LXIZCXIA.ogg',
 'ZSDCFFDR.ogg',
 'ZLFKIWCH.ogg',
 'FUMTDFMU.ogg',
 'BCXMMMZE.ogg',
 'VDJGEMDP.ogg',
 'OLFJXRJU.ogg',
 'YFKJDJPM.ogg',
 'AQOFXYED.ogg',
 'PXVWYPCC.ogg',
 'UXFQLZTM.ogg',
 'DVKHDUVM.ogg',
 'FZWKJYYC.ogg',
 'MCDVNYFH.ogg',
 'SVXGNYBC.ogg',
 'TVKRDOAQ.ogg',
 'GZNNOPRA.ogg',
 'RWUMVMGK.ogg',
 'YNZWBVPM.ogg',
 'YNRMYLFN.ogg',
 'IXNXSPYR.ogg',
 'IBXBTPFA.ogg',
 'SOXBQDKY.ogg',
 'YTETLJTK.ogg',
 'DIXZVESQ.ogg',
 'WLLJPZAV.ogg',
 'MBLJMGFZ.ogg',
 'EFRZOELJ.ogg',
 'QIPXFCTV.ogg',
 'AUFQUJQE.ogg',
 'UEITASLC.ogg',
 'HBHDPDKV.ogg',
 'WVSZIVZX.ogg',
 'UGJEBKXR.ogg',
 'VFFQVKWE.ogg',
 'BHQIJPJP.ogg',
 'FEAZCQLA.ogg',
 'NHYCQHMM.ogg',
 'QUUQVYGB.ogg',
 'ZOJMWRZZ.ogg',
 'KFMKRVUZ.ogg',
 'VGKIJHUS.ogg',
 'GEJJDDSP.ogg',
 'TVOGCPMB.ogg',
 'WJBLQEWC.ogg',
 'TWWELPBG.ogg',
 'XUDXVGDY.ogg',
 'MIOVTUBM.ogg',
 'JFLDHNIG.ogg',
 'ZQXCLARX.ogg',
 'ZHLLXFWL.ogg',
 'PDXANQNX.ogg',
 'VYURSQLG.ogg',
 'XZYSHVKO.ogg',
 'EPJBHJCW.ogg',
 'AXOWTHTV.ogg',
 'ZDDYOSJI.ogg',
 'LDLVEDCX.ogg',
 'NPHOZSAQ.ogg',
 'NHNRCXGE.ogg',
 'ISQYRSXY.ogg',
 'BCALYDOH.ogg',
 'UFGJKFVD.ogg',
 'QANEZCEC.ogg',
 'BRSVYLPB.ogg',
 'IVARACXI.ogg',
 'WGCBZUVM.ogg',
 'IUDGCJHJ.ogg',
 'LTKLKMIR.ogg',
 'WDRYEUPK.ogg',
 'ORKNDPQD.ogg',
 'RNCRKTTO.ogg',
 'WEBDOOLL.ogg',
 'UNVGSNYI.ogg',
 'NXHHCQNF.ogg',
 'XLTXCUAY.ogg',
 'YCMEXXHT.ogg',
 'MKMALZYH.ogg',
 'BHVCPZHQ.ogg',
 'HTUEPQLZ.ogg',
 'UVMXEVCY.ogg',
 'YUERQDTP.ogg',
 ...]

In [40]:
import pandas as pd  

train=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/train.csv")

In [41]:
train

             id                  path label
0      RUNQPNJF  ./train/RUNQPNJF.ogg  real
1      JFAWUOGJ  ./train/JFAWUOGJ.ogg  fake
2      RDKEKEVX  ./train/RDKEKEVX.ogg  real
3      QYHJDOFK  ./train/QYHJDOFK.ogg  real
4      RSPQNHAO  ./train/RSPQNHAO.ogg  real
...         ...                   ...   ...
55433  NJGPMAJL  ./train/NJGPMAJL.ogg  real
55434  SZXIACUZ  ./train/SZXIACUZ.ogg  fake
55435  PXLBTGRH  ./train/PXLBTGRH.ogg  fake
55436  CGGQGPOQ  ./train/CGGQGPOQ.ogg  fake
55437  CPMKEDIS  ./train/CPMKEDIS.ogg  fake

[55438 rows x 3 columns]

In [42]:
train=train.sort_values(['id','path','label'])
train

             id                  path label
39661  AAACWKPZ  ./train/AAACWKPZ.ogg  fake
39539  AAAQOZYI  ./train/AAAQOZYI.ogg  fake
655    AAAWBXQE  ./train/AAAWBXQE.ogg  real
29647  AABHDRLX  ./train/AABHDRLX.ogg  real
16890  AABXXHMU  ./train/AABXXHMU.ogg  real
...         ...                   ...   ...
19183  ZZZMJSBX  ./train/ZZZMJSBX.ogg  fake
20744  ZZZRTSKN  ./train/ZZZRTSKN.ogg  fake
25482  ZZZSAANM  ./train/ZZZSAANM.ogg  real
22209  ZZZSYEYS  ./train/ZZZSYEYS.ogg  fake
1125   ZZZTCIWY  ./train/ZZZTCIWY.ogg  fake

[55438 rows x 3 columns]

In [43]:
import natsort
train_list=natsort.natsorted(train_list)

In [44]:
train['label'].isnull().sum()

0

In [45]:
train_list

['AAACWKPZ.ogg',
 'AAAQOZYI.ogg',
 'AAAWBXQE.ogg',
 'AABHDRLX.ogg',
 'AABXXHMU.ogg',
 'AACAYDKC.ogg',
 'AACBAWMZ.ogg',
 'AACEAXVU.ogg',
 'AACHVERO.ogg',
 'AACYAWEH.ogg',
 'AADDNUMU.ogg',
 'AADKWHEE.ogg',
 'AADPDAER.ogg',
 'AADQUEFI.ogg',
 'AAECEROJ.ogg',
 'AAEYTHSY.ogg',
 'AAFFVAWD.ogg',
 'AAFNYPXE.ogg',
 'AAGDMPXZ.ogg',
 'AAGIITHH.ogg',
 'AAGXILIN.ogg',
 'AAGZDQDL.ogg',
 'AAHKQWBB.ogg',
 'AAIGXLUD.ogg',
 'AAIINGWH.ogg',
 'AAIKZLBQ.ogg',
 'AAIXOVVV.ogg',
 'AAIYWHUF.ogg',
 'AAJEQLVT.ogg',
 'AAJKXPIW.ogg',
 'AAJMPRLS.ogg',
 'AAJSFGQB.ogg',
 'AAKKEAOL.ogg',
 'AAKXVWXI.ogg',
 'AALITDLH.ogg',
 'AALMMBOZ.ogg',
 'AALVLTSV.ogg',
 'AAMMREFE.ogg',
 'AANJJHYA.ogg',
 'AANOXTME.ogg',
 'AANUFJBH.ogg',
 'AAOEAZJW.ogg',
 'AAOFKKOG.ogg',
 'AAOYUWCN.ogg',
 'AAPELQFY.ogg',
 'AAPGWSKV.ogg',
 'AAPWJSUB.ogg',
 'AAQBLCRK.ogg',
 'AAQBNHMD.ogg',
 'AAQBQXCT.ogg',
 'AAQFLJFN.ogg',
 'AAQJRBNN.ogg',
 'AAQNTEKV.ogg',
 'AAQQXFSY.ogg',
 'AARBSIOH.ogg',
 'AARGVJZI.ogg',
 'AARGWRKZ.ogg',
 'AARRJAAQ.ogg',
 'AASWUMSW.ogg',
 'AATCFCVI.ogg',
 'AATLVEWK.ogg',
 'AATQICFM.ogg',
 'AATTJCGE.ogg',
 'AATTWSHA.ogg',
 'AAUAYKVM.ogg',
 'AAUEYCPM.ogg',
 'AAUSMRIH.ogg',
 'AAUTECVW.ogg',
 'AAWRAXMA.ogg',
 'AAWWBNIZ.ogg',
 'AAWWHHJX.ogg',
 'AAWZUHOB.ogg',
 'AAXQREUD.ogg',
 'AAXSBNDD.ogg',
 'AAXYCDPY.ogg',
 'AAYKMDBZ.ogg',
 'AAYPWYKF.ogg',
 'AAYTHXYW.ogg',
 'AAYYBEHJ.ogg',
 'AAZJOTGS.ogg',
 'AAZTWMFP.ogg',
 'AAZYAGMM.ogg',
 'ABAENKHV.ogg',
 'ABAFLSLF.ogg',
 'ABBIUGTR.ogg',
 'ABBZBMWL.ogg',
 'ABCPBMFW.ogg',
 'ABCVBHOB.ogg',
 'ABDOJNBI.ogg',
 'ABEFAEHN.ogg',
 'ABEMMSDM.ogg',
 'ABEOIKVE.ogg',
 'ABFGDXNL.ogg',
 'ABFJWPVZ.ogg',
 'ABFLRFQS.ogg',
 'ABFLVQJN.ogg',
 'ABFQLXGA.ogg',
 'ABGTOQQP.ogg',
 'ABHCEUXO.ogg',
 'ABHKMALR.ogg',
 'ABHPHEQR.ogg',
 'ABICOCXR.ogg',
 'ABJOLJDE.ogg',
 'ABKCBVEX.ogg',
 'ABKEQPLS.ogg',
 'ABKFHZQH.ogg',
 'ABKGIXCK.ogg',
 'ABKUMPGG.ogg',
 'ABKXHBIM.ogg',
 'ABLARKBT.ogg',
 'ABLIHAZW.ogg',
 'ABLNKKUX.ogg',
 'ABLWKUWO.ogg',
 'ABMDYAQT.ogg',
 'ABMPTGUJ.ogg',
 'ABMTFRFR.ogg',
 'ABNJDLFT.ogg',
 'ABNPAPHJ.ogg',
 'ABNSMWQL.ogg',
 'ABNYBNQV.ogg',
 'ABOAJFJU.ogg',
 'ABODBMGT.ogg',
 'ABOGAUEA.ogg',
 'ABOHAMXE.ogg',
 'ABOQWAGI.ogg',
 'ABOUKFBY.ogg',
 'ABOZOOGW.ogg',
 'ABPBTZOA.ogg',
 'ABPERQHZ.ogg',
 'ABPFZVZA.ogg',
 'ABPNIJHE.ogg',
 'ABPPUMMV.ogg',
 'ABPQJSIJ.ogg',
 'ABQFMETL.ogg',
 'ABRQWDWI.ogg',
 'ABRXILJS.ogg',
 'ABSHFXDX.ogg',
 'ABSNZUNO.ogg',
 'ABSPZPGI.ogg',
 'ABSWVZJA.ogg',
 'ABSXQNYR.ogg',
 'ABTLKJXD.ogg',
 'ABTNXFZS.ogg',
 'ABTPCQFA.ogg',
 'ABUHXIXM.ogg',
 'ABUNGWUU.ogg',
 'ABUQBWXC.ogg',
 'ABUUKHXR.ogg',
 'ABVBMDVV.ogg',
 'ABVBWXRP.ogg',
 'ABVGOCCV.ogg',
 'ABVGQMUB.ogg',
 'ABVWWSBB.ogg',
 'ABWCFFHK.ogg',
 'ABWUXCMN.ogg',
 'ABXJPTKW.ogg',
 'ABYCORVQ.ogg',
 'ABYKGYGO.ogg',
 'ABYNSDDG.ogg',
 'ABYOZVEE.ogg',
 'ABYRDEYH.ogg',
 'ABYWCRPI.ogg',
 'ABYZABZD.ogg',
 'ABYZNHTZ.ogg',
 'ABZCSMEE.ogg',
 'ABZRXUIA.ogg',
 'ACADZSLP.ogg',
 'ACAQLVEP.ogg',
 'ACAXJQVH.ogg',
 'ACCFXCMA.ogg',
 'ACCIDWEB.ogg',
 'ACCIREEY.ogg',
 'ACCJJVII.ogg',
 'ACCRYQFF.ogg',
 'ACCVDILY.ogg',
 'ACDLJRDR.ogg',
 'ACDRCJLG.ogg',
 'ACDYPDEM.ogg',
 'ACERXOAR.ogg',
 'ACEVNLTT.ogg',
 'ACEZIJAB.ogg',
 'ACFGHOWF.ogg',
 'ACFQUFYO.ogg',
 'ACFWDRVT.ogg',
 'ACGFRPRI.ogg',
 'ACGUAHMM.ogg',
 'ACHJDZOZ.ogg',
 'ACHMYSZY.ogg',
 'ACHORSDD.ogg',
 'ACHRSWBA.ogg',
 'ACHVQDUS.ogg',
 'ACIFENNO.ogg',
 'ACIHPMPW.ogg',
 'ACILIPFX.ogg',
 'ACIWOKDJ.ogg',
 'ACJUMQTR.ogg',
 'ACKCEXWX.ogg',
 'ACKSBUPD.ogg',
 'ACLGRMWV.ogg',
 'ACLJSORS.ogg',
 'ACLQGXBK.ogg',
 'ACMIDJBL.ogg',
 'ACMMKTIX.ogg',
 'ACMVOVPG.ogg',
 'ACMVWCLI.ogg',
 'ACMWONON.ogg',
 'ACNMORJU.ogg',
 'ACOCDNKO.ogg',
 'ACOGLDLN.ogg',
 'ACOHIIDN.ogg',
 'ACOYEPCS.ogg',
 'ACPGWVHU.ogg',
 'ACPNWAZP.ogg',
 'ACPPUGMA.ogg',
 'ACQBNMSF.ogg',
 'ACQYANTU.ogg',
 'ACRFDLZL.ogg',
 'ACRLASKU.ogg',
 'ACRLDUAX.ogg',
 'ACRXBUQB.ogg',
 'ACSANEKN.ogg',
 'ACSBLOUY.ogg',
 'ACSCYAQJ.ogg',
 'ACSTVSFE.ogg',
 'ACTDYAIM.ogg',
 'ACTOJCHP.ogg',
 'ACTVDSPZ.ogg',
 'ACUUCPDE.ogg',
 'ACVBIICI.ogg',
 'ACVLQWUT.ogg',
 'ACWBHUHH.ogg',
 'ACWCEZKR.ogg',
 'ACWJDIYF.ogg',
 'ACWJFMDA.ogg',
 'ACWPMQUS.ogg',
 'ACXQVBZU.ogg',
 'ACXSNPAG.ogg',
 'ACYDVUSW.ogg',
 'ACYDXMGH.ogg',
 'ACYNKSXM.ogg',
 'ACYPSUDL.ogg',
 'ACYWILHM.ogg',
 'ACZDWFJU.ogg',
 'ACZHJEMZ.ogg',
 'ACZQHZVX.ogg',
 'ACZYGLME.ogg',
 'ADBJJUZZ.ogg',
 'ADBMDAGD.ogg',
 'ADCHBQBA.ogg',
 'ADCIPVAL.ogg',
 'ADCOOLKZ.ogg',
 'ADCPMILG.ogg',
 'ADCVPSTQ.ogg',
 'ADDBUOGS.ogg',
 'ADDGDTIE.ogg',
 'ADDVJJOY.ogg',
 'ADECASSY.ogg',
 'ADEJFHOY.ogg',
 'ADESWDSC.ogg',
 'ADEVHVOE.ogg',
 'ADFBFFAQ.ogg',
 'ADFGBALZ.ogg',
 'ADFSOSBE.ogg',
 'ADFWZJRH.ogg',
 'ADGBKOGD.ogg',
 'ADGOEVLE.ogg',
 'ADGQHEZF.ogg',
 'ADGYLZAM.ogg',
 'ADHFLHEJ.ogg',
 'ADHFTIVB.ogg',
 'ADHJIKDG.ogg',
 'ADHRVVOP.ogg',
 'ADHSMHLP.ogg',
 'ADHWFMHZ.ogg',
 'ADIEYDPE.ogg',
 'ADITNUUO.ogg',
 'ADIVLXIX.ogg',
 'ADJDIWTE.ogg',
 'ADJGZNRP.ogg',
 'ADJKHDIW.ogg',
 'ADJPBUAD.ogg',
 'ADKBXRUV.ogg',
 'ADKELMJC.ogg',
 'ADKFQOID.ogg',
 'ADKHDYQV.ogg',
 'ADKRPWYK.ogg',
 'ADLACGUG.ogg',
 'ADLDAJMK.ogg',
 'ADLKVZEI.ogg',
 'ADLMZFOF.ogg',
 'ADLNYCMI.ogg',
 'ADLQFSRE.ogg',
 'ADMEGPRK.ogg',
 'ADMFGENI.ogg',
 'ADMQLVFV.ogg',
 'ADNGIXGH.ogg',
 'ADNISKIT.ogg',
 'ADNKTIJQ.ogg',
 'ADNMWDJP.ogg',
 'ADNNCBGZ.ogg',
 'ADNPUEYS.ogg',
 'ADNYCZPD.ogg',
 'ADNYUCEB.ogg',
 'ADOEZJIO.ogg',
 'ADPKWOHB.ogg',
 'ADQHEJLV.ogg',
 'ADQKGTQJ.ogg',
 'ADQTWRSE.ogg',
 'ADQWFHBR.ogg',
 'ADRNQPXO.ogg',
 'ADSDIJTR.ogg',
 'ADSNZACB.ogg',
 'ADSRKXVU.ogg',
 'ADSRXWKO.ogg',
 'ADSSBDPL.ogg',
 'ADSTEZYN.ogg',
 'ADSTJJIB.ogg',
 'ADSXGIKP.ogg',
 'ADTAAQCP.ogg',
 'ADTBVZIW.ogg',
 'ADTDYZQZ.ogg',
 'ADTJOXOA.ogg',
 'ADTQJQCI.ogg',
 'ADTUELXB.ogg',
 'ADUABJXF.ogg',
 'ADUBKOVZ.ogg',
 'ADUIUEAW.ogg',
 'ADUQCTQP.ogg',
 'ADUQOFSI.ogg',
 'ADVMSMTV.ogg',
 'ADVQXYIM.ogg',
 'ADWOYWAP.ogg',
 'ADWXBJDH.ogg',
 'ADXBGMXE.ogg',
 'ADYANHIO.ogg',
 'ADYGUSBE.ogg',
 'ADYJKHHY.ogg',
 'ADYPROEM.ogg',
 'ADYQNAPY.ogg',
 'ADZOBSNB.ogg',
 'ADZQZRLW.ogg',
 'ADZUQMJO.ogg',
 'AEAAVDAF.ogg',
 'AEBMFJWF.ogg',
 'AEBNACWI.ogg',
 'AEBPSOHM.ogg',
 'AEBZNUBU.ogg',
 'AECPNGMA.ogg',
 'AECRBGUJ.ogg',
 'AECVJJQK.ogg',
 'AEDCYQQT.ogg',
 'AEDHXXYD.ogg',
 'AEDPCSZJ.ogg',
 'AEDZPTDI.ogg',
 'AEEACJIW.ogg',
 'AEEOHCVR.ogg',
 'AEEUECPE.ogg',
 'AEEURZUP.ogg',
 'AEFBUARF.ogg',
 'AEFMVYBW.ogg',
 'AEFWQMYP.ogg',
 'AEGEBHFT.ogg',
 'AEGWUBEU.ogg',
 'AEHCWTPB.ogg',
 'AEHDZWQM.ogg',
 'AEHVGZKG.ogg',
 'AEIAQJXV.ogg',
 'AEIKQDHC.ogg',
 'AEIRDQKD.ogg',
 'AEIZRMHG.ogg',
 'AEJFIPHV.ogg',
 'AEJJCUCT.ogg',
 'AEJMEDNT.ogg',
 'AEKDGZXN.ogg',
 'AEKOBTOE.ogg',
 'AEKSMDCO.ogg',
 'AELDKNXQ.ogg',
 'AELSBQQL.ogg',
 'AEMDYPFZ.ogg',
 'AEMHVPVW.ogg',
 'AEMKIWDO.ogg',
 'AEMMWATT.ogg',
 'AEMZZPPA.ogg',
 'AENBNFSI.ogg',
 'AENRBUAL.ogg',
 'AENTVFFM.ogg',
 'AENTYNMG.ogg',
 'AENWKPQE.ogg',
 'AEOFNIMF.ogg',
 'AEOHOHBW.ogg',
 'AEOXUSYR.ogg',
 'AEPGTXMC.ogg',
 'AEQHYULU.ogg',
 'AERPPYWP.ogg',
 'AERTUDRE.ogg',
 'AESCIYMY.ogg',
 'AESNSXZH.ogg',
 'AETIFRQU.ogg',
 'AETMLJQY.ogg',
 'AETMNHHW.ogg',
 'AETOGHFY.ogg',
 'AETWPQPP.ogg',
 'AEUDCUAC.ogg',
 'AEUWOAIB.ogg',
 'AEUYTICZ.ogg',
 'AEVCRCFP.ogg',
 'AEVJCMCP.ogg',
 'AEVKUTWY.ogg',
 'AEVNJDXP.ogg',
 'AEWICJRW.ogg',
 'AEWJZEME.ogg',
 'AEWTPDON.ogg',
 'AEWVHKYT.ogg',
 'AEXGOQDL.ogg',
 'AEXKWYDW.ogg',
 'AEXNBZLD.ogg',
 'AEXWQOKG.ogg',
 'AEXYVJTN.ogg',
 'AEYBZATW.ogg',
 'AEYLNOZG.ogg',
 'AEYOLXXC.ogg',
 'AEYSCGLW.ogg',
 'AEYXWGZQ.ogg',
 'AEZDKBEY.ogg',
 'AEZDYISN.ogg',
 'AEZYLUQL.ogg',
 'AFAAYJSI.ogg',
 'AFACNPAK.ogg',
 'AFADRIRJ.ogg',
 'AFAGCXCK.ogg',
 'AFALXUGS.ogg',
 'AFAMVIHQ.ogg',
 'AFANLUMA.ogg',
 'AFBLGBET.ogg',
 'AFBLTGOK.ogg',
 'AFBQLTEG.ogg',
 'AFBXWLNK.ogg',
 'AFBZWKVM.ogg',
 'AFCEQCVZ.ogg',
 'AFCYFLUW.ogg',
 'AFDJUTMO.ogg',
 'AFDPMDHK.ogg',
 'AFEHOGCJ.ogg',
 'AFEYUVPQ.ogg',
 'AFFLBOVF.ogg',
 'AFGCNCUU.ogg',
 'AFHOVMJV.ogg',
 'AFIFNCLP.ogg',
 'AFIKKLUO.ogg',
 'AFIROKXK.ogg',
 'AFIUYGOA.ogg',
 'AFJMVZLF.ogg',
 'AFJPEUHJ.ogg',
 'AFJWZYRF.ogg',
 'AFKXTQZF.ogg',
 'AFLFVIKD.ogg',
 'AFLHPTQF.ogg',
 'AFLZWGMH.ogg',
 'AFMGPDKW.ogg',
 'AFNLQZQL.ogg',
 'AFNXJSXO.ogg',
 'AFOPZPTL.ogg',
 'AFPGGOGL.ogg',
 'AFPVFIAV.ogg',
 'AFPWRHRB.ogg',
 'AFQEFLJL.ogg',
 'AFQGQEQK.ogg',
 'AFQHSXTQ.ogg',
 'AFQRCQUU.ogg',
 'AFQSNMRI.ogg',
 'AFRBXNQG.ogg',
 'AFRGMQYW.ogg',
 'AFRMTWGE.ogg',
 'AFROULCH.ogg',
 'AFRPSDEM.ogg',
 'AFRPUJGI.ogg',
 'AFRVVHPK.ogg',
 'AFSEQMNR.ogg',
 'AFSJNYYL.ogg',
 'AFSJRKTL.ogg',
 'AFSQIJVH.ogg',
 'AFSVCRLI.ogg',
 'AFSVSBSD.ogg',
 'AFTARWGF.ogg',
 'AFTBNETW.ogg',
 'AFTKYLGZ.ogg',
 'AFTZDSCV.ogg',
 'AFUEJCDS.ogg',
 'AFUKENUG.ogg',
 'AFUYLVDO.ogg',
 'AFVONUFK.ogg',
 'AFVTCTBV.ogg',
 'AFVWWUVV.ogg',
 'AFVXVZCM.ogg',
 'AFWDAERX.ogg',
 'AFWIEFWW.ogg',
 'AFWJNPMB.ogg',
 'AFWTBXQH.ogg',
 'AFWUUVYE.ogg',
 'AFXBKPRE.ogg',
 'AFXPGSFR.ogg',
 'AFYDFEQE.ogg',
 'AFYNCSIZ.ogg',
 'AFYOEBAF.ogg',
 'AFYZJFSO.ogg',
 'AFZGHEGW.ogg',
 'AFZJCVEA.ogg',
 'AFZNNBMJ.ogg',
 'AFZQULOH.ogg',
 'AFZWGKYO.ogg',
 'AGAALQTR.ogg',
 'AGAGSFMQ.ogg',
 'AGAPPMIX.ogg',
 'AGARSDKA.ogg',
 'AGASUWQT.ogg',
 'AGAUSEOT.ogg',
 'AGBAFONA.ogg',
 'AGBESGIE.ogg',
 'AGBGCXLZ.ogg',
 'AGBGYVPT.ogg',
 'AGBOALAT.ogg',
 'AGBUUVJE.ogg',
 'AGCHKVRQ.ogg',
 'AGCLFAQW.ogg',
 'AGCPUJHS.ogg',
 'AGCXORSP.ogg',
 'AGDAVVQQ.ogg',
 'AGDEVNQT.ogg',
 'AGDQIQFV.ogg',
 'AGDUPIND.ogg',
 'AGECTYKU.ogg',
 'AGEFYCBJ.ogg',
 'AGFDJUHD.ogg',
 'AGGDYNKC.ogg',
 'AGGGZLDV.ogg',
 'AGGMNOKU.ogg',
 'AGGXLHHC.ogg',
 'AGGXPHJD.ogg',
 'AGHATMQF.ogg',
 'AGIAJKYN.ogg',
 'AGIDDTIO.ogg',
 'AGILFEGO.ogg',
 'AGIQONAU.ogg',
 'AGIWVZKG.ogg',
 'AGJJZMVD.ogg',
 'AGJVQMDF.ogg',
 'AGJZCNCE.ogg',
 'AGKJBCAS.ogg',
 'AGKYVNAD.ogg',
 'AGLBDSJI.ogg',
 'AGLLRTPA.ogg',
 'AGLZYODF.ogg',
 'AGMWNVRF.ogg',
 'AGNBHAYY.ogg',
 'AGNQKNGC.ogg',
 'AGNZMIYK.ogg',
 'AGOHEFCJ.ogg',
 'AGOYCZEA.ogg',
 'AGPFLSOQ.ogg',
 'AGPQRXSM.ogg',
 'AGPTZJVF.ogg',
 'AGPYZILJ.ogg',
 'AGPZJCTE.ogg',
 'AGQCQXKL.ogg',
 'AGQCZWTI.ogg',
 'AGQFSDWT.ogg',
 'AGTLOBCF.ogg',
 'AGTPLHYB.ogg',
 'AGUGWFPO.ogg',
 'AGUNIFYQ.ogg',
 'AGUUHNCQ.ogg',
 'AGUZUPLU.ogg',
 'AGVAQSQO.ogg',
 'AGVEEARW.ogg',
 'AGVHCDDI.ogg',
 'AGVJCHVD.ogg',
 'AGVMGXSE.ogg',
 'AGVTOYVT.ogg',
 'AGWBLKOF.ogg',
 'AGWLICGR.ogg',
 'AGWMDZHB.ogg',
 'AGWXWLJP.ogg',
 'AGXMUWTF.ogg',
 'AGXXOJFP.ogg',
 'AGXYQIWN.ogg',
 'AGYCNBTW.ogg',
 'AGYLMIXE.ogg',
 'AGYZIVWR.ogg',
 'AGZPKXZS.ogg',
 'AHAAHLII.ogg',
 'AHAKRHKG.ogg',
 'AHBBPEMI.ogg',
 'AHCJYNJY.ogg',
 'AHDHDSEI.ogg',
 'AHDHXRRS.ogg',
 'AHDLDDUW.ogg',
 'AHDXYXNM.ogg',
 'AHDYOPHA.ogg',
 'AHEDSKDV.ogg',
 'AHEESOWJ.ogg',
 'AHENKMTJ.ogg',
 'AHFALZBA.ogg',
 'AHFCJALQ.ogg',
 'AHFNTEYW.ogg',
 'AHFVYCEQ.ogg',
 'AHGHLXSI.ogg',
 'AHGWLYDO.ogg',
 'AHHCNALZ.ogg',
 'AHHHPVXP.ogg',
 'AHHKSEZU.ogg',
 'AHHRIEZK.ogg',
 'AHHSAEJC.ogg',
 'AHIGTLCR.ogg',
 'AHIHQUVW.ogg',
 'AHIZVYUL.ogg',
 'AHJDQCGC.ogg',
 'AHJGLZQK.ogg',
 'AHJIBBAN.ogg',
 'AHJQEQQY.ogg',
 'AHJXGNEV.ogg',
 'AHKOYGQT.ogg',
 'AHLFJSQN.ogg',
 'AHLZMMEQ.ogg',
 'AHMAAWJD.ogg',
 'AHNKISAV.ogg',
 'AHNWFVNZ.ogg',
 'AHOJUHUF.ogg',
 'AHOLOSXE.ogg',
 'AHOVCIUA.ogg',
 'AHPMGUFF.ogg',
 'AHPUYDZQ.ogg',
 'AHPZBRGZ.ogg',
 'AHQCHOZM.ogg',
 'AHQHPOWN.ogg',
 'AHQJBAEO.ogg',
 'AHQNWZOY.ogg',
 'AHQPKPWQ.ogg',
 'AHRVGKVS.ogg',
 'AHRYQXUU.ogg',
 'AHSOCDYE.ogg',
 'AHSVTKRX.ogg',
 'AHTGUDEZ.ogg',
 'AHUEGHST.ogg',
 'AHUQLBHS.ogg',
 'AHUUSJOB.ogg',
 'AHVGNTRH.ogg',
 'AHVSZZGR.ogg',
 'AHVZLBGD.ogg',
 'AHWARRXT.ogg',
 'AHWDQGEF.ogg',
 'AHWMRDHV.ogg',
 'AHWQXQGQ.ogg',
 'AHWWLXXU.ogg',
 'AHXEIWPG.ogg',
 'AHXHREHW.ogg',
 'AHXLKIOJ.ogg',
 'AHXMGMPN.ogg',
 'AHXSBEFB.ogg',
 'AHYJVYRQ.ogg',
 'AHYTRPWQ.ogg',
 'AHYUUOKD.ogg',
 'AHZJXKGU.ogg',
 'AHZNAIDB.ogg',
 'AHZYJDTJ.ogg',
 'AIAGVZTM.ogg',
 'AIALEWIS.ogg',
 'AIAPAZIG.ogg',
 'AIAWJKGB.ogg',
 'AIBHCRTA.ogg',
 'AIBKDEPJ.ogg',
 'AIBNKKTD.ogg',
 'AIBTGPHR.ogg',
 'AIBXWDGX.ogg',
 'AICDZCBI.ogg',
 'AICNVWNS.ogg',
 'AICPVDQI.ogg',
 'AICQBQNH.ogg',
 'AICTFDLS.ogg',
 'AICWGBIU.ogg',
 'AIDHLGBC.ogg',
 'AIDJWOKA.ogg',
 'AIDTLCPO.ogg',
 'AIDWDJUD.ogg',
 'AIEHFHRX.ogg',
 'AIENUOJF.ogg',
 'AIEYUBGS.ogg',
 'AIEZGUQP.ogg',
 'AIFAIMIL.ogg',
 'AIFFTCRA.ogg',
 'AIFKCALK.ogg',
 'AIGEMOBQ.ogg',
 'AIGLPJKJ.ogg',
 'AIGNDNXA.ogg',
 'AIGZSPYB.ogg',
 'AIHQDZKQ.ogg',
 'AIHWUKPA.ogg',
 'AIIBGBFV.ogg',
 'AIIWGURU.ogg',
 'AIIZYHUL.ogg',
 'AIJWMRBH.ogg',
 'AIJYUZOW.ogg',
 'AIKCHPNB.ogg',
 'AIKMLOVD.ogg',
 'AIKPDOES.ogg',
 'AIMZABGQ.ogg',
 'AINLHFKV.ogg',
 'AINNBHJS.ogg',
 'AIODDNBO.ogg',
 'AIONYGQJ.ogg',
 'AIPGEZXI.ogg',
 'AIPGFSGT.ogg',
 'AIPSVYPD.ogg',
 'AIQJPTMG.ogg',
 'AIQQQVXS.ogg',
 'AIQWULRX.ogg',
 'AIRQOATZ.ogg',
 'AIRTCHLM.ogg',
 'AISAUROZ.ogg',
 'AISBKBEJ.ogg',
 'AISDUJXR.ogg',
 'AISGGETB.ogg',
 'AISPOPMG.ogg',
 'AISTCFGB.ogg',
 'AITDUZSK.ogg',
 'AITGONWI.ogg',
 'AITNPRBX.ogg',
 'AITUWDRP.ogg',
 'AIULKIVE.ogg',
 'AIUOCNCF.ogg',
 'AIURFHMM.ogg',
 'AIUUXFNP.ogg',
 'AIVDIIYO.ogg',
 'AIVEZTLG.ogg',
 'AIVFNGIE.ogg',
 'AIVWEUKX.ogg',
 'AIWADXHX.ogg',
 'AIWAGPQV.ogg',
 'AIWLSPNW.ogg',
 'AIWQMJLI.ogg',
 'AIWTLUAW.ogg',
 'AIXFJBKY.ogg',
 'AIXHYDNK.ogg',
 'AIXPMMFQ.ogg',
 'AIXTCNBY.ogg',
 'AIXZPKTV.ogg',
 'AIYFWIBQ.ogg',
 'AIYUHKXV.ogg',
 'AIYVYURF.ogg',
 'AIYYJOTF.ogg',
 'AIZAKRGX.ogg',
 'AIZPIRKF.ogg',
 'AIZPQTGC.ogg',
 'AIZUYWLJ.ogg',
 'AJBBOGBI.ogg',
 'AJBFABSU.ogg',
 'AJBSHFMM.ogg',
 'AJBTDTLP.ogg',
 'AJBTFEKQ.ogg',
 'AJBTONYS.ogg',
 'AJBWBSLF.ogg',
 'AJBYDNEE.ogg',
 'AJCQUYEA.ogg',
 'AJDCSEFP.ogg',
 'AJDEIHLH.ogg',
 'AJDFZAST.ogg',
 'AJDJNHAX.ogg',
 'AJEEHGWH.ogg',
 'AJEEZSQV.ogg',
 'AJEOUQOA.ogg',
 'AJFGGKEV.ogg',
 'AJFNUCOQ.ogg',
 'AJFQNPMQ.ogg',
 'AJGTYVOA.ogg',
 'AJGUQXNG.ogg',
 'AJGZARXD.ogg',
 'AJHPIGHL.ogg',
 'AJIAVABC.ogg',
 'AJIHLVIK.ogg',
 'AJIRAXRP.ogg',
 'AJIRPNDJ.ogg',
 'AJJSURAR.ogg',
 'AJKFOBAY.ogg',
 'AJKICDSA.ogg',
 'AJKIDODQ.ogg',
 'AJKLDVND.ogg',
 'AJKOJSYY.ogg',
 'AJKRNRZI.ogg',
 'AJKSMJPZ.ogg',
 'AJLEKGSH.ogg',
 'AJLKWLKO.ogg',
 'AJLPHOXD.ogg',
 'AJMMMHCS.ogg',
 'AJMNXSND.ogg',
 'AJMQPQNP.ogg',
 'AJMZRSAS.ogg',
 'AJNBKOJC.ogg',
 'AJNBTLJG.ogg',
 'AJNHIQTS.ogg',
 'AJNJPVEM.ogg',
 'AJOBHLGL.ogg',
 'AJOLSXZK.ogg',
 'AJOSGWOI.ogg',
 'AJOYFNMS.ogg',
 'AJPKCXPA.ogg',
 'AJPKWURJ.ogg',
 'AJPNKBWZ.ogg',
 'AJPSSKBD.ogg',
 'AJQJHTCG.ogg',
 'AJQNRTTZ.ogg',
 'AJQUQREE.ogg',
 'AJQZKSVP.ogg',
 'AJRBNWGC.ogg',
 'AJRJNVRN.ogg',
 'AJRKDDJB.ogg',
 'AJRPMMBT.ogg',
 'AJSFXQCO.ogg',
 'AJTDNKAA.ogg',
 'AJTIBKDD.ogg',
 'AJTPMNCF.ogg',
 'AJUBTAOJ.ogg',
 'AJUQLRZT.ogg',
 'AJUSUGDF.ogg',
 'AJUUNRCL.ogg',
 'AJVGIHPT.ogg',
 'AJVNKKQZ.ogg',
 'AJVUHIKA.ogg',
 'AJVZYPZM.ogg',
 'AJWSGVNU.ogg',
 'AJWWROIZ.ogg',
 'AJWXBYDV.ogg',
 'AJWZVGYQ.ogg',
 'AJXGGEWK.ogg',
 'AJXOLTIK.ogg',
 'AJXRDEWE.ogg',
 'AJXYHFTT.ogg',
 'AJYFLCUM.ogg',
 'AJYKQUND.ogg',
 'AJYTMDPR.ogg',
 'AJYVMMXL.ogg',
 'AJYWNBUN.ogg',
 'AJYXWCSX.ogg',
 'AJZIXPAQ.ogg',
 'AJZRGJRC.ogg',
 'AKAFJQIQ.ogg',
 'AKAOQATA.ogg',
 'AKARVISS.ogg',
 'AKATDYQY.ogg',
 'AKAWIOTJ.ogg',
 'AKAXQIFV.ogg',
 'AKBOCJDQ.ogg',
 'AKBOOKWP.ogg',
 'AKBYXDIJ.ogg',
 'AKBZWEAO.ogg',
 'AKCMMVXO.ogg',
 'AKCWBZCG.ogg',
 'AKCZXFJK.ogg',
 'AKDCNLFW.ogg',
 'AKDEGHKT.ogg',
 'AKDHVILH.ogg',
 'AKEEKPEY.ogg',
 'AKEGKQNM.ogg',
 'AKENQBZF.ogg',
 'AKENWNCS.ogg',
 'AKENYJXT.ogg',
 'AKETLKSR.ogg',
 'AKEWLEVH.ogg',
 'AKFLOOHC.ogg',
 'AKGEZENQ.ogg',
 'AKGGXHQN.ogg',
 'AKGYSFGZ.ogg',
 'AKICDHVP.ogg',
 'AKICOEWM.ogg',
 'AKIJCVDI.ogg',
 'AKINHLRE.ogg',
 'AKIVXKHY.ogg',
 'AKJFWEVN.ogg',
 'AKJIAQTQ.ogg',
 'AKJWOGIJ.ogg',
 'AKKTFFGR.ogg',
 'AKKXIUZP.ogg',
 'AKLFGKDY.ogg',
 'AKLHOOFX.ogg',
 'AKLJZFUP.ogg',
 'AKLKPSUW.ogg',
 'AKLOKBGI.ogg',
 'AKLRNIEB.ogg',
 'AKOAQNHD.ogg',
 'AKOHYRJS.ogg',
 'AKOKVMAZ.ogg',
 'AKONRVMN.ogg',
 'AKOSOOMH.ogg',
 'AKPEPGAV.ogg',
 'AKPQVOME.ogg',
 'AKPSIZYR.ogg',
 'AKPUUBZJ.ogg',
 'AKQNHIAB.ogg',
 'AKQOLGKG.ogg',
 'AKQPMDCG.ogg',
 'AKRCRNDX.ogg',
 'AKRCYUMZ.ogg',
 'AKRKSEGR.ogg',
 'AKRYZNFX.ogg',
 'AKSBEDFZ.ogg',
 'AKSJTTYE.ogg',
 'AKSMPCOJ.ogg',
 'AKSRUOJV.ogg',
 'AKSZZXKT.ogg',
 'AKTHFKUH.ogg',
 'AKTUNTOW.ogg',
 'AKULBGIU.ogg',
 'AKULFXLG.ogg',
 'AKUPPIKH.ogg',
 'AKVGARWY.ogg',
 'AKVGCQDA.ogg',
 'AKVKQPFD.ogg',
 'AKVLQJIL.ogg',
 'AKVLVALO.ogg',
 'AKVYLYBQ.ogg',
 'AKWRMHMD.ogg',
 'AKWSISHL.ogg',
 'AKXEYBRY.ogg',
 'AKXFXZZG.ogg',
 'AKXLJPRX.ogg',
 'AKXLTZMU.ogg',
 'AKZRNPZD.ogg',
 'AKZTJYKP.ogg',
 'AKZUVEER.ogg',
 'AKZYHHJB.ogg',
 'ALAQUICV.ogg',
 'ALAQYZKJ.ogg',
 'ALAXYGNO.ogg',
 'ALBEXIOR.ogg',
 'ALBFNSMA.ogg',
 'ALBKCPGL.ogg',
 'ALBTVPAU.ogg',
 'ALBYWZGG.ogg',
 'ALCFUPBC.ogg',
 'ALCJGLII.ogg',
 'ALCOPRTA.ogg',
 'ALCWCCFT.ogg',
 'ALDBWRIZ.ogg',
 'ALDUCZCW.ogg',
 'ALEKIKZU.ogg',
 'ALETTBZH.ogg',
 'ALEZOAYY.ogg',
 'ALFHAZRH.ogg',
 'ALFVKBTQ.ogg',
 'ALFWKHIF.ogg',
 'ALGRYBFL.ogg',
 'ALGVLKVB.ogg',
 'ALGWJQMZ.ogg',
 'ALHTABEH.ogg',
 'ALHUUXIA.ogg',
 'ALIJEHEB.ogg',
 'ALIJNFRF.ogg',
 'ALIYGGTF.ogg',
 'ALJDGTKE.ogg',
 'ALJRZMBU.ogg',
 'ALJSBCDQ.ogg',
 'ALJUXRNQ.ogg',
 'ALKAOVNU.ogg',
 'ALKIUKHA.ogg',
 'ALKMVJWQ.ogg',
 'ALKRDVFF.ogg',
 'ALLHXIXS.ogg',
 'ALLMSOUQ.ogg',
 'ALLQOPBP.ogg',
 'ALLXCXXT.ogg',
 'ALLXYWYP.ogg',
 'ALMAPCIY.ogg',
 'ALMRKNPR.ogg',
 'ALMVHLWP.ogg',
 'ALNATJVU.ogg',
 'ALNUKCDQ.ogg',
 'ALNUYTRG.ogg',
 'ALOCVASW.ogg',
 'ALODTWUB.ogg',
 'ALOIRSSL.ogg',
 'ALOLZWEP.ogg',
 'ALOXHEML.ogg',
 'ALPDTTFM.ogg',
 'ALPFZXWE.ogg',
 'ALPXPRSG.ogg',
 'ALQFACBZ.ogg',
 'ALQQCIDE.ogg',
 'ALQSTIKZ.ogg',
 'ALRDVQWR.ogg',
 'ALRLDEKG.ogg',
 'ALRTKBMG.ogg',
 'ALSPOUQC.ogg',
 'ALSUQFDZ.ogg',
 'ALUMTIAL.ogg',
 'ALUOSDMB.ogg',
 'ALUXSHFV.ogg',
 'ALVWEEJU.ogg',
 'ALWFDQID.ogg',
 'ALWTQMZG.ogg',
 'ALXEHQLG.ogg',
 'ALXJLRDR.ogg',
 'ALXLIYVG.ogg',
 ...]

In [46]:
test=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/test.csv")
test

               id                   path
0      TEST_00000  ./test/TEST_00000.ogg
1      TEST_00001  ./test/TEST_00001.ogg
2      TEST_00002  ./test/TEST_00002.ogg
3      TEST_00003  ./test/TEST_00003.ogg
4      TEST_00004  ./test/TEST_00004.ogg
...           ...                    ...
49995  TEST_49995  ./test/TEST_49995.ogg
49996  TEST_49996  ./test/TEST_49996.ogg
49997  TEST_49997  ./test/TEST_49997.ogg
49998  TEST_49998  ./test/TEST_49998.ogg
49999  TEST_49999  ./test/TEST_49999.ogg

[50000 rows x 2 columns]

In [47]:
import librosa
import librosa.display
import numpy as np  


x=librosa.load(train_path+train_list[0])[0]
x

array([0.03395326, 0.05049137, 0.03909199, ..., 0.13583225, 0.1232833 ,
       0.        ], dtype=float32)

In [48]:
S = librosa.feature.melspectrogram(y=x, sr=8000, n_mels=200)
log_S = librosa.power_to_db(S, ref=np.max)
mfcc = librosa.feature.mfcc(S=log_S, n_mfcc=30)
n_mfcc = librosa.feature.delta(mfcc, order=2)
n_mfcc = n_mfcc.flatten()
n_mfcc=n_mfcc[:300]

In [49]:
n_mfcc[299]

1.0390635

In [50]:
n_mfcc.shape

(300,)

In [51]:
train_len=len(train_list)
test_len=len(test_list)

In [52]:
train_data=pd.DataFrame(index=range(train_len),columns=(['id','label']))
test_data=pd.DataFrame(index=range(test_len),columns=(['id']))

In [53]:
train_data['id']=train['id']
train_data['label']=train['label']

In [54]:
train_data

             id label
0      RUNQPNJF  real
1      JFAWUOGJ  fake
2      RDKEKEVX  real
3      QYHJDOFK  real
4      RSPQNHAO  real
...         ...   ...
55433  NJGPMAJL  real
55434  SZXIACUZ  fake
55435  PXLBTGRH  fake
55436  CGGQGPOQ  fake
55437  CPMKEDIS  fake

[55438 rows x 2 columns]

In [55]:
train_feature=pd.DataFrame(index=range(train_data.shape[0]),columns=range(n_mfcc.shape[0]))

In [56]:
train_feature

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
train_feature.shape

(55438, 300)

In [58]:
train_data.iloc[0,1]

'real'

In [59]:
test_data

        id
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
...    ...
49995  NaN
49996  NaN
49997  NaN
49998  NaN
49999  NaN

[50000 rows x 1 columns]

In [60]:
train_feature=pd.DataFrame(index=range(train_data.shape[0]),columns=range(n_mfcc.shape[0]))

In [61]:
train_feature.shape

(55438, 300)

In [62]:
x=librosa.load(train_path+train_list[2])[0]
S = librosa.feature.melspectrogram(y=x, sr=16000, n_mels=128)
log_S = librosa.power_to_db(S, ref=np.max)
mfcc = librosa.feature.mfcc(S=log_S, n_mfcc=30)
n_mfcc = librosa.feature.delta(mfcc, order=2)
n_mfcc=n_mfcc.flatten()
n_mfcc.shape
n_mfcc=n_mfcc[:800]
n_mfcc.shape

(800,)

In [63]:
import numpy as np
import librosa

# Constants
duration = 2  # seconds
sample_rate = 16000  # Hz

for i in range(train_feature.shape[0]):
    x = librosa.load(train_path + train_list[i], sr=sample_rate, duration=duration)[0]
    S = librosa.feature.melspectrogram(y=x, sr=sample_rate, n_mels=128)
    log_S = librosa.power_to_db(S, ref=np.max)
    mfcc = librosa.feature.mfcc(S=log_S, n_mfcc=20)
    mfcc_shape = mfcc.shape[1]

    # width 값을 mfcc_shape에 맞게 조정, 홀수이고 3 이상이어야 함
    if mfcc_shape < 3:
        width = 3  # mfcc_shape가 3보다 작으면 최소값 3으로 설정
    else:
        width = min(9, mfcc_shape - 1)  # mfcc_shape가 충분히 크면 9 이하로 조정
        if width % 2 == 0:
            width -= 1  # width가 짝수이면 홀수로 조정
    
    n_mfcc = librosa.feature.delta(mfcc, order=2, width=width)
    n_mfcc = n_mfcc.flatten()
    n_mfcc = n_mfcc[:300]

    
    for j in range(train_feature.shape[1]):
        if n_mfcc.shape[0] < 300:
            break
        train_feature.iloc[i, j] = n_mfcc[j]

In [64]:
train_feature

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
0,1.438519,1.438519,1.438519,1.438519,1.438519,2.746312,1.341054,-3.447641,-9.094271,-12.917919,...,-1.182487,0.711398,1.497095,1.404814,0.789971,0.64608,0.64608,0.64608,0.64608,0.64608
1,-25.90686,-25.90686,-25.90686,-25.90686,-25.90686,-17.379387,2.246948,16.650721,19.44792,12.75608,...,2.526754,1.06833,-0.398145,-2.48468,-4.388935,-4.14498,-2.141811,0.857629,3.262114,4.556356
2,-9.265671,-9.265671,-9.265671,-9.265671,-9.265671,-2.136198,4.5619,7.054737,5.1285,2.052986,...,-4.047248,-5.607961,-5.328619,-2.278079,1.571096,4.051303,4.017733,2.285928,3.335169,4.021658
3,12.194304,12.194304,12.194304,12.194304,12.194304,16.417101,10.615695,-0.616173,-11.808883,-13.913478,...,1.338306,-1.38725,-4.088012,-4.907184,-3.66424,-1.319175,1.903858,4.323899,4.126403,1.562672
4,6.901976,6.901976,6.901976,6.901976,6.901976,3.055412,-4.047513,-7.914245,-6.421064,-2.68299,...,1.480798,-0.845831,-0.845831,-0.845831,-0.845831,-0.845831,-1.825729,-1.825729,-1.825729,-1.825729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-7.681902,-7.681902,-7.681902,-7.681902,-7.681902,-10.621124,-6.423388,-4.476775,-1.161648,2.931834,...,-0.492598,-2.153574,-1.528402,-0.443851,-0.205066,-0.327911,-0.327911,-0.327911,-0.327911,-0.327911
55434,-4.70039,-4.70039,-4.70039,-4.70039,-4.70039,2.013616,8.407907,10.478395,6.018128,-1.079452,...,2.83453,0.320568,-1.943429,-3.503829,-2.799786,-0.257467,1.228969,0.380908,0.066585,-0.065431
55435,34.854847,34.854847,34.854847,34.854847,34.854847,38.405346,28.282476,14.494637,-5.210199,-20.876534,...,-0.99947,-2.945691,-8.138636,-9.117725,-6.248882,0.466669,8.233017,12.388657,10.6954,3.930505
55436,2.576622,2.576622,2.576622,2.576622,2.576622,3.27641,-0.907858,-5.612336,-7.652254,-5.872251,...,-0.919622,-3.063054,-0.42863,2.356253,3.891686,3.091029,-1.126633,-6.620365,-9.471728,-7.839835
55437,1.708457,1.708457,1.708457,1.708457,1.708457,4.501143,4.840662,4.899501,5.153507,4.483346,...,4.20815,0.590521,-0.233076,-0.696627,-0.628282,-0.75471,-2.871971,-5.43341,-5.076292,-0.248749

In [65]:
Y=pd.DataFrame(train['label'])

In [66]:
save_data=pd.concat([train_feature,Y],axis=1)

In [67]:
save_data

,0,1,2,3,4,5,6,7,8,9,...,291,292,293,294,295,296,297,298,299,label
0,1.438519,1.438519,1.438519,1.438519,1.438519,2.746312,1.341054,-3.447641,-9.094271,-12.917919,...,0.711398,1.497095,1.404814,0.789971,0.64608,0.64608,0.64608,0.64608,0.64608,real
1,-25.90686,-25.90686,-25.90686,-25.90686,-25.90686,-17.379387,2.246948,16.650721,19.44792,12.75608,...,1.06833,-0.398145,-2.48468,-4.388935,-4.14498,-2.141811,0.857629,3.262114,4.556356,fake
2,-9.265671,-9.265671,-9.265671,-9.265671,-9.265671,-2.136198,4.5619,7.054737,5.1285,2.052986,...,-5.607961,-5.328619,-2.278079,1.571096,4.051303,4.017733,2.285928,3.335169,4.021658,real
3,12.194304,12.194304,12.194304,12.194304,12.194304,16.417101,10.615695,-0.616173,-11.808883,-13.913478,...,-1.38725,-4.088012,-4.907184,-3.66424,-1.319175,1.903858,4.323899,4.126403,1.562672,real
4,6.901976,6.901976,6.901976,6.901976,6.901976,3.055412,-4.047513,-7.914245,-6.421064,-2.68299,...,-0.845831,-0.845831,-0.845831,-0.845831,-0.845831,-1.825729,-1.825729,-1.825729,-1.825729,real
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-7.681902,-7.681902,-7.681902,-7.681902,-7.681902,-10.621124,-6.423388,-4.476775,-1.161648,2.931834,...,-2.153574,-1.528402,-0.443851,-0.205066,-0.327911,-0.327911,-0.327911,-0.327911,-0.327911,real
55434,-4.70039,-4.70039,-4.70039,-4.70039,-4.70039,2.013616,8.407907,10.478395,6.018128,-1.079452,...,0.320568,-1.943429,-3.503829,-2.799786,-0.257467,1.228969,0.380908,0.066585,-0.065431,fake
55435,34.854847,34.854847,34.854847,34.854847,34.854847,38.405346,28.282476,14.494637,-5.210199,-20.876534,...,-2.945691,-8.138636,-9.117725,-6.248882,0.466669,8.233017,12.388657,10.6954,3.930505,fake
55436,2.576622,2.576622,2.576622,2.576622,2.576622,3.27641,-0.907858,-5.612336,-7.652254,-5.872251,...,-3.063054,-0.42863,2.356253,3.891686,3.091029,-1.126633,-6.620365,-9.471728,-7.839835,fake
55437,1.708457,1.708457,1.708457,1.708457,1.708457,4.501143,4.840662,4.899501,5.153507,4.483346,...,0.590521,-0.233076,-0.696627,-0.628282,-0.75471,-2.871971,-5.43341,-5.076292,-0.248749,fake

In [68]:
save_data2=save_data

In [69]:
save_data2=save_data.dropna(axis=0)

In [70]:
save_data2

,0,1,2,3,4,5,6,7,8,9,...,291,292,293,294,295,296,297,298,299,label
0,1.438519,1.438519,1.438519,1.438519,1.438519,2.746312,1.341054,-3.447641,-9.094271,-12.917919,...,0.711398,1.497095,1.404814,0.789971,0.64608,0.64608,0.64608,0.64608,0.64608,real
1,-25.90686,-25.90686,-25.90686,-25.90686,-25.90686,-17.379387,2.246948,16.650721,19.44792,12.75608,...,1.06833,-0.398145,-2.48468,-4.388935,-4.14498,-2.141811,0.857629,3.262114,4.556356,fake
2,-9.265671,-9.265671,-9.265671,-9.265671,-9.265671,-2.136198,4.5619,7.054737,5.1285,2.052986,...,-5.607961,-5.328619,-2.278079,1.571096,4.051303,4.017733,2.285928,3.335169,4.021658,real
3,12.194304,12.194304,12.194304,12.194304,12.194304,16.417101,10.615695,-0.616173,-11.808883,-13.913478,...,-1.38725,-4.088012,-4.907184,-3.66424,-1.319175,1.903858,4.323899,4.126403,1.562672,real
4,6.901976,6.901976,6.901976,6.901976,6.901976,3.055412,-4.047513,-7.914245,-6.421064,-2.68299,...,-0.845831,-0.845831,-0.845831,-0.845831,-0.845831,-1.825729,-1.825729,-1.825729,-1.825729,real
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-7.681902,-7.681902,-7.681902,-7.681902,-7.681902,-10.621124,-6.423388,-4.476775,-1.161648,2.931834,...,-2.153574,-1.528402,-0.443851,-0.205066,-0.327911,-0.327911,-0.327911,-0.327911,-0.327911,real
55434,-4.70039,-4.70039,-4.70039,-4.70039,-4.70039,2.013616,8.407907,10.478395,6.018128,-1.079452,...,0.320568,-1.943429,-3.503829,-2.799786,-0.257467,1.228969,0.380908,0.066585,-0.065431,fake
55435,34.854847,34.854847,34.854847,34.854847,34.854847,38.405346,28.282476,14.494637,-5.210199,-20.876534,...,-2.945691,-8.138636,-9.117725,-6.248882,0.466669,8.233017,12.388657,10.6954,3.930505,fake
55436,2.576622,2.576622,2.576622,2.576622,2.576622,3.27641,-0.907858,-5.612336,-7.652254,-5.872251,...,-3.063054,-0.42863,2.356253,3.891686,3.091029,-1.126633,-6.620365,-9.471728,-7.839835,fake
55437,1.708457,1.708457,1.708457,1.708457,1.708457,4.501143,4.840662,4.899501,5.153507,4.483346,...,0.590521,-0.233076,-0.696627,-0.628282,-0.75471,-2.871971,-5.43341,-5.076292,-0.248749,fake

In [71]:
save_data2.to_csv("train data no null(300).csv")

In [72]:
save_data2.isnull().sum()

0        0
1        0
2        0
3        0
4        0
        ..
296      0
297      0
298      0
299      0
label    0
Length: 301, dtype: int64