In [1]:
import pandas as pd   


submission=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/sample_submission.csv")


#submission.iloc[:,0:2]
submission

               id  fake  real
0      TEST_00000     0     0
1      TEST_00001     0     0
2      TEST_00002     0     0
3      TEST_00003     0     0
4      TEST_00004     0     0
...           ...   ...   ...
49995  TEST_49995     0     0
49996  TEST_49996     0     0
49997  TEST_49997     0     0
49998  TEST_49998     0     0
49999  TEST_49999     0     0

[50000 rows x 3 columns]

In [2]:
test_data=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/test.csv")
test_data

               id                   path
0      TEST_00000  ./test/TEST_00000.ogg
1      TEST_00001  ./test/TEST_00001.ogg
2      TEST_00002  ./test/TEST_00002.ogg
3      TEST_00003  ./test/TEST_00003.ogg
4      TEST_00004  ./test/TEST_00004.ogg
...           ...                    ...
49995  TEST_49995  ./test/TEST_49995.ogg
49996  TEST_49996  ./test/TEST_49996.ogg
49997  TEST_49997  ./test/TEST_49997.ogg
49998  TEST_49998  ./test/TEST_49998.ogg
49999  TEST_49999  ./test/TEST_49999.ogg

[50000 rows x 2 columns]

In [7]:
import os
import numpy as np
import pandas as pd
import librosa
import natsort
from sklearn.preprocessing import StandardScaler

test_path='/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/test/'
test_list=os.listdir(test_path)
test_list

['TEST_29550.ogg',
 'TEST_18955.ogg',
 'TEST_09680.ogg',
 'TEST_26663.ogg',
 'TEST_41820.ogg',
 'TEST_39743.ogg',
 'TEST_28896.ogg',
 'TEST_07875.ogg',
 'TEST_19493.ogg',
 'TEST_47289.ogg',
 'TEST_36470.ogg',
 'TEST_20212.ogg',
 'TEST_09858.ogg',
 'TEST_46197.ogg',
 'TEST_30001.ogg',
 'TEST_16978.ogg',
 'TEST_44958.ogg',
 'TEST_24074.ogg',
 'TEST_33508.ogg',
 'TEST_34267.ogg',
 'TEST_13800.ogg',
 'TEST_35179.ogg',
 'TEST_44780.ogg',
 'TEST_22405.ogg',
 'TEST_32616.ogg',
 'TEST_32170.ogg',
 'TEST_43789.ogg',
 'TEST_14809.ogg',
 'TEST_22363.ogg',
 'TEST_34501.ogg',
 'TEST_43951.ogg',
 'TEST_05904.ogg',
 'TEST_24712.ogg',
 'TEST_42497.ogg',
 'TEST_30767.ogg',
 'TEST_48804.ogg',
 'TEST_28128.ogg',
 'TEST_20574.ogg',
 'TEST_11971.ogg',
 'TEST_37008.ogg',
 'TEST_39025.ogg',
 'TEST_36316.ogg',
 'TEST_29236.ogg',
 'TEST_40280.ogg',
 'TEST_31479.ogg',
 'TEST_26105.ogg',
 'TEST_46829.ogg',
 'TEST_48810.ogg',
 'TEST_30773.ogg',
 'TEST_20560.ogg',
 'TEST_11965.ogg',
 'TEST_39031.ogg',
 'TEST_36302.ogg',
 'TEST_40294.ogg',
 'TEST_29222.ogg',
 'TEST_26111.ogg',
 'TEST_00868.ogg',
 'TEST_25418.ogg',
 'TEST_32164.ogg',
 'TEST_22377.ogg',
 'TEST_34515.ogg',
 'TEST_05910.ogg',
 'TEST_23069.ogg',
 'TEST_43945.ogg',
 'TEST_24706.ogg',
 'TEST_42483.ogg',
 'TEST_24060.ogg',
 'TEST_02919.ogg',
 'TEST_34273.ogg',
 'TEST_44794.ogg',
 'TEST_13814.ogg',
 'TEST_22411.ogg',
 'TEST_32602.ogg',
 'TEST_29544.ogg',
 'TEST_26677.ogg',
 'TEST_09694.ogg',
 'TEST_18941.ogg',
 'TEST_07861.ogg',
 'TEST_28882.ogg',
 'TEST_39757.ogg',
 'TEST_41834.ogg',
 'TEST_21118.ogg',
 'TEST_36464.ogg',
 'TEST_19487.ogg',
 'TEST_20206.ogg',
 'TEST_38449.ogg',
 'TEST_18799.ogg',
 'TEST_46183.ogg',
 'TEST_30015.ogg',
 'TEST_27569.ogg',
 'TEST_04398.ogg',
 'TEST_33534.ogg',
 'TEST_02931.ogg',
 'TEST_44964.ogg',
 'TEST_24048.ogg',
 'TEST_23727.ogg',
 'TEST_15295.ogg',
 'TEST_22439.ogg',
 'TEST_35145.ogg',
 'TEST_05086.ogg',
 'TEST_25356.ogg',
 'TEST_18969.ogg',
 'TEST_31323.ogg',
 'TEST_21130.ogg',
 'TEST_48186.ogg',
 'TEST_07849.ogg',
 'TEST_26887.ogg',
 'TEST_09864.ogg',
 'TEST_37752.ogg',
 'TEST_17482.ogg',
 'TEST_49298.ogg',
 'TEST_38461.ogg',
 'TEST_27541.ogg',
 'TEST_07691.ogg',
 'TEST_28672.ogg',
 'TEST_16944.ogg',
 'TEST_27227.ogg',
 'TEST_48838.ogg',
 'TEST_28114.ogg',
 'TEST_00698.ogg',
 'TEST_37034.ogg',
 'TEST_38307.ogg',
 'TEST_20548.ogg',
 'TEST_01586.ogg',
 'TEST_30983.ogg',
 'TEST_21656.ogg',
 'TEST_39019.ogg',
 'TEST_11795.ogg',
 'TEST_00840.ogg',
 'TEST_26139.ogg',
 'TEST_46815.ogg',
 'TEST_31445.ogg',
 'TEST_14835.ogg',
 'TEST_25430.ogg',
 'TEST_35623.ogg',
 'TEST_23041.ogg',
 'TEST_05938.ogg',
 'TEST_03391.ogg',
 'TEST_33252.ogg',
 'TEST_13182.ogg',
 'TEST_14821.ogg',
 'TEST_32158.ogg',
 'TEST_12288.ogg',
 'TEST_25424.ogg',
 'TEST_35637.ogg',
 'TEST_23055.ogg',
 'TEST_43979.ogg',
 'TEST_03385.ogg',
 'TEST_34529.ogg',
 'TEST_33246.ogg',
 'TEST_13196.ogg',
 'TEST_27233.ogg',
 'TEST_28100.ogg',
 'TEST_37020.ogg',
 'TEST_11959.ogg',
 'TEST_38313.ogg',
 'TEST_01592.ogg',
 'TEST_21642.ogg',
 'TEST_30997.ogg',
 'TEST_46801.ogg',
 'TEST_00854.ogg',
 'TEST_11781.ogg',
 'TEST_31451.ogg',
 'TEST_31337.ogg',
 'TEST_29578.ogg',
 'TEST_36458.ogg',
 'TEST_16788.ogg',
 'TEST_48192.ogg',
 'TEST_41808.ogg',
 'TEST_21124.ogg',
 'TEST_37746.ogg',
 'TEST_09870.ogg',
 'TEST_26893.ogg',
 'TEST_38475.ogg',
 'TEST_17496.ogg',
 'TEST_27555.ogg',
 'TEST_16950.ogg',
 'TEST_28666.ogg',
 'TEST_07685.ogg',
 'TEST_30029.ogg',
 'TEST_33520.ogg',
 'TEST_44970.ogg',
 'TEST_02925.ogg',
 'TEST_23733.ogg',
 'TEST_15281.ogg',
 'TEST_35151.ogg',
 'TEST_13828.ogg',
 'TEST_05092.ogg',
 'TEST_25342.ogg',
 'TEST_44743.ogg',
 'TEST_02716.ogg',
 'TEST_12505.ogg',
 'TEST_05079.ogg',
 'TEST_23900.ogg',
 'TEST_42332.ogg',
 'TEST_04367.ogg',
 'TEST_03408.ogg',
 'TEST_14174.ogg',
 'TEST_49267.ogg',
 'TEST_26878.ogg',
 'TEST_46154.ogg',
 'TEST_00101.ogg',
 'TEST_39958.ogg',
 'TEST_10312.ogg',
 'TEST_40525.ogg',
 'TEST_06570.ogg',
 'TEST_29593.ogg',
 'TEST_37975.ogg',
 'TEST_18996.ogg',
 'TEST_09643.ogg',
 'TEST_16763.ogg',
 'TEST_39780.ogg',
 'TEST_48179.ogg',
 'TEST_28855.ogg',
 'TEST_19450.ogg',
 'TEST_16005.ogg',
 'TEST_01579.ogg',
 'TEST_19336.ogg',
 'TEST_40243.ogg',
 'TEST_06216.ogg',
 'TEST_09125.ogg',
 'TEST_07108.ogg',
 'TEST_21871.ogg',
 'TEST_10474.ogg',
 'TEST_49501.ogg',
 'TEST_18028.ogg',
 'TEST_46632.ogg',
 'TEST_00667.ogg',
 'TEST_14612.ogg',
 'TEST_43992.ogg',
 'TEST_35804.ogg',
 'TEST_42454.ogg',
 'TEST_04401.ogg',
 'TEST_12263.ogg',
 'TEST_44025.ogg',
 'TEST_24909.ogg',
 'TEST_02070.ogg',
 'TEST_43986.ogg',
 'TEST_14606.ogg',
 'TEST_13169.ogg',
 'TEST_35810.ogg',
 'TEST_04415.ogg',
 'TEST_42440.ogg',
 'TEST_12277.ogg',
 'TEST_02064.ogg',
 'TEST_44031.ogg',
 'TEST_15518.ogg',
 'TEST_30968.ogg',
 'TEST_16011.ogg',
 'TEST_19322.ogg',
 'TEST_47538.ogg',
 'TEST_06202.ogg',
 'TEST_40257.ogg',
 'TEST_09131.ogg',
 'TEST_41149.ogg',
 'TEST_21865.ogg',
 'TEST_10460.ogg',
 'TEST_49515.ogg',
 'TEST_00673.ogg',
 'TEST_46626.ogg',
 'TEST_17469.ogg',
 'TEST_49273.ogg',
 'TEST_00115.ogg',
 'TEST_46140.ogg',
 'TEST_28699.ogg',
 'TEST_08549.ogg',
 'TEST_10306.ogg',
 'TEST_29587.ogg',
 'TEST_06564.ogg',
 'TEST_40531.ogg',
 'TEST_11018.ogg',
 'TEST_09657.ogg',
 'TEST_18982.ogg',
 'TEST_37961.ogg',
 'TEST_28841.ogg',
 'TEST_39794.ogg',
 'TEST_16777.ogg',
 'TEST_19444.ogg',
 'TEST_02702.ogg',
 'TEST_44757.ogg',
 'TEST_12511.ogg',
 'TEST_23914.ogg',
 'TEST_43038.ogg',
 'TEST_04373.ogg',
 'TEST_42326.ogg',
 'TEST_45449.ogg',
 'TEST_32819.ogg',
 'TEST_14160.ogg',
 'TEST_26844.ogg',
 'TEST_18772.ogg',
 'TEST_37791.ogg',
 'TEST_46168.ogg',
 'TEST_17441.ogg',
 'TEST_08561.ogg',
 'TEST_27582.ogg',
 'TEST_07652.ogg',
 'TEST_39964.ogg',
 'TEST_16987.ogg',
 'TEST_41607.ogg',
 'TEST_37949.ogg',
 'TEST_11030.ogg',
 'TEST_40519.ogg',
 'TEST_01223.ogg',
 'TEST_47276.ogg',
 'TEST_48145.ogg',
 'TEST_28869.ogg',
 'TEST_15256.ogg',
 'TEST_35186.ogg',
 'TEST_05045.ogg',
 'TEST_43010.ogg',
 'TEST_12539.ogg',
 'TEST_25395.ogg',
 'TEST_13627.ogg',
 'TEST_14148.ogg',
 'TEST_32831.ogg',
 'TEST_03434.ogg',
 'TEST_45461.ogg',
 'TEST_34298.ogg',
 'TEST_23082.ogg',
 'TEST_03352.ogg',
 'TEST_45307.ogg',
 'TEST_42468.ogg',
 'TEST_33291.ogg',
 'TEST_35838.ogg',
 'TEST_13141.ogg',
 'TEST_05723.ogg',
 'TEST_43776.ogg',
 'TEST_15530.ogg',
 'TEST_44019.ogg',
 'TEST_24935.ogg',
 'TEST_01545.ogg',
 'TEST_47510.ogg',
 'TEST_16039.ogg',
 'TEST_48623.ogg',
 'TEST_30940.ogg',
 'TEST_21695.ogg',
 'TEST_09119.ogg',
 'TEST_11756.ogg',
 'TEST_00883.ogg',
 'TEST_31486.ogg',
 'TEST_10448.ogg',
 'TEST_08207.ogg',
 'TEST_07134.ogg',
 'TEST_30798.ogg',
 'TEST_41161.ogg',
 'TEST_18014.ogg',
 'TEST_17327.ogg',
 'TEST_47504.ogg',
 'TEST_01551.ogg',
 'TEST_21681.ogg',
 'TEST_30954.ogg',
 'TEST_48637.ogg',
 'TEST_00897.ogg',
 'TEST_11742.ogg',
 'TEST_31492.ogg',
 'TEST_08213.ogg',
 'TEST_41175.ogg',
 'TEST_21859.ogg',
 'TEST_07120.ogg',
 'TEST_18000.ogg',
 'TEST_17333.ogg',
 'TEST_49529.ogg',
 'TEST_23096.ogg',
 'TEST_45313.ogg',
 'TEST_03346.ogg',
 'TEST_04429.ogg',
 'TEST_33285.ogg',
 'TEST_13155.ogg',
 'TEST_43762.ogg',
 'TEST_05737.ogg',
 'TEST_15524.ogg',
 'TEST_22388.ogg',
 'TEST_02058.ogg',
 'TEST_24921.ogg',
 'TEST_15242.ogg',
 'TEST_35192.ogg',
 'TEST_23928.ogg',
 'TEST_43004.ogg',
 'TEST_05051.ogg',
 'TEST_25381.ogg',
 'TEST_13633.ogg',
 'TEST_32825.ogg',
 'TEST_45475.ogg',
 'TEST_03420.ogg',
 'TEST_00129.ogg',
 'TEST_37785.ogg',
 'TEST_18766.ogg',
 'TEST_26850.ogg',
 'TEST_17455.ogg',
 'TEST_27596.ogg',
 'TEST_08575.ogg',
 'TEST_41613.ogg',
 'TEST_16993.ogg',
 'TEST_39970.ogg',
 'TEST_07646.ogg',
 'TEST_11024.ogg',
 'TEST_26688.ogg',
 'TEST_06558.ogg',
 'TEST_19478.ogg',
 'TEST_47262.ogg',
 'TEST_01237.ogg',
 'TEST_48151.ogg',
 'TEST_26307.ogg',
 'TEST_40082.ogg',
 'TEST_49918.ogg',
 'TEST_29034.ogg',
 'TEST_36114.ogg',
 'TEST_39227.ogg',
 'TEST_21468.ogg',
 'TEST_20776.ogg',
 'TEST_38139.ogg',
 'TEST_01960.ogg',
 'TEST_27019.ogg',
 'TEST_47935.ogg',
 'TEST_30565.ogg',
 'TEST_42695.ogg',
 'TEST_15915.ogg',
 'TEST_24510.ogg',
 'TEST_34703.ogg',
 'TEST_22161.ogg',
 'TEST_04818.ogg',
 'TEST_32372.ogg',
 'TEST_32414.ogg',
 'TEST_03811.ogg',
 'TEST_45844.ogg',
 'TEST_25168.ogg',
 'TEST_22607.ogg',
 'TEST_44582.ogg',
 'TEST_23519.ogg',
 'TEST_34065.ogg',
 'TEST_24276.ogg',
 'TEST_19849.ogg',
 'TEST_30203.ogg',
 'TEST_46395.ogg',
 'TEST_20010.ogg',
 'TEST_06969.ogg',
 'TEST_08944.ogg',
 'TEST_19691.ogg',
 'TEST_36672.ogg',
 'TEST_39541.ogg',
 'TEST_09482.ogg',
 'TEST_26461.ogg',
 'TEST_29752.ogg',
 'TEST_38887.ogg',
 'TEST_17864.ogg',
 'TEST_08788.ogg',
 'TEST_30217.ogg',
 'TEST_28458.ogg',
 'TEST_46381.ogg',
 'TEST_37578.ogg',
 'TEST_40928.ogg',
 'TEST_20004.ogg',
 'TEST_36666.ogg',
 'TEST_19685.ogg',
 'TEST_08950.ogg',
 'TEST_39555.ogg',
 'TEST_26475.ogg',
 'TEST_09496.ogg',
 'TEST_17870.ogg',
 'TEST_38893.ogg',
 'TEST_29746.ogg',
 'TEST_31109.ogg',
 'TEST_32400.ogg',
 'TEST_45850.ogg',
 'TEST_03805.ogg',
 'TEST_22613.ogg',
 'TEST_44596.ogg',
 'TEST_34071.ogg',
 'TEST_45688.ogg',
 'TEST_12908.ogg',
 'TEST_24262.ogg',
 'TEST_15901.ogg',
 'TEST_33078.ogg',
 'TEST_42681.ogg',
 'TEST_24504.ogg',
 'TEST_34717.ogg',
 'TEST_22175.ogg',
 'TEST_42859.ogg',
 'TEST_35409.ogg',
 'TEST_32366.ogg',
 'TEST_26313.ogg',
 'TEST_29020.ogg',
 'TEST_40096.ogg',
 'TEST_36100.ogg',
 'TEST_10879.ogg',
 'TEST_39233.ogg',
 'TEST_20762.ogg',
 'TEST_47921.ogg',
 'TEST_01974.ogg',
 'TEST_41388.ogg',
 'TEST_30571.ogg',
 'TEST_13380.ogg',
 'TEST_33050.ogg',
 'TEST_15929.ogg',
 'TEST_03193.ogg',
 'TEST_23243.ogg',
 'TEST_35421.ogg',
 'TEST_42871.ogg',
 'TEST_04824.ogg',
 'TEST_25632.ogg',
 'TEST_20992.ogg',
 'TEST_31647.ogg',
 'TEST_49924.ogg',
 'TEST_29008.ogg',
 'TEST_11597.ogg',
 'TEST_21454.ogg',
 'TEST_01784.ogg',
 'TEST_10851.ogg',
 'TEST_36128.ogg',
 'TEST_38105.ogg',
 'TEST_37236.ogg',
 'TEST_28316.ogg',
 'TEST_30559.ogg',
 'TEST_10689.ogg',
 'TEST_27025.ogg',
 'TEST_47909.ogg',
 'TEST_07493.ogg',
 'TEST_28470.ogg',
 'TEST_36896.ogg',
 'TEST_19875.ogg',
 'TEST_27743.ogg',
 'TEST_40900.ogg',
 'TEST_17680.ogg',
 'TEST_38663.ogg',
 'TEST_06955.ogg',
 'TEST_37550.ogg',
 'TEST_48384.ogg',
 'TEST_21332.ogg',
 'TEST_08978.ogg',
 'TEST_31121.ogg',
 'TEST_17858.ogg',
 'TEST_45878.ogg',
 'TEST_25154.ogg',
 'TEST_05284.ogg',
 'TEST_32428.ogg',
 'TEST_35347.ogg',
 'TEST_15097.ogg',
 'TEST_12920.ogg',
 'TEST_34059.ogg',
 'TEST_14389.ogg',
 'TEST_23525.ogg',
 'TEST_33736.ogg',
 'TEST_25140.ogg',
 'TEST_03839.ogg',
 'TEST_05290.ogg',
 'TEST_35353.ogg',
 'TEST_15083.ogg',
 'TEST_12934.ogg',
 'TEST_23531.ogg',
 'TEST_33722.ogg',
 'TEST_28464.ogg',
 'TEST_07487.ogg',
 'TEST_27757.ogg',
 'TEST_19861.ogg',
 'TEST_36882.ogg',
 'TEST_06941.ogg',
 'TEST_38677.ogg',
 'TEST_17694.ogg',
 'TEST_40914.ogg',
 'TEST_20038.ogg',
 'TEST_37544.ogg',
 'TEST_21326.ogg',
 'TEST_48390.ogg',
 'TEST_39569.ogg',
 'TEST_06799.ogg',
 'TEST_31135.ogg',
 'TEST_26449.ogg',
 'TEST_49930.ogg',
 'TEST_31653.ogg',
 'TEST_20986.ogg',
 'TEST_11583.ogg',
 'TEST_21440.ogg',
 'TEST_10845.ogg',
 'TEST_01790.ogg',
 'TEST_38111.ogg',
 'TEST_37222.ogg',
 'TEST_28302.ogg',
 'TEST_27031.ogg',
 'TEST_01948.ogg',
 'TEST_13394.ogg',
 'TEST_24538.ogg',
 'TEST_33044.ogg',
 'TEST_03187.ogg',
 'TEST_23257.ogg',
 'TEST_02299.ogg',
 'TEST_35435.ogg',
 'TEST_04830.ogg',
 'TEST_22149.ogg',
 'TEST_42865.ogg',
 'TEST_25626.ogg',
 'TEST_02272.ogg',
 'TEST_44227.ogg',
 'TEST_43548.ogg',
 'TEST_34918.ogg',
 'TEST_12061.ogg',
 'TEST_04603.ogg',
 'TEST_42656.ogg',
 'TEST_14410.ogg',
 'TEST_45139.ogg',
 'TEST_25815.ogg',
 'TEST_00465.ogg',
 'TEST_46430.ogg',
 'TEST_49703.ogg',
 'TEST_17119.ogg',
 'TEST_31860.ogg',
 'TEST_08039.ogg',
 'TEST_10676.ogg',
 'TEST_11568.ogg',
 'TEST_09327.ogg',
 'TEST_06014.ogg',
 'TEST_40041.ogg',
 'TEST_19134.ogg',
 'TEST_16207.ogg',
 'TEST_27964.ogg',
 'TEST_08987.ogg',
 'TEST_47048.ogg',
 'TEST_19652.ogg',
 'TEST_16561.ogg',
 'TEST_39582.ogg',
 'TEST_09441.ogg',
 'TEST_06772.ogg',
 'TEST_29791.ogg',
 'TEST_38844.ogg',
 'TEST_40727.ogg',
 'TEST_36869.ogg',
 'TEST_10110.ogg',
 'TEST_41439.ogg',
 'TEST_00303.ogg',
 'TEST_46356.ogg',
 'TEST_49065.ogg',
 'TEST_29949.ogg',
 'TEST_14376.ogg',
 'TEST_04165.ogg',
 'TEST_42130.ogg',
 'TEST_13419.ogg',
 'TEST_45887.ogg',
 'TEST_12707.ogg',
 'TEST_15068.ogg',
 'TEST_33911.ogg',
 'TEST_02514.ogg',
 'TEST_44541.ogg',
 'TEST_14362.ogg',
 'TEST_22808.ogg',
 'TEST_42124.ogg',
 'TEST_04171.ogg',
 'TEST_12713.ogg',
 'TEST_45893.ogg',
 'TEST_33905.ogg',
 'TEST_44555.ogg',
 'TEST_02500.ogg',
 'TEST_01009.ogg',
 'TEST_19646.ogg',
 'TEST_08993.ogg',
 'TEST_27970.ogg',
 'TEST_39596.ogg',
 'TEST_16575.ogg',
 'TEST_09455.ogg',
 'TEST_40733.ogg',
 'TEST_38850.ogg',
 'TEST_29785.ogg',
 'TEST_06766.ogg',
 'TEST_10104.ogg',
 'TEST_07478.ogg',
 'TEST_46342.ogg',
 'TEST_18558.ogg',
 'TEST_00317.ogg',
 'TEST_38688.ogg',
 'TEST_49071.ogg',
 'TEST_46424.ogg',
 'TEST_00471.ogg',
 'TEST_31874.ogg',
 'TEST_49717.ogg',
 'TEST_10662.ogg',
 'TEST_09333.ogg',
 'TEST_40055.ogg',
 'TEST_20979.ogg',
 'TEST_06000.ogg',
 'TEST_19120.ogg',
 'TEST_48409.ogg',
 'TEST_16213.ogg',
 'TEST_44233.ogg',
 'TEST_02266.ogg',
 'TEST_05509.ogg',
 'TEST_12075.ogg',
 'TEST_42642.ogg',
 'TEST_04617.ogg',
 'TEST_14404.ogg',
 'TEST_03178.ogg',
 'TEST_25801.ogg',
 'TEST_17125.ogg',
 'TEST_20789.ogg',
 'TEST_00459.ogg',
 'TEST_18216.ogg',
 'TEST_41363.ogg',
 'TEST_07336.ogg',
 'TEST_08005.ogg',
 'TEST_06028.ogg',
 'TEST_20951.ogg',
 'TEST_31684.ogg',
 'TEST_11554.ogg',
 'TEST_21497.ogg',
 'TEST_48421.ogg',
 'TEST_47712.ogg',
 'TEST_19108.ogg',
 'TEST_01747.ogg',
 'TEST_10892.ogg',
 'TEST_15732.ogg',
 'TEST_34924.ogg',
 'TEST_43574.ogg',
 'TEST_05521.ogg',
 'TEST_13343.ogg',
 'TEST_33093.ogg',
 'TEST_45105.ogg',
 'TEST_25829.ogg',
 'TEST_03150.ogg',
 'TEST_23280.ogg',
 'TEST_45663.ogg',
 'TEST_03636.ogg',
 'TEST_13425.ogg',
 'TEST_24289.ogg',
 'TEST_04159.ogg',
 'TEST_22820.ogg',
 'TEST_25197.ogg',
 'TEST_43212.ogg',
 'TEST_05247.ogg',
 'TEST_02528.ogg',
 'TEST_35384.ogg',
 'TEST_15054.ogg',
 'TEST_48347.ogg',
 'TEST_27958.ogg',
 'TEST_47074.ogg',
 'TEST_01021.ogg',
 'TEST_38878.ogg',
 'TEST_11232.ogg',
 'TEST_41405.ogg',
 'TEST_07450.ogg',
 'TEST_36855.ogg',
 'TEST_08763.ogg',
 'TEST_27780.ogg',
 'TEST_49059.ogg',
 'TEST_17643.ogg',
 'TEST_29975.ogg',
 'TEST_06996.ogg',
 'TEST_18570.ogg',
 'TEST_37593.ogg',
 'TEST_48353.ogg',
 'TEST_16549.ogg',
 'TEST_01035.ogg',
 'TEST_36699.ogg',
 'TEST_47060.ogg',
 'TEST_09469.ogg',
 'TEST_11226.ogg',
 'TEST_07444.ogg',
 'TEST_41411.ogg',
 'TEST_10138.ogg',
 'TEST_27794.ogg',
 'TEST_08777.ogg',
 'TEST_36841.ogg',
 'TEST_06982.ogg',
 'TEST_29961.ogg',
 'TEST_17657.ogg',
 'TEST_37587.ogg',
 'TEST_18564.ogg',
 'TEST_03622.ogg',
 'TEST_45677.ogg',
 'TEST_13431.ogg',
 'TEST_22834.ogg',
 'TEST_42118.ogg',
 'TEST_25183.ogg',
 'TEST_05253.ogg',
 'TEST_43206.ogg',
 'TEST_44569.ogg',
 'TEST_35390.ogg',
 'TEST_33939.ogg',
 'TEST_15040.ogg',
 'TEST_15726.ogg',
 'TEST_12049.ogg',
 'TEST_34930.ogg',
 'TEST_05535.ogg',
 'TEST_43560.ogg',
 'TEST_32399.ogg',
 'TEST_13357.ogg',
 'TEST_33087.ogg',
 'TEST_03144.ogg',
 'TEST_45111.ogg',
 'TEST_14438.ogg',
 'TEST_23294.ogg',
 'TEST_31848.ogg',
 'TEST_17131.ogg',
 'TEST_46418.ogg',
 'TEST_18202.ogg',
 'TEST_07322.ogg',
 'TEST_41377.ogg',
 'TEST_08011.ogg',
 'TEST_31690.ogg',
 'TEST_40069.ogg',
 'TEST_20945.ogg',
 'TEST_11540.ogg',
 'TEST_48435.ogg',
 'TEST_21483.ogg',
 'TEST_10886.ogg',
 'TEST_01753.ogg',
 'TEST_47706.ogg',
 'TEST_47841.ogg',
 'TEST_01814.ogg',
 'TEST_30411.ogg',
 'TEST_46587.ogg',
 'TEST_20602.ogg',
 'TEST_36060.ogg',
 'TEST_47699.ogg',
 'TEST_19083.ogg',
 'TEST_10919.ogg',
 'TEST_39353.ogg',
 'TEST_26273.ogg',
 'TEST_09290.ogg',
 'TEST_29140.ogg',
 'TEST_32206.ogg',
 'TEST_22015.ogg',
 'TEST_42939.ogg',
 'TEST_44390.ogg',
 'TEST_35569.ogg',
 'TEST_34677.ogg',
 'TEST_15861.ogg',
 'TEST_33118.ogg',
 'TEST_24464.ogg',
 'TEST_42087.ogg',
 'TEST_24302.ogg',
 'TEST_34111.ogg',
 'TEST_12868.ogg',
 'TEST_22773.ogg',
 'TEST_43399.ogg',
 'TEST_32560.ogg',
 'TEST_45930.ogg',
 'TEST_03965.ogg',
 'TEST_26515.ogg',
 'TEST_17910.ogg',
 'TEST_29626.ogg',
 'TEST_31069.ogg',
 'TEST_40690.ogg',
 'TEST_36706.ogg',
 'TEST_08830.ogg',
 'TEST_39435.ogg',
 'TEST_37418.ogg',
 'TEST_40848.ogg',
 'TEST_20164.ogg',
 'TEST_30377.ogg',
 'TEST_28538.ogg',
 'TEST_26501.ogg',
 'TEST_40684.ogg',
 'TEST_29632.ogg',
 'TEST_17904.ogg',
 'TEST_08824.ogg',
 'TEST_36712.ogg',
 'TEST_39421.ogg',
 'TEST_20170.ogg',
 'TEST_06809.ogg',
 'TEST_19929.ogg',
 'TEST_30363.ogg',
 'TEST_42093.ogg',
 'TEST_24316.ogg',
 'TEST_23479.ogg',
 'TEST_34105.ogg',
 'TEST_22767.ogg',
 'TEST_32574.ogg',
 'TEST_03971.ogg',
 'TEST_45924.ogg',
 'TEST_25008.ogg',
 'TEST_32212.ogg',
 'TEST_22001.ogg',
 'TEST_04978.ogg',
 'TEST_44384.ogg',
 'TEST_34663.ogg',
 'TEST_15875.ogg',
 'TEST_24470.ogg',
 'TEST_01800.ogg',
 'TEST_27179.ogg',
 'TEST_47855.ogg',
 'TEST_30405.ogg',
 'TEST_46593.ogg',
 'TEST_18389.ogg',
 'TEST_20616.ogg',
 'TEST_38059.ogg',
 'TEST_19097.ogg',
 'TEST_36074.ogg',
 'TEST_39347.ogg',
 'TEST_21508.ogg',
 'TEST_09284.ogg',
 'TEST_26267.ogg',
 'TEST_49878.ogg',
 'TEST_29154.ogg',
 'TEST_34893.ogg',
 'TEST_25746.ogg',
 'TEST_05496.ogg',
 'TEST_35555.ogg',
 'TEST_15685.ogg',
 'TEST_04950.ogg',
 'TEST_22029.ogg',
 'TEST_42905.ogg',
 'TEST_23337.ogg',
 'TEST_24458.ogg',
 'TEST_04788.ogg',
 'TEST_33124.ogg',
 'TEST_28262.ogg',
 'TEST_07281.ogg',
 'TEST_27151.ogg',
 'TEST_01828.ogg',
 'TEST_38071.ogg',
 'TEST_49688.ogg',
 'TEST_17092.ogg',
 'TEST_37342.ogg',
 'TEST_21520.ogg',
 'TEST_48596.ogg',
 'TEST_10925.ogg',
 'TEST_49850.ogg',
 'TEST_31733.ogg',
 'TEST_31055.ogg',
 'TEST_11385.ogg',
 'TEST_26529.ogg',
 'TEST_21246.ogg',
 'TEST_39409.ogg',
 'TEST_01196.ogg',
 'TEST_06821.ogg',
 'TEST_38717.ogg',
 'TEST_40874.ogg',
 'TEST_20158.ogg',
 'TEST_00288.ogg',
 'TEST_37424.ogg',
 'TEST_28504.ogg',
 'TEST_27637.ogg',
 'TEST_19901.ogg',
 'TEST_13592.ogg',
 'TEST_22997.ogg',
 'TEST_33642.ogg',
 'TEST_03781.ogg',
 'TEST_12854.ogg',
 'TEST_23451.ogg',
 'TEST_35233.ogg',
 'TEST_25020.ogg',
 'TEST_03959.ogg',
 'TEST_13586.ogg',
 'TEST_33656.ogg',
 'TEST_22983.ogg',
 'TEST_12840.ogg',
 'TEST_03795.ogg',
 'TEST_34139.ogg',
 'TEST_23445.ogg',
 'TEST_35227.ogg',
 'TEST_12698.ogg',
 'TEST_45918.ogg',
 'TEST_25034.ogg',
 'TEST_32548.ogg',
 'TEST_31041.ogg',
 'TEST_17938.ogg',
 'TEST_11391.ogg',
 'TEST_21252.ogg',
 'TEST_01182.ogg',
 'TEST_08818.ogg',
 'TEST_40860.ogg',
 'TEST_38703.ogg',
 'TEST_06835.ogg',
 'TEST_37430.ogg',
 'TEST_28510.ogg',
 'TEST_19915.ogg',
 'TEST_27623.ogg',
 'TEST_07295.ogg',
 'TEST_28276.ogg',
 'TEST_30439.ogg',
 'TEST_27145.ogg',
 'TEST_47869.ogg',
 'TEST_17086.ogg',
 'TEST_38065.ogg',
 'TEST_37356.ogg',
 'TEST_48582.ogg',
 'TEST_16398.ogg',
 'TEST_21534.ogg',
 'TEST_10931.ogg',
 'TEST_36048.ogg',
 'TEST_31727.ogg',
 'TEST_49844.ogg',
 'TEST_29168.ogg',
 'TEST_25752.ogg',
 'TEST_34887.ogg',
 'TEST_05482.ogg',
 'TEST_35541.ogg',
 'TEST_42911.ogg',
 'TEST_04944.ogg',
 'TEST_15691.ogg',
 'TEST_23323.ogg',
 'TEST_33130.ogg',
 'TEST_15849.ogg',
 'TEST_14564.ogg',
 'TEST_03018.ogg',
 'TEST_25961.ogg',
 'TEST_42722.ogg',
 'TEST_04777.ogg',
 'TEST_05469.ogg',
 'TEST_12115.ogg',
 'TEST_44353.ogg',
 'TEST_02306.ogg',
 'TEST_19040.ogg',
 ...]

In [10]:
test_list=natsort.natsorted(os.listdir(test_path))
test_list

['TEST_00000.ogg',
 'TEST_00001.ogg',
 'TEST_00002.ogg',
 'TEST_00003.ogg',
 'TEST_00004.ogg',
 'TEST_00005.ogg',
 'TEST_00006.ogg',
 'TEST_00007.ogg',
 'TEST_00008.ogg',
 'TEST_00009.ogg',
 'TEST_00010.ogg',
 'TEST_00011.ogg',
 'TEST_00012.ogg',
 'TEST_00013.ogg',
 'TEST_00014.ogg',
 'TEST_00015.ogg',
 'TEST_00016.ogg',
 'TEST_00017.ogg',
 'TEST_00018.ogg',
 'TEST_00019.ogg',
 'TEST_00020.ogg',
 'TEST_00021.ogg',
 'TEST_00022.ogg',
 'TEST_00023.ogg',
 'TEST_00024.ogg',
 'TEST_00025.ogg',
 'TEST_00026.ogg',
 'TEST_00027.ogg',
 'TEST_00028.ogg',
 'TEST_00029.ogg',
 'TEST_00030.ogg',
 'TEST_00031.ogg',
 'TEST_00032.ogg',
 'TEST_00033.ogg',
 'TEST_00034.ogg',
 'TEST_00035.ogg',
 'TEST_00036.ogg',
 'TEST_00037.ogg',
 'TEST_00038.ogg',
 'TEST_00039.ogg',
 'TEST_00040.ogg',
 'TEST_00041.ogg',
 'TEST_00042.ogg',
 'TEST_00043.ogg',
 'TEST_00044.ogg',
 'TEST_00045.ogg',
 'TEST_00046.ogg',
 'TEST_00047.ogg',
 'TEST_00048.ogg',
 'TEST_00049.ogg',
 'TEST_00050.ogg',
 'TEST_00051.ogg',
 'TEST_00052.ogg',
 'TEST_00053.ogg',
 'TEST_00054.ogg',
 'TEST_00055.ogg',
 'TEST_00056.ogg',
 'TEST_00057.ogg',
 'TEST_00058.ogg',
 'TEST_00059.ogg',
 'TEST_00060.ogg',
 'TEST_00061.ogg',
 'TEST_00062.ogg',
 'TEST_00063.ogg',
 'TEST_00064.ogg',
 'TEST_00065.ogg',
 'TEST_00066.ogg',
 'TEST_00067.ogg',
 'TEST_00068.ogg',
 'TEST_00069.ogg',
 'TEST_00070.ogg',
 'TEST_00071.ogg',
 'TEST_00072.ogg',
 'TEST_00073.ogg',
 'TEST_00074.ogg',
 'TEST_00075.ogg',
 'TEST_00076.ogg',
 'TEST_00077.ogg',
 'TEST_00078.ogg',
 'TEST_00079.ogg',
 'TEST_00080.ogg',
 'TEST_00081.ogg',
 'TEST_00082.ogg',
 'TEST_00083.ogg',
 'TEST_00084.ogg',
 'TEST_00085.ogg',
 'TEST_00086.ogg',
 'TEST_00087.ogg',
 'TEST_00088.ogg',
 'TEST_00089.ogg',
 'TEST_00090.ogg',
 'TEST_00091.ogg',
 'TEST_00092.ogg',
 'TEST_00093.ogg',
 'TEST_00094.ogg',
 'TEST_00095.ogg',
 'TEST_00096.ogg',
 'TEST_00097.ogg',
 'TEST_00098.ogg',
 'TEST_00099.ogg',
 'TEST_00100.ogg',
 'TEST_00101.ogg',
 'TEST_00102.ogg',
 'TEST_00103.ogg',
 'TEST_00104.ogg',
 'TEST_00105.ogg',
 'TEST_00106.ogg',
 'TEST_00107.ogg',
 'TEST_00108.ogg',
 'TEST_00109.ogg',
 'TEST_00110.ogg',
 'TEST_00111.ogg',
 'TEST_00112.ogg',
 'TEST_00113.ogg',
 'TEST_00114.ogg',
 'TEST_00115.ogg',
 'TEST_00116.ogg',
 'TEST_00117.ogg',
 'TEST_00118.ogg',
 'TEST_00119.ogg',
 'TEST_00120.ogg',
 'TEST_00121.ogg',
 'TEST_00122.ogg',
 'TEST_00123.ogg',
 'TEST_00124.ogg',
 'TEST_00125.ogg',
 'TEST_00126.ogg',
 'TEST_00127.ogg',
 'TEST_00128.ogg',
 'TEST_00129.ogg',
 'TEST_00130.ogg',
 'TEST_00131.ogg',
 'TEST_00132.ogg',
 'TEST_00133.ogg',
 'TEST_00134.ogg',
 'TEST_00135.ogg',
 'TEST_00136.ogg',
 'TEST_00137.ogg',
 'TEST_00138.ogg',
 'TEST_00139.ogg',
 'TEST_00140.ogg',
 'TEST_00141.ogg',
 'TEST_00142.ogg',
 'TEST_00143.ogg',
 'TEST_00144.ogg',
 'TEST_00145.ogg',
 'TEST_00146.ogg',
 'TEST_00147.ogg',
 'TEST_00148.ogg',
 'TEST_00149.ogg',
 'TEST_00150.ogg',
 'TEST_00151.ogg',
 'TEST_00152.ogg',
 'TEST_00153.ogg',
 'TEST_00154.ogg',
 'TEST_00155.ogg',
 'TEST_00156.ogg',
 'TEST_00157.ogg',
 'TEST_00158.ogg',
 'TEST_00159.ogg',
 'TEST_00160.ogg',
 'TEST_00161.ogg',
 'TEST_00162.ogg',
 'TEST_00163.ogg',
 'TEST_00164.ogg',
 'TEST_00165.ogg',
 'TEST_00166.ogg',
 'TEST_00167.ogg',
 'TEST_00168.ogg',
 'TEST_00169.ogg',
 'TEST_00170.ogg',
 'TEST_00171.ogg',
 'TEST_00172.ogg',
 'TEST_00173.ogg',
 'TEST_00174.ogg',
 'TEST_00175.ogg',
 'TEST_00176.ogg',
 'TEST_00177.ogg',
 'TEST_00178.ogg',
 'TEST_00179.ogg',
 'TEST_00180.ogg',
 'TEST_00181.ogg',
 'TEST_00182.ogg',
 'TEST_00183.ogg',
 'TEST_00184.ogg',
 'TEST_00185.ogg',
 'TEST_00186.ogg',
 'TEST_00187.ogg',
 'TEST_00188.ogg',
 'TEST_00189.ogg',
 'TEST_00190.ogg',
 'TEST_00191.ogg',
 'TEST_00192.ogg',
 'TEST_00193.ogg',
 'TEST_00194.ogg',
 'TEST_00195.ogg',
 'TEST_00196.ogg',
 'TEST_00197.ogg',
 'TEST_00198.ogg',
 'TEST_00199.ogg',
 'TEST_00200.ogg',
 'TEST_00201.ogg',
 'TEST_00202.ogg',
 'TEST_00203.ogg',
 'TEST_00204.ogg',
 'TEST_00205.ogg',
 'TEST_00206.ogg',
 'TEST_00207.ogg',
 'TEST_00208.ogg',
 'TEST_00209.ogg',
 'TEST_00210.ogg',
 'TEST_00211.ogg',
 'TEST_00212.ogg',
 'TEST_00213.ogg',
 'TEST_00214.ogg',
 'TEST_00215.ogg',
 'TEST_00216.ogg',
 'TEST_00217.ogg',
 'TEST_00218.ogg',
 'TEST_00219.ogg',
 'TEST_00220.ogg',
 'TEST_00221.ogg',
 'TEST_00222.ogg',
 'TEST_00223.ogg',
 'TEST_00224.ogg',
 'TEST_00225.ogg',
 'TEST_00226.ogg',
 'TEST_00227.ogg',
 'TEST_00228.ogg',
 'TEST_00229.ogg',
 'TEST_00230.ogg',
 'TEST_00231.ogg',
 'TEST_00232.ogg',
 'TEST_00233.ogg',
 'TEST_00234.ogg',
 'TEST_00235.ogg',
 'TEST_00236.ogg',
 'TEST_00237.ogg',
 'TEST_00238.ogg',
 'TEST_00239.ogg',
 'TEST_00240.ogg',
 'TEST_00241.ogg',
 'TEST_00242.ogg',
 'TEST_00243.ogg',
 'TEST_00244.ogg',
 'TEST_00245.ogg',
 'TEST_00246.ogg',
 'TEST_00247.ogg',
 'TEST_00248.ogg',
 'TEST_00249.ogg',
 'TEST_00250.ogg',
 'TEST_00251.ogg',
 'TEST_00252.ogg',
 'TEST_00253.ogg',
 'TEST_00254.ogg',
 'TEST_00255.ogg',
 'TEST_00256.ogg',
 'TEST_00257.ogg',
 'TEST_00258.ogg',
 'TEST_00259.ogg',
 'TEST_00260.ogg',
 'TEST_00261.ogg',
 'TEST_00262.ogg',
 'TEST_00263.ogg',
 'TEST_00264.ogg',
 'TEST_00265.ogg',
 'TEST_00266.ogg',
 'TEST_00267.ogg',
 'TEST_00268.ogg',
 'TEST_00269.ogg',
 'TEST_00270.ogg',
 'TEST_00271.ogg',
 'TEST_00272.ogg',
 'TEST_00273.ogg',
 'TEST_00274.ogg',
 'TEST_00275.ogg',
 'TEST_00276.ogg',
 'TEST_00277.ogg',
 'TEST_00278.ogg',
 'TEST_00279.ogg',
 'TEST_00280.ogg',
 'TEST_00281.ogg',
 'TEST_00282.ogg',
 'TEST_00283.ogg',
 'TEST_00284.ogg',
 'TEST_00285.ogg',
 'TEST_00286.ogg',
 'TEST_00287.ogg',
 'TEST_00288.ogg',
 'TEST_00289.ogg',
 'TEST_00290.ogg',
 'TEST_00291.ogg',
 'TEST_00292.ogg',
 'TEST_00293.ogg',
 'TEST_00294.ogg',
 'TEST_00295.ogg',
 'TEST_00296.ogg',
 'TEST_00297.ogg',
 'TEST_00298.ogg',
 'TEST_00299.ogg',
 'TEST_00300.ogg',
 'TEST_00301.ogg',
 'TEST_00302.ogg',
 'TEST_00303.ogg',
 'TEST_00304.ogg',
 'TEST_00305.ogg',
 'TEST_00306.ogg',
 'TEST_00307.ogg',
 'TEST_00308.ogg',
 'TEST_00309.ogg',
 'TEST_00310.ogg',
 'TEST_00311.ogg',
 'TEST_00312.ogg',
 'TEST_00313.ogg',
 'TEST_00314.ogg',
 'TEST_00315.ogg',
 'TEST_00316.ogg',
 'TEST_00317.ogg',
 'TEST_00318.ogg',
 'TEST_00319.ogg',
 'TEST_00320.ogg',
 'TEST_00321.ogg',
 'TEST_00322.ogg',
 'TEST_00323.ogg',
 'TEST_00324.ogg',
 'TEST_00325.ogg',
 'TEST_00326.ogg',
 'TEST_00327.ogg',
 'TEST_00328.ogg',
 'TEST_00329.ogg',
 'TEST_00330.ogg',
 'TEST_00331.ogg',
 'TEST_00332.ogg',
 'TEST_00333.ogg',
 'TEST_00334.ogg',
 'TEST_00335.ogg',
 'TEST_00336.ogg',
 'TEST_00337.ogg',
 'TEST_00338.ogg',
 'TEST_00339.ogg',
 'TEST_00340.ogg',
 'TEST_00341.ogg',
 'TEST_00342.ogg',
 'TEST_00343.ogg',
 'TEST_00344.ogg',
 'TEST_00345.ogg',
 'TEST_00346.ogg',
 'TEST_00347.ogg',
 'TEST_00348.ogg',
 'TEST_00349.ogg',
 'TEST_00350.ogg',
 'TEST_00351.ogg',
 'TEST_00352.ogg',
 'TEST_00353.ogg',
 'TEST_00354.ogg',
 'TEST_00355.ogg',
 'TEST_00356.ogg',
 'TEST_00357.ogg',
 'TEST_00358.ogg',
 'TEST_00359.ogg',
 'TEST_00360.ogg',
 'TEST_00361.ogg',
 'TEST_00362.ogg',
 'TEST_00363.ogg',
 'TEST_00364.ogg',
 'TEST_00365.ogg',
 'TEST_00366.ogg',
 'TEST_00367.ogg',
 'TEST_00368.ogg',
 'TEST_00369.ogg',
 'TEST_00370.ogg',
 'TEST_00371.ogg',
 'TEST_00372.ogg',
 'TEST_00373.ogg',
 'TEST_00374.ogg',
 'TEST_00375.ogg',
 'TEST_00376.ogg',
 'TEST_00377.ogg',
 'TEST_00378.ogg',
 'TEST_00379.ogg',
 'TEST_00380.ogg',
 'TEST_00381.ogg',
 'TEST_00382.ogg',
 'TEST_00383.ogg',
 'TEST_00384.ogg',
 'TEST_00385.ogg',
 'TEST_00386.ogg',
 'TEST_00387.ogg',
 'TEST_00388.ogg',
 'TEST_00389.ogg',
 'TEST_00390.ogg',
 'TEST_00391.ogg',
 'TEST_00392.ogg',
 'TEST_00393.ogg',
 'TEST_00394.ogg',
 'TEST_00395.ogg',
 'TEST_00396.ogg',
 'TEST_00397.ogg',
 'TEST_00398.ogg',
 'TEST_00399.ogg',
 'TEST_00400.ogg',
 'TEST_00401.ogg',
 'TEST_00402.ogg',
 'TEST_00403.ogg',
 'TEST_00404.ogg',
 'TEST_00405.ogg',
 'TEST_00406.ogg',
 'TEST_00407.ogg',
 'TEST_00408.ogg',
 'TEST_00409.ogg',
 'TEST_00410.ogg',
 'TEST_00411.ogg',
 'TEST_00412.ogg',
 'TEST_00413.ogg',
 'TEST_00414.ogg',
 'TEST_00415.ogg',
 'TEST_00416.ogg',
 'TEST_00417.ogg',
 'TEST_00418.ogg',
 'TEST_00419.ogg',
 'TEST_00420.ogg',
 'TEST_00421.ogg',
 'TEST_00422.ogg',
 'TEST_00423.ogg',
 'TEST_00424.ogg',
 'TEST_00425.ogg',
 'TEST_00426.ogg',
 'TEST_00427.ogg',
 'TEST_00428.ogg',
 'TEST_00429.ogg',
 'TEST_00430.ogg',
 'TEST_00431.ogg',
 'TEST_00432.ogg',
 'TEST_00433.ogg',
 'TEST_00434.ogg',
 'TEST_00435.ogg',
 'TEST_00436.ogg',
 'TEST_00437.ogg',
 'TEST_00438.ogg',
 'TEST_00439.ogg',
 'TEST_00440.ogg',
 'TEST_00441.ogg',
 'TEST_00442.ogg',
 'TEST_00443.ogg',
 'TEST_00444.ogg',
 'TEST_00445.ogg',
 'TEST_00446.ogg',
 'TEST_00447.ogg',
 'TEST_00448.ogg',
 'TEST_00449.ogg',
 'TEST_00450.ogg',
 'TEST_00451.ogg',
 'TEST_00452.ogg',
 'TEST_00453.ogg',
 'TEST_00454.ogg',
 'TEST_00455.ogg',
 'TEST_00456.ogg',
 'TEST_00457.ogg',
 'TEST_00458.ogg',
 'TEST_00459.ogg',
 'TEST_00460.ogg',
 'TEST_00461.ogg',
 'TEST_00462.ogg',
 'TEST_00463.ogg',
 'TEST_00464.ogg',
 'TEST_00465.ogg',
 'TEST_00466.ogg',
 'TEST_00467.ogg',
 'TEST_00468.ogg',
 'TEST_00469.ogg',
 'TEST_00470.ogg',
 'TEST_00471.ogg',
 'TEST_00472.ogg',
 'TEST_00473.ogg',
 'TEST_00474.ogg',
 'TEST_00475.ogg',
 'TEST_00476.ogg',
 'TEST_00477.ogg',
 'TEST_00478.ogg',
 'TEST_00479.ogg',
 'TEST_00480.ogg',
 'TEST_00481.ogg',
 'TEST_00482.ogg',
 'TEST_00483.ogg',
 'TEST_00484.ogg',
 'TEST_00485.ogg',
 'TEST_00486.ogg',
 'TEST_00487.ogg',
 'TEST_00488.ogg',
 'TEST_00489.ogg',
 'TEST_00490.ogg',
 'TEST_00491.ogg',
 'TEST_00492.ogg',
 'TEST_00493.ogg',
 'TEST_00494.ogg',
 'TEST_00495.ogg',
 'TEST_00496.ogg',
 'TEST_00497.ogg',
 'TEST_00498.ogg',
 'TEST_00499.ogg',
 'TEST_00500.ogg',
 'TEST_00501.ogg',
 'TEST_00502.ogg',
 'TEST_00503.ogg',
 'TEST_00504.ogg',
 'TEST_00505.ogg',
 'TEST_00506.ogg',
 'TEST_00507.ogg',
 'TEST_00508.ogg',
 'TEST_00509.ogg',
 'TEST_00510.ogg',
 'TEST_00511.ogg',
 'TEST_00512.ogg',
 'TEST_00513.ogg',
 'TEST_00514.ogg',
 'TEST_00515.ogg',
 'TEST_00516.ogg',
 'TEST_00517.ogg',
 'TEST_00518.ogg',
 'TEST_00519.ogg',
 'TEST_00520.ogg',
 'TEST_00521.ogg',
 'TEST_00522.ogg',
 'TEST_00523.ogg',
 'TEST_00524.ogg',
 'TEST_00525.ogg',
 'TEST_00526.ogg',
 'TEST_00527.ogg',
 'TEST_00528.ogg',
 'TEST_00529.ogg',
 'TEST_00530.ogg',
 'TEST_00531.ogg',
 'TEST_00532.ogg',
 'TEST_00533.ogg',
 'TEST_00534.ogg',
 'TEST_00535.ogg',
 'TEST_00536.ogg',
 'TEST_00537.ogg',
 'TEST_00538.ogg',
 'TEST_00539.ogg',
 'TEST_00540.ogg',
 'TEST_00541.ogg',
 'TEST_00542.ogg',
 'TEST_00543.ogg',
 'TEST_00544.ogg',
 'TEST_00545.ogg',
 'TEST_00546.ogg',
 'TEST_00547.ogg',
 'TEST_00548.ogg',
 'TEST_00549.ogg',
 'TEST_00550.ogg',
 'TEST_00551.ogg',
 'TEST_00552.ogg',
 'TEST_00553.ogg',
 'TEST_00554.ogg',
 'TEST_00555.ogg',
 'TEST_00556.ogg',
 'TEST_00557.ogg',
 'TEST_00558.ogg',
 'TEST_00559.ogg',
 'TEST_00560.ogg',
 'TEST_00561.ogg',
 'TEST_00562.ogg',
 'TEST_00563.ogg',
 'TEST_00564.ogg',
 'TEST_00565.ogg',
 'TEST_00566.ogg',
 'TEST_00567.ogg',
 'TEST_00568.ogg',
 'TEST_00569.ogg',
 'TEST_00570.ogg',
 'TEST_00571.ogg',
 'TEST_00572.ogg',
 'TEST_00573.ogg',
 'TEST_00574.ogg',
 'TEST_00575.ogg',
 'TEST_00576.ogg',
 'TEST_00577.ogg',
 'TEST_00578.ogg',
 'TEST_00579.ogg',
 'TEST_00580.ogg',
 'TEST_00581.ogg',
 'TEST_00582.ogg',
 'TEST_00583.ogg',
 'TEST_00584.ogg',
 'TEST_00585.ogg',
 'TEST_00586.ogg',
 'TEST_00587.ogg',
 'TEST_00588.ogg',
 'TEST_00589.ogg',
 'TEST_00590.ogg',
 'TEST_00591.ogg',
 'TEST_00592.ogg',
 'TEST_00593.ogg',
 'TEST_00594.ogg',
 'TEST_00595.ogg',
 'TEST_00596.ogg',
 'TEST_00597.ogg',
 'TEST_00598.ogg',
 'TEST_00599.ogg',
 'TEST_00600.ogg',
 'TEST_00601.ogg',
 'TEST_00602.ogg',
 'TEST_00603.ogg',
 'TEST_00604.ogg',
 'TEST_00605.ogg',
 'TEST_00606.ogg',
 'TEST_00607.ogg',
 'TEST_00608.ogg',
 'TEST_00609.ogg',
 'TEST_00610.ogg',
 'TEST_00611.ogg',
 'TEST_00612.ogg',
 'TEST_00613.ogg',
 'TEST_00614.ogg',
 'TEST_00615.ogg',
 'TEST_00616.ogg',
 'TEST_00617.ogg',
 'TEST_00618.ogg',
 'TEST_00619.ogg',
 'TEST_00620.ogg',
 'TEST_00621.ogg',
 'TEST_00622.ogg',
 'TEST_00623.ogg',
 'TEST_00624.ogg',
 'TEST_00625.ogg',
 'TEST_00626.ogg',
 'TEST_00627.ogg',
 'TEST_00628.ogg',
 'TEST_00629.ogg',
 'TEST_00630.ogg',
 'TEST_00631.ogg',
 'TEST_00632.ogg',
 'TEST_00633.ogg',
 'TEST_00634.ogg',
 'TEST_00635.ogg',
 'TEST_00636.ogg',
 'TEST_00637.ogg',
 'TEST_00638.ogg',
 'TEST_00639.ogg',
 'TEST_00640.ogg',
 'TEST_00641.ogg',
 'TEST_00642.ogg',
 'TEST_00643.ogg',
 'TEST_00644.ogg',
 'TEST_00645.ogg',
 'TEST_00646.ogg',
 'TEST_00647.ogg',
 'TEST_00648.ogg',
 'TEST_00649.ogg',
 'TEST_00650.ogg',
 'TEST_00651.ogg',
 'TEST_00652.ogg',
 'TEST_00653.ogg',
 'TEST_00654.ogg',
 'TEST_00655.ogg',
 'TEST_00656.ogg',
 'TEST_00657.ogg',
 'TEST_00658.ogg',
 'TEST_00659.ogg',
 'TEST_00660.ogg',
 'TEST_00661.ogg',
 'TEST_00662.ogg',
 'TEST_00663.ogg',
 'TEST_00664.ogg',
 'TEST_00665.ogg',
 'TEST_00666.ogg',
 'TEST_00667.ogg',
 'TEST_00668.ogg',
 'TEST_00669.ogg',
 'TEST_00670.ogg',
 'TEST_00671.ogg',
 'TEST_00672.ogg',
 'TEST_00673.ogg',
 'TEST_00674.ogg',
 'TEST_00675.ogg',
 'TEST_00676.ogg',
 'TEST_00677.ogg',
 'TEST_00678.ogg',
 'TEST_00679.ogg',
 'TEST_00680.ogg',
 'TEST_00681.ogg',
 'TEST_00682.ogg',
 'TEST_00683.ogg',
 'TEST_00684.ogg',
 'TEST_00685.ogg',
 'TEST_00686.ogg',
 'TEST_00687.ogg',
 'TEST_00688.ogg',
 'TEST_00689.ogg',
 'TEST_00690.ogg',
 'TEST_00691.ogg',
 'TEST_00692.ogg',
 'TEST_00693.ogg',
 'TEST_00694.ogg',
 'TEST_00695.ogg',
 'TEST_00696.ogg',
 'TEST_00697.ogg',
 'TEST_00698.ogg',
 'TEST_00699.ogg',
 'TEST_00700.ogg',
 'TEST_00701.ogg',
 'TEST_00702.ogg',
 'TEST_00703.ogg',
 'TEST_00704.ogg',
 'TEST_00705.ogg',
 'TEST_00706.ogg',
 'TEST_00707.ogg',
 'TEST_00708.ogg',
 'TEST_00709.ogg',
 'TEST_00710.ogg',
 'TEST_00711.ogg',
 'TEST_00712.ogg',
 'TEST_00713.ogg',
 'TEST_00714.ogg',
 'TEST_00715.ogg',
 'TEST_00716.ogg',
 'TEST_00717.ogg',
 'TEST_00718.ogg',
 'TEST_00719.ogg',
 'TEST_00720.ogg',
 'TEST_00721.ogg',
 'TEST_00722.ogg',
 'TEST_00723.ogg',
 'TEST_00724.ogg',
 'TEST_00725.ogg',
 'TEST_00726.ogg',
 'TEST_00727.ogg',
 'TEST_00728.ogg',
 'TEST_00729.ogg',
 'TEST_00730.ogg',
 'TEST_00731.ogg',
 'TEST_00732.ogg',
 'TEST_00733.ogg',
 'TEST_00734.ogg',
 'TEST_00735.ogg',
 'TEST_00736.ogg',
 'TEST_00737.ogg',
 'TEST_00738.ogg',
 'TEST_00739.ogg',
 'TEST_00740.ogg',
 'TEST_00741.ogg',
 'TEST_00742.ogg',
 'TEST_00743.ogg',
 'TEST_00744.ogg',
 'TEST_00745.ogg',
 'TEST_00746.ogg',
 'TEST_00747.ogg',
 'TEST_00748.ogg',
 'TEST_00749.ogg',
 'TEST_00750.ogg',
 'TEST_00751.ogg',
 'TEST_00752.ogg',
 'TEST_00753.ogg',
 'TEST_00754.ogg',
 'TEST_00755.ogg',
 'TEST_00756.ogg',
 'TEST_00757.ogg',
 'TEST_00758.ogg',
 'TEST_00759.ogg',
 'TEST_00760.ogg',
 'TEST_00761.ogg',
 'TEST_00762.ogg',
 'TEST_00763.ogg',
 'TEST_00764.ogg',
 'TEST_00765.ogg',
 'TEST_00766.ogg',
 'TEST_00767.ogg',
 'TEST_00768.ogg',
 'TEST_00769.ogg',
 'TEST_00770.ogg',
 'TEST_00771.ogg',
 'TEST_00772.ogg',
 'TEST_00773.ogg',
 'TEST_00774.ogg',
 'TEST_00775.ogg',
 'TEST_00776.ogg',
 'TEST_00777.ogg',
 'TEST_00778.ogg',
 'TEST_00779.ogg',
 'TEST_00780.ogg',
 'TEST_00781.ogg',
 'TEST_00782.ogg',
 'TEST_00783.ogg',
 'TEST_00784.ogg',
 'TEST_00785.ogg',
 'TEST_00786.ogg',
 'TEST_00787.ogg',
 'TEST_00788.ogg',
 'TEST_00789.ogg',
 'TEST_00790.ogg',
 'TEST_00791.ogg',
 'TEST_00792.ogg',
 'TEST_00793.ogg',
 'TEST_00794.ogg',
 'TEST_00795.ogg',
 'TEST_00796.ogg',
 'TEST_00797.ogg',
 'TEST_00798.ogg',
 'TEST_00799.ogg',
 'TEST_00800.ogg',
 'TEST_00801.ogg',
 'TEST_00802.ogg',
 'TEST_00803.ogg',
 'TEST_00804.ogg',
 'TEST_00805.ogg',
 'TEST_00806.ogg',
 'TEST_00807.ogg',
 'TEST_00808.ogg',
 'TEST_00809.ogg',
 'TEST_00810.ogg',
 'TEST_00811.ogg',
 'TEST_00812.ogg',
 'TEST_00813.ogg',
 'TEST_00814.ogg',
 'TEST_00815.ogg',
 'TEST_00816.ogg',
 'TEST_00817.ogg',
 'TEST_00818.ogg',
 'TEST_00819.ogg',
 'TEST_00820.ogg',
 'TEST_00821.ogg',
 'TEST_00822.ogg',
 'TEST_00823.ogg',
 'TEST_00824.ogg',
 'TEST_00825.ogg',
 'TEST_00826.ogg',
 'TEST_00827.ogg',
 'TEST_00828.ogg',
 'TEST_00829.ogg',
 'TEST_00830.ogg',
 'TEST_00831.ogg',
 'TEST_00832.ogg',
 'TEST_00833.ogg',
 'TEST_00834.ogg',
 'TEST_00835.ogg',
 'TEST_00836.ogg',
 'TEST_00837.ogg',
 'TEST_00838.ogg',
 'TEST_00839.ogg',
 'TEST_00840.ogg',
 'TEST_00841.ogg',
 'TEST_00842.ogg',
 'TEST_00843.ogg',
 'TEST_00844.ogg',
 'TEST_00845.ogg',
 'TEST_00846.ogg',
 'TEST_00847.ogg',
 'TEST_00848.ogg',
 'TEST_00849.ogg',
 'TEST_00850.ogg',
 'TEST_00851.ogg',
 'TEST_00852.ogg',
 'TEST_00853.ogg',
 'TEST_00854.ogg',
 'TEST_00855.ogg',
 'TEST_00856.ogg',
 'TEST_00857.ogg',
 'TEST_00858.ogg',
 'TEST_00859.ogg',
 'TEST_00860.ogg',
 'TEST_00861.ogg',
 'TEST_00862.ogg',
 'TEST_00863.ogg',
 'TEST_00864.ogg',
 'TEST_00865.ogg',
 'TEST_00866.ogg',
 'TEST_00867.ogg',
 'TEST_00868.ogg',
 'TEST_00869.ogg',
 'TEST_00870.ogg',
 'TEST_00871.ogg',
 'TEST_00872.ogg',
 'TEST_00873.ogg',
 'TEST_00874.ogg',
 'TEST_00875.ogg',
 'TEST_00876.ogg',
 'TEST_00877.ogg',
 'TEST_00878.ogg',
 'TEST_00879.ogg',
 'TEST_00880.ogg',
 'TEST_00881.ogg',
 'TEST_00882.ogg',
 'TEST_00883.ogg',
 'TEST_00884.ogg',
 'TEST_00885.ogg',
 'TEST_00886.ogg',
 'TEST_00887.ogg',
 'TEST_00888.ogg',
 'TEST_00889.ogg',
 'TEST_00890.ogg',
 'TEST_00891.ogg',
 'TEST_00892.ogg',
 'TEST_00893.ogg',
 'TEST_00894.ogg',
 'TEST_00895.ogg',
 'TEST_00896.ogg',
 'TEST_00897.ogg',
 'TEST_00898.ogg',
 'TEST_00899.ogg',
 'TEST_00900.ogg',
 'TEST_00901.ogg',
 'TEST_00902.ogg',
 'TEST_00903.ogg',
 'TEST_00904.ogg',
 'TEST_00905.ogg',
 'TEST_00906.ogg',
 'TEST_00907.ogg',
 'TEST_00908.ogg',
 'TEST_00909.ogg',
 'TEST_00910.ogg',
 'TEST_00911.ogg',
 'TEST_00912.ogg',
 'TEST_00913.ogg',
 'TEST_00914.ogg',
 'TEST_00915.ogg',
 'TEST_00916.ogg',
 'TEST_00917.ogg',
 'TEST_00918.ogg',
 'TEST_00919.ogg',
 'TEST_00920.ogg',
 'TEST_00921.ogg',
 'TEST_00922.ogg',
 'TEST_00923.ogg',
 'TEST_00924.ogg',
 'TEST_00925.ogg',
 'TEST_00926.ogg',
 'TEST_00927.ogg',
 'TEST_00928.ogg',
 'TEST_00929.ogg',
 'TEST_00930.ogg',
 'TEST_00931.ogg',
 'TEST_00932.ogg',
 'TEST_00933.ogg',
 'TEST_00934.ogg',
 'TEST_00935.ogg',
 'TEST_00936.ogg',
 'TEST_00937.ogg',
 'TEST_00938.ogg',
 'TEST_00939.ogg',
 'TEST_00940.ogg',
 'TEST_00941.ogg',
 'TEST_00942.ogg',
 'TEST_00943.ogg',
 'TEST_00944.ogg',
 'TEST_00945.ogg',
 'TEST_00946.ogg',
 'TEST_00947.ogg',
 'TEST_00948.ogg',
 'TEST_00949.ogg',
 'TEST_00950.ogg',
 'TEST_00951.ogg',
 'TEST_00952.ogg',
 'TEST_00953.ogg',
 'TEST_00954.ogg',
 'TEST_00955.ogg',
 'TEST_00956.ogg',
 'TEST_00957.ogg',
 'TEST_00958.ogg',
 'TEST_00959.ogg',
 'TEST_00960.ogg',
 'TEST_00961.ogg',
 'TEST_00962.ogg',
 'TEST_00963.ogg',
 'TEST_00964.ogg',
 'TEST_00965.ogg',
 'TEST_00966.ogg',
 'TEST_00967.ogg',
 'TEST_00968.ogg',
 'TEST_00969.ogg',
 'TEST_00970.ogg',
 'TEST_00971.ogg',
 'TEST_00972.ogg',
 'TEST_00973.ogg',
 'TEST_00974.ogg',
 'TEST_00975.ogg',
 'TEST_00976.ogg',
 'TEST_00977.ogg',
 'TEST_00978.ogg',
 'TEST_00979.ogg',
 'TEST_00980.ogg',
 'TEST_00981.ogg',
 'TEST_00982.ogg',
 'TEST_00983.ogg',
 'TEST_00984.ogg',
 'TEST_00985.ogg',
 'TEST_00986.ogg',
 'TEST_00987.ogg',
 'TEST_00988.ogg',
 'TEST_00989.ogg',
 'TEST_00990.ogg',
 'TEST_00991.ogg',
 'TEST_00992.ogg',
 'TEST_00993.ogg',
 'TEST_00994.ogg',
 'TEST_00995.ogg',
 'TEST_00996.ogg',
 'TEST_00997.ogg',
 'TEST_00998.ogg',
 'TEST_00999.ogg',
 ...]

In [11]:
len(test_list)

50000

In [12]:
# 데이터 증강 함수
import random
def augment_audio(y):
    # 시간 축소
    if random.random() < 0.5:
        y = librosa.effects.time_stretch(y, rate=random.uniform(0.8, 1.2))
    # 피치 변경
    if random.random() < 0.5:
        y = librosa.effects.pitch_shift(y, sr=sample_rate, n_steps=random.randint(-3, 3))
    return y

In [13]:
# Constants
duration = 2  # seconds
sample_rate = 32000  # Hz
n_mels = 128
n_mfcc = 40

In [14]:
# Initialize lists for features and labels
test_feature = []

for i in range(len(test_list)):
    x, _ = librosa.load(test_path + test_list[i], sr=sample_rate, duration=duration)
    
    # 데이터 증강
    x = augment_audio(x)
    
    # 노이즈 감소
    x = librosa.effects.preemphasis(x)
    
    # Extract log-mel spectrogram
    S = librosa.feature.melspectrogram(y=x, sr=sample_rate, n_mels=n_mels)
    log_S = librosa.power_to_db(S, ref=np.max)
    
    # Extract MFCC
    mfcc = librosa.feature.mfcc(S=log_S, n_mfcc=n_mfcc)
    
    # Compute delta and delta-delta MFCC
    width = min(7, mfcc.shape[1]) if mfcc.shape[1] >= 3 else 3
    delta_mfcc = librosa.feature.delta(mfcc, width=width)
    delta2_mfcc = librosa.feature.delta(mfcc, order=2, width=width)
    
    # Extract spectral contrast
    spectral_contrast = librosa.feature.spectral_contrast(S=log_S, sr=sample_rate)
    
    # Concatenate features along the MFCC axis
    combined_features = np.concatenate((mfcc, delta_mfcc, delta2_mfcc, spectral_contrast), axis=0)
    
    # Normalize the combined features
    scaler = StandardScaler()
    normalized_features = scaler.fit_transform(combined_features)
    
    # Append to the feature list
    test_feature.append(normalized_features.flatten())

In [ ]:
train_feature_df = pd.DataFrame(test_feature)
train_feature_df

In [ ]:
test_x=train_feature_df[:,0:1016]

In [ ]:
test_x.to_csv("test data 0713.csv")

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

test_x=pd.DataFrame(scaler.fit_transform(test_x))
test_x

In [ ]:
import tensorflow as tf
import numpy as np 

X_test = test_x.astype(np.float32)

In [ ]:
import tensorflow as tf

x_test = tf.reshape(X_test,(X_test.shape[0],X_test.shape[1],1))

In [ ]:
pred = model.predict(x_test)