In [26]:
import os

train_path='/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/train/'
test_path='/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/test'
train_list=os.listdir(train_path)
test_list=os.listdir(test_path)

In [27]:
import pandas as pd  

train=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/train.csv")

In [28]:
train=train.sort_values(['id','path','label'])
train

             id                  path label
39661  AAACWKPZ  ./train/AAACWKPZ.ogg  fake
39539  AAAQOZYI  ./train/AAAQOZYI.ogg  fake
655    AAAWBXQE  ./train/AAAWBXQE.ogg  real
29647  AABHDRLX  ./train/AABHDRLX.ogg  real
16890  AABXXHMU  ./train/AABXXHMU.ogg  real
...         ...                   ...   ...
19183  ZZZMJSBX  ./train/ZZZMJSBX.ogg  fake
20744  ZZZRTSKN  ./train/ZZZRTSKN.ogg  fake
25482  ZZZSAANM  ./train/ZZZSAANM.ogg  real
22209  ZZZSYEYS  ./train/ZZZSYEYS.ogg  fake
1125   ZZZTCIWY  ./train/ZZZTCIWY.ogg  fake

[55438 rows x 3 columns]

In [29]:
import natsort
train_list=natsort.natsorted(train_list)

In [30]:
train['label'].isnull().sum()

0

In [31]:
train_list

['AAACWKPZ.ogg',
 'AAAQOZYI.ogg',
 'AAAWBXQE.ogg',
 'AABHDRLX.ogg',
 'AABXXHMU.ogg',
 'AACAYDKC.ogg',
 'AACBAWMZ.ogg',
 'AACEAXVU.ogg',
 'AACHVERO.ogg',
 'AACYAWEH.ogg',
 'AADDNUMU.ogg',
 'AADKWHEE.ogg',
 'AADPDAER.ogg',
 'AADQUEFI.ogg',
 'AAECEROJ.ogg',
 'AAEYTHSY.ogg',
 'AAFFVAWD.ogg',
 'AAFNYPXE.ogg',
 'AAGDMPXZ.ogg',
 'AAGIITHH.ogg',
 'AAGXILIN.ogg',
 'AAGZDQDL.ogg',
 'AAHKQWBB.ogg',
 'AAIGXLUD.ogg',
 'AAIINGWH.ogg',
 'AAIKZLBQ.ogg',
 'AAIXOVVV.ogg',
 'AAIYWHUF.ogg',
 'AAJEQLVT.ogg',
 'AAJKXPIW.ogg',
 'AAJMPRLS.ogg',
 'AAJSFGQB.ogg',
 'AAKKEAOL.ogg',
 'AAKXVWXI.ogg',
 'AALITDLH.ogg',
 'AALMMBOZ.ogg',
 'AALVLTSV.ogg',
 'AAMMREFE.ogg',
 'AANJJHYA.ogg',
 'AANOXTME.ogg',
 'AANUFJBH.ogg',
 'AAOEAZJW.ogg',
 'AAOFKKOG.ogg',
 'AAOYUWCN.ogg',
 'AAPELQFY.ogg',
 'AAPGWSKV.ogg',
 'AAPWJSUB.ogg',
 'AAQBLCRK.ogg',
 'AAQBNHMD.ogg',
 'AAQBQXCT.ogg',
 'AAQFLJFN.ogg',
 'AAQJRBNN.ogg',
 'AAQNTEKV.ogg',
 'AAQQXFSY.ogg',
 'AARBSIOH.ogg',
 'AARGVJZI.ogg',
 'AARGWRKZ.ogg',
 'AARRJAAQ.ogg',
 'AASWUMSW.ogg',
 'AATCFCVI.ogg',
 'AATLVEWK.ogg',
 'AATQICFM.ogg',
 'AATTJCGE.ogg',
 'AATTWSHA.ogg',
 'AAUAYKVM.ogg',
 'AAUEYCPM.ogg',
 'AAUSMRIH.ogg',
 'AAUTECVW.ogg',
 'AAWRAXMA.ogg',
 'AAWWBNIZ.ogg',
 'AAWWHHJX.ogg',
 'AAWZUHOB.ogg',
 'AAXQREUD.ogg',
 'AAXSBNDD.ogg',
 'AAXYCDPY.ogg',
 'AAYKMDBZ.ogg',
 'AAYPWYKF.ogg',
 'AAYTHXYW.ogg',
 'AAYYBEHJ.ogg',
 'AAZJOTGS.ogg',
 'AAZTWMFP.ogg',
 'AAZYAGMM.ogg',
 'ABAENKHV.ogg',
 'ABAFLSLF.ogg',
 'ABBIUGTR.ogg',
 'ABBZBMWL.ogg',
 'ABCPBMFW.ogg',
 'ABCVBHOB.ogg',
 'ABDOJNBI.ogg',
 'ABEFAEHN.ogg',
 'ABEMMSDM.ogg',
 'ABEOIKVE.ogg',
 'ABFGDXNL.ogg',
 'ABFJWPVZ.ogg',
 'ABFLRFQS.ogg',
 'ABFLVQJN.ogg',
 'ABFQLXGA.ogg',
 'ABGTOQQP.ogg',
 'ABHCEUXO.ogg',
 'ABHKMALR.ogg',
 'ABHPHEQR.ogg',
 'ABICOCXR.ogg',
 'ABJOLJDE.ogg',
 'ABKCBVEX.ogg',
 'ABKEQPLS.ogg',
 'ABKFHZQH.ogg',
 'ABKGIXCK.ogg',
 'ABKUMPGG.ogg',
 'ABKXHBIM.ogg',
 'ABLARKBT.ogg',
 'ABLIHAZW.ogg',
 'ABLNKKUX.ogg',
 'ABLWKUWO.ogg',
 'ABMDYAQT.ogg',
 'ABMPTGUJ.ogg',
 'ABMTFRFR.ogg',
 'ABNJDLFT.ogg',
 'ABNPAPHJ.ogg',
 'ABNSMWQL.ogg',
 'ABNYBNQV.ogg',
 'ABOAJFJU.ogg',
 'ABODBMGT.ogg',
 'ABOGAUEA.ogg',
 'ABOHAMXE.ogg',
 'ABOQWAGI.ogg',
 'ABOUKFBY.ogg',
 'ABOZOOGW.ogg',
 'ABPBTZOA.ogg',
 'ABPERQHZ.ogg',
 'ABPFZVZA.ogg',
 'ABPNIJHE.ogg',
 'ABPPUMMV.ogg',
 'ABPQJSIJ.ogg',
 'ABQFMETL.ogg',
 'ABRQWDWI.ogg',
 'ABRXILJS.ogg',
 'ABSHFXDX.ogg',
 'ABSNZUNO.ogg',
 'ABSPZPGI.ogg',
 'ABSWVZJA.ogg',
 'ABSXQNYR.ogg',
 'ABTLKJXD.ogg',
 'ABTNXFZS.ogg',
 'ABTPCQFA.ogg',
 'ABUHXIXM.ogg',
 'ABUNGWUU.ogg',
 'ABUQBWXC.ogg',
 'ABUUKHXR.ogg',
 'ABVBMDVV.ogg',
 'ABVBWXRP.ogg',
 'ABVGOCCV.ogg',
 'ABVGQMUB.ogg',
 'ABVWWSBB.ogg',
 'ABWCFFHK.ogg',
 'ABWUXCMN.ogg',
 'ABXJPTKW.ogg',
 'ABYCORVQ.ogg',
 'ABYKGYGO.ogg',
 'ABYNSDDG.ogg',
 'ABYOZVEE.ogg',
 'ABYRDEYH.ogg',
 'ABYWCRPI.ogg',
 'ABYZABZD.ogg',
 'ABYZNHTZ.ogg',
 'ABZCSMEE.ogg',
 'ABZRXUIA.ogg',
 'ACADZSLP.ogg',
 'ACAQLVEP.ogg',
 'ACAXJQVH.ogg',
 'ACCFXCMA.ogg',
 'ACCIDWEB.ogg',
 'ACCIREEY.ogg',
 'ACCJJVII.ogg',
 'ACCRYQFF.ogg',
 'ACCVDILY.ogg',
 'ACDLJRDR.ogg',
 'ACDRCJLG.ogg',
 'ACDYPDEM.ogg',
 'ACERXOAR.ogg',
 'ACEVNLTT.ogg',
 'ACEZIJAB.ogg',
 'ACFGHOWF.ogg',
 'ACFQUFYO.ogg',
 'ACFWDRVT.ogg',
 'ACGFRPRI.ogg',
 'ACGUAHMM.ogg',
 'ACHJDZOZ.ogg',
 'ACHMYSZY.ogg',
 'ACHORSDD.ogg',
 'ACHRSWBA.ogg',
 'ACHVQDUS.ogg',
 'ACIFENNO.ogg',
 'ACIHPMPW.ogg',
 'ACILIPFX.ogg',
 'ACIWOKDJ.ogg',
 'ACJUMQTR.ogg',
 'ACKCEXWX.ogg',
 'ACKSBUPD.ogg',
 'ACLGRMWV.ogg',
 'ACLJSORS.ogg',
 'ACLQGXBK.ogg',
 'ACMIDJBL.ogg',
 'ACMMKTIX.ogg',
 'ACMVOVPG.ogg',
 'ACMVWCLI.ogg',
 'ACMWONON.ogg',
 'ACNMORJU.ogg',
 'ACOCDNKO.ogg',
 'ACOGLDLN.ogg',
 'ACOHIIDN.ogg',
 'ACOYEPCS.ogg',
 'ACPGWVHU.ogg',
 'ACPNWAZP.ogg',
 'ACPPUGMA.ogg',
 'ACQBNMSF.ogg',
 'ACQYANTU.ogg',
 'ACRFDLZL.ogg',
 'ACRLASKU.ogg',
 'ACRLDUAX.ogg',
 'ACRXBUQB.ogg',
 'ACSANEKN.ogg',
 'ACSBLOUY.ogg',
 'ACSCYAQJ.ogg',
 'ACSTVSFE.ogg',
 'ACTDYAIM.ogg',
 'ACTOJCHP.ogg',
 'ACTVDSPZ.ogg',
 'ACUUCPDE.ogg',
 'ACVBIICI.ogg',
 'ACVLQWUT.ogg',
 'ACWBHUHH.ogg',
 'ACWCEZKR.ogg',
 'ACWJDIYF.ogg',
 'ACWJFMDA.ogg',
 'ACWPMQUS.ogg',
 'ACXQVBZU.ogg',
 'ACXSNPAG.ogg',
 'ACYDVUSW.ogg',
 'ACYDXMGH.ogg',
 'ACYNKSXM.ogg',
 'ACYPSUDL.ogg',
 'ACYWILHM.ogg',
 'ACZDWFJU.ogg',
 'ACZHJEMZ.ogg',
 'ACZQHZVX.ogg',
 'ACZYGLME.ogg',
 'ADBJJUZZ.ogg',
 'ADBMDAGD.ogg',
 'ADCHBQBA.ogg',
 'ADCIPVAL.ogg',
 'ADCOOLKZ.ogg',
 'ADCPMILG.ogg',
 'ADCVPSTQ.ogg',
 'ADDBUOGS.ogg',
 'ADDGDTIE.ogg',
 'ADDVJJOY.ogg',
 'ADECASSY.ogg',
 'ADEJFHOY.ogg',
 'ADESWDSC.ogg',
 'ADEVHVOE.ogg',
 'ADFBFFAQ.ogg',
 'ADFGBALZ.ogg',
 'ADFSOSBE.ogg',
 'ADFWZJRH.ogg',
 'ADGBKOGD.ogg',
 'ADGOEVLE.ogg',
 'ADGQHEZF.ogg',
 'ADGYLZAM.ogg',
 'ADHFLHEJ.ogg',
 'ADHFTIVB.ogg',
 'ADHJIKDG.ogg',
 'ADHRVVOP.ogg',
 'ADHSMHLP.ogg',
 'ADHWFMHZ.ogg',
 'ADIEYDPE.ogg',
 'ADITNUUO.ogg',
 'ADIVLXIX.ogg',
 'ADJDIWTE.ogg',
 'ADJGZNRP.ogg',
 'ADJKHDIW.ogg',
 'ADJPBUAD.ogg',
 'ADKBXRUV.ogg',
 'ADKELMJC.ogg',
 'ADKFQOID.ogg',
 'ADKHDYQV.ogg',
 'ADKRPWYK.ogg',
 'ADLACGUG.ogg',
 'ADLDAJMK.ogg',
 'ADLKVZEI.ogg',
 'ADLMZFOF.ogg',
 'ADLNYCMI.ogg',
 'ADLQFSRE.ogg',
 'ADMEGPRK.ogg',
 'ADMFGENI.ogg',
 'ADMQLVFV.ogg',
 'ADNGIXGH.ogg',
 'ADNISKIT.ogg',
 'ADNKTIJQ.ogg',
 'ADNMWDJP.ogg',
 'ADNNCBGZ.ogg',
 'ADNPUEYS.ogg',
 'ADNYCZPD.ogg',
 'ADNYUCEB.ogg',
 'ADOEZJIO.ogg',
 'ADPKWOHB.ogg',
 'ADQHEJLV.ogg',
 'ADQKGTQJ.ogg',
 'ADQTWRSE.ogg',
 'ADQWFHBR.ogg',
 'ADRNQPXO.ogg',
 'ADSDIJTR.ogg',
 'ADSNZACB.ogg',
 'ADSRKXVU.ogg',
 'ADSRXWKO.ogg',
 'ADSSBDPL.ogg',
 'ADSTEZYN.ogg',
 'ADSTJJIB.ogg',
 'ADSXGIKP.ogg',
 'ADTAAQCP.ogg',
 'ADTBVZIW.ogg',
 'ADTDYZQZ.ogg',
 'ADTJOXOA.ogg',
 'ADTQJQCI.ogg',
 'ADTUELXB.ogg',
 'ADUABJXF.ogg',
 'ADUBKOVZ.ogg',
 'ADUIUEAW.ogg',
 'ADUQCTQP.ogg',
 'ADUQOFSI.ogg',
 'ADVMSMTV.ogg',
 'ADVQXYIM.ogg',
 'ADWOYWAP.ogg',
 'ADWXBJDH.ogg',
 'ADXBGMXE.ogg',
 'ADYANHIO.ogg',
 'ADYGUSBE.ogg',
 'ADYJKHHY.ogg',
 'ADYPROEM.ogg',
 'ADYQNAPY.ogg',
 'ADZOBSNB.ogg',
 'ADZQZRLW.ogg',
 'ADZUQMJO.ogg',
 'AEAAVDAF.ogg',
 'AEBMFJWF.ogg',
 'AEBNACWI.ogg',
 'AEBPSOHM.ogg',
 'AEBZNUBU.ogg',
 'AECPNGMA.ogg',
 'AECRBGUJ.ogg',
 'AECVJJQK.ogg',
 'AEDCYQQT.ogg',
 'AEDHXXYD.ogg',
 'AEDPCSZJ.ogg',
 'AEDZPTDI.ogg',
 'AEEACJIW.ogg',
 'AEEOHCVR.ogg',
 'AEEUECPE.ogg',
 'AEEURZUP.ogg',
 'AEFBUARF.ogg',
 'AEFMVYBW.ogg',
 'AEFWQMYP.ogg',
 'AEGEBHFT.ogg',
 'AEGWUBEU.ogg',
 'AEHCWTPB.ogg',
 'AEHDZWQM.ogg',
 'AEHVGZKG.ogg',
 'AEIAQJXV.ogg',
 'AEIKQDHC.ogg',
 'AEIRDQKD.ogg',
 'AEIZRMHG.ogg',
 'AEJFIPHV.ogg',
 'AEJJCUCT.ogg',
 'AEJMEDNT.ogg',
 'AEKDGZXN.ogg',
 'AEKOBTOE.ogg',
 'AEKSMDCO.ogg',
 'AELDKNXQ.ogg',
 'AELSBQQL.ogg',
 'AEMDYPFZ.ogg',
 'AEMHVPVW.ogg',
 'AEMKIWDO.ogg',
 'AEMMWATT.ogg',
 'AEMZZPPA.ogg',
 'AENBNFSI.ogg',
 'AENRBUAL.ogg',
 'AENTVFFM.ogg',
 'AENTYNMG.ogg',
 'AENWKPQE.ogg',
 'AEOFNIMF.ogg',
 'AEOHOHBW.ogg',
 'AEOXUSYR.ogg',
 'AEPGTXMC.ogg',
 'AEQHYULU.ogg',
 'AERPPYWP.ogg',
 'AERTUDRE.ogg',
 'AESCIYMY.ogg',
 'AESNSXZH.ogg',
 'AETIFRQU.ogg',
 'AETMLJQY.ogg',
 'AETMNHHW.ogg',
 'AETOGHFY.ogg',
 'AETWPQPP.ogg',
 'AEUDCUAC.ogg',
 'AEUWOAIB.ogg',
 'AEUYTICZ.ogg',
 'AEVCRCFP.ogg',
 'AEVJCMCP.ogg',
 'AEVKUTWY.ogg',
 'AEVNJDXP.ogg',
 'AEWICJRW.ogg',
 'AEWJZEME.ogg',
 'AEWTPDON.ogg',
 'AEWVHKYT.ogg',
 'AEXGOQDL.ogg',
 'AEXKWYDW.ogg',
 'AEXNBZLD.ogg',
 'AEXWQOKG.ogg',
 'AEXYVJTN.ogg',
 'AEYBZATW.ogg',
 'AEYLNOZG.ogg',
 'AEYOLXXC.ogg',
 'AEYSCGLW.ogg',
 'AEYXWGZQ.ogg',
 'AEZDKBEY.ogg',
 'AEZDYISN.ogg',
 'AEZYLUQL.ogg',
 'AFAAYJSI.ogg',
 'AFACNPAK.ogg',
 'AFADRIRJ.ogg',
 'AFAGCXCK.ogg',
 'AFALXUGS.ogg',
 'AFAMVIHQ.ogg',
 'AFANLUMA.ogg',
 'AFBLGBET.ogg',
 'AFBLTGOK.ogg',
 'AFBQLTEG.ogg',
 'AFBXWLNK.ogg',
 'AFBZWKVM.ogg',
 'AFCEQCVZ.ogg',
 'AFCYFLUW.ogg',
 'AFDJUTMO.ogg',
 'AFDPMDHK.ogg',
 'AFEHOGCJ.ogg',
 'AFEYUVPQ.ogg',
 'AFFLBOVF.ogg',
 'AFGCNCUU.ogg',
 'AFHOVMJV.ogg',
 'AFIFNCLP.ogg',
 'AFIKKLUO.ogg',
 'AFIROKXK.ogg',
 'AFIUYGOA.ogg',
 'AFJMVZLF.ogg',
 'AFJPEUHJ.ogg',
 'AFJWZYRF.ogg',
 'AFKXTQZF.ogg',
 'AFLFVIKD.ogg',
 'AFLHPTQF.ogg',
 'AFLZWGMH.ogg',
 'AFMGPDKW.ogg',
 'AFNLQZQL.ogg',
 'AFNXJSXO.ogg',
 'AFOPZPTL.ogg',
 'AFPGGOGL.ogg',
 'AFPVFIAV.ogg',
 'AFPWRHRB.ogg',
 'AFQEFLJL.ogg',
 'AFQGQEQK.ogg',
 'AFQHSXTQ.ogg',
 'AFQRCQUU.ogg',
 'AFQSNMRI.ogg',
 'AFRBXNQG.ogg',
 'AFRGMQYW.ogg',
 'AFRMTWGE.ogg',
 'AFROULCH.ogg',
 'AFRPSDEM.ogg',
 'AFRPUJGI.ogg',
 'AFRVVHPK.ogg',
 'AFSEQMNR.ogg',
 'AFSJNYYL.ogg',
 'AFSJRKTL.ogg',
 'AFSQIJVH.ogg',
 'AFSVCRLI.ogg',
 'AFSVSBSD.ogg',
 'AFTARWGF.ogg',
 'AFTBNETW.ogg',
 'AFTKYLGZ.ogg',
 'AFTZDSCV.ogg',
 'AFUEJCDS.ogg',
 'AFUKENUG.ogg',
 'AFUYLVDO.ogg',
 'AFVONUFK.ogg',
 'AFVTCTBV.ogg',
 'AFVWWUVV.ogg',
 'AFVXVZCM.ogg',
 'AFWDAERX.ogg',
 'AFWIEFWW.ogg',
 'AFWJNPMB.ogg',
 'AFWTBXQH.ogg',
 'AFWUUVYE.ogg',
 'AFXBKPRE.ogg',
 'AFXPGSFR.ogg',
 'AFYDFEQE.ogg',
 'AFYNCSIZ.ogg',
 'AFYOEBAF.ogg',
 'AFYZJFSO.ogg',
 'AFZGHEGW.ogg',
 'AFZJCVEA.ogg',
 'AFZNNBMJ.ogg',
 'AFZQULOH.ogg',
 'AFZWGKYO.ogg',
 'AGAALQTR.ogg',
 'AGAGSFMQ.ogg',
 'AGAPPMIX.ogg',
 'AGARSDKA.ogg',
 'AGASUWQT.ogg',
 'AGAUSEOT.ogg',
 'AGBAFONA.ogg',
 'AGBESGIE.ogg',
 'AGBGCXLZ.ogg',
 'AGBGYVPT.ogg',
 'AGBOALAT.ogg',
 'AGBUUVJE.ogg',
 'AGCHKVRQ.ogg',
 'AGCLFAQW.ogg',
 'AGCPUJHS.ogg',
 'AGCXORSP.ogg',
 'AGDAVVQQ.ogg',
 'AGDEVNQT.ogg',
 'AGDQIQFV.ogg',
 'AGDUPIND.ogg',
 'AGECTYKU.ogg',
 'AGEFYCBJ.ogg',
 'AGFDJUHD.ogg',
 'AGGDYNKC.ogg',
 'AGGGZLDV.ogg',
 'AGGMNOKU.ogg',
 'AGGXLHHC.ogg',
 'AGGXPHJD.ogg',
 'AGHATMQF.ogg',
 'AGIAJKYN.ogg',
 'AGIDDTIO.ogg',
 'AGILFEGO.ogg',
 'AGIQONAU.ogg',
 'AGIWVZKG.ogg',
 'AGJJZMVD.ogg',
 'AGJVQMDF.ogg',
 'AGJZCNCE.ogg',
 'AGKJBCAS.ogg',
 'AGKYVNAD.ogg',
 'AGLBDSJI.ogg',
 'AGLLRTPA.ogg',
 'AGLZYODF.ogg',
 'AGMWNVRF.ogg',
 'AGNBHAYY.ogg',
 'AGNQKNGC.ogg',
 'AGNZMIYK.ogg',
 'AGOHEFCJ.ogg',
 'AGOYCZEA.ogg',
 'AGPFLSOQ.ogg',
 'AGPQRXSM.ogg',
 'AGPTZJVF.ogg',
 'AGPYZILJ.ogg',
 'AGPZJCTE.ogg',
 'AGQCQXKL.ogg',
 'AGQCZWTI.ogg',
 'AGQFSDWT.ogg',
 'AGTLOBCF.ogg',
 'AGTPLHYB.ogg',
 'AGUGWFPO.ogg',
 'AGUNIFYQ.ogg',
 'AGUUHNCQ.ogg',
 'AGUZUPLU.ogg',
 'AGVAQSQO.ogg',
 'AGVEEARW.ogg',
 'AGVHCDDI.ogg',
 'AGVJCHVD.ogg',
 'AGVMGXSE.ogg',
 'AGVTOYVT.ogg',
 'AGWBLKOF.ogg',
 'AGWLICGR.ogg',
 'AGWMDZHB.ogg',
 'AGWXWLJP.ogg',
 'AGXMUWTF.ogg',
 'AGXXOJFP.ogg',
 'AGXYQIWN.ogg',
 'AGYCNBTW.ogg',
 'AGYLMIXE.ogg',
 'AGYZIVWR.ogg',
 'AGZPKXZS.ogg',
 'AHAAHLII.ogg',
 'AHAKRHKG.ogg',
 'AHBBPEMI.ogg',
 'AHCJYNJY.ogg',
 'AHDHDSEI.ogg',
 'AHDHXRRS.ogg',
 'AHDLDDUW.ogg',
 'AHDXYXNM.ogg',
 'AHDYOPHA.ogg',
 'AHEDSKDV.ogg',
 'AHEESOWJ.ogg',
 'AHENKMTJ.ogg',
 'AHFALZBA.ogg',
 'AHFCJALQ.ogg',
 'AHFNTEYW.ogg',
 'AHFVYCEQ.ogg',
 'AHGHLXSI.ogg',
 'AHGWLYDO.ogg',
 'AHHCNALZ.ogg',
 'AHHHPVXP.ogg',
 'AHHKSEZU.ogg',
 'AHHRIEZK.ogg',
 'AHHSAEJC.ogg',
 'AHIGTLCR.ogg',
 'AHIHQUVW.ogg',
 'AHIZVYUL.ogg',
 'AHJDQCGC.ogg',
 'AHJGLZQK.ogg',
 'AHJIBBAN.ogg',
 'AHJQEQQY.ogg',
 'AHJXGNEV.ogg',
 'AHKOYGQT.ogg',
 'AHLFJSQN.ogg',
 'AHLZMMEQ.ogg',
 'AHMAAWJD.ogg',
 'AHNKISAV.ogg',
 'AHNWFVNZ.ogg',
 'AHOJUHUF.ogg',
 'AHOLOSXE.ogg',
 'AHOVCIUA.ogg',
 'AHPMGUFF.ogg',
 'AHPUYDZQ.ogg',
 'AHPZBRGZ.ogg',
 'AHQCHOZM.ogg',
 'AHQHPOWN.ogg',
 'AHQJBAEO.ogg',
 'AHQNWZOY.ogg',
 'AHQPKPWQ.ogg',
 'AHRVGKVS.ogg',
 'AHRYQXUU.ogg',
 'AHSOCDYE.ogg',
 'AHSVTKRX.ogg',
 'AHTGUDEZ.ogg',
 'AHUEGHST.ogg',
 'AHUQLBHS.ogg',
 'AHUUSJOB.ogg',
 'AHVGNTRH.ogg',
 'AHVSZZGR.ogg',
 'AHVZLBGD.ogg',
 'AHWARRXT.ogg',
 'AHWDQGEF.ogg',
 'AHWMRDHV.ogg',
 'AHWQXQGQ.ogg',
 'AHWWLXXU.ogg',
 'AHXEIWPG.ogg',
 'AHXHREHW.ogg',
 'AHXLKIOJ.ogg',
 'AHXMGMPN.ogg',
 'AHXSBEFB.ogg',
 'AHYJVYRQ.ogg',
 'AHYTRPWQ.ogg',
 'AHYUUOKD.ogg',
 'AHZJXKGU.ogg',
 'AHZNAIDB.ogg',
 'AHZYJDTJ.ogg',
 'AIAGVZTM.ogg',
 'AIALEWIS.ogg',
 'AIAPAZIG.ogg',
 'AIAWJKGB.ogg',
 'AIBHCRTA.ogg',
 'AIBKDEPJ.ogg',
 'AIBNKKTD.ogg',
 'AIBTGPHR.ogg',
 'AIBXWDGX.ogg',
 'AICDZCBI.ogg',
 'AICNVWNS.ogg',
 'AICPVDQI.ogg',
 'AICQBQNH.ogg',
 'AICTFDLS.ogg',
 'AICWGBIU.ogg',
 'AIDHLGBC.ogg',
 'AIDJWOKA.ogg',
 'AIDTLCPO.ogg',
 'AIDWDJUD.ogg',
 'AIEHFHRX.ogg',
 'AIENUOJF.ogg',
 'AIEYUBGS.ogg',
 'AIEZGUQP.ogg',
 'AIFAIMIL.ogg',
 'AIFFTCRA.ogg',
 'AIFKCALK.ogg',
 'AIGEMOBQ.ogg',
 'AIGLPJKJ.ogg',
 'AIGNDNXA.ogg',
 'AIGZSPYB.ogg',
 'AIHQDZKQ.ogg',
 'AIHWUKPA.ogg',
 'AIIBGBFV.ogg',
 'AIIWGURU.ogg',
 'AIIZYHUL.ogg',
 'AIJWMRBH.ogg',
 'AIJYUZOW.ogg',
 'AIKCHPNB.ogg',
 'AIKMLOVD.ogg',
 'AIKPDOES.ogg',
 'AIMZABGQ.ogg',
 'AINLHFKV.ogg',
 'AINNBHJS.ogg',
 'AIODDNBO.ogg',
 'AIONYGQJ.ogg',
 'AIPGEZXI.ogg',
 'AIPGFSGT.ogg',
 'AIPSVYPD.ogg',
 'AIQJPTMG.ogg',
 'AIQQQVXS.ogg',
 'AIQWULRX.ogg',
 'AIRQOATZ.ogg',
 'AIRTCHLM.ogg',
 'AISAUROZ.ogg',
 'AISBKBEJ.ogg',
 'AISDUJXR.ogg',
 'AISGGETB.ogg',
 'AISPOPMG.ogg',
 'AISTCFGB.ogg',
 'AITDUZSK.ogg',
 'AITGONWI.ogg',
 'AITNPRBX.ogg',
 'AITUWDRP.ogg',
 'AIULKIVE.ogg',
 'AIUOCNCF.ogg',
 'AIURFHMM.ogg',
 'AIUUXFNP.ogg',
 'AIVDIIYO.ogg',
 'AIVEZTLG.ogg',
 'AIVFNGIE.ogg',
 'AIVWEUKX.ogg',
 'AIWADXHX.ogg',
 'AIWAGPQV.ogg',
 'AIWLSPNW.ogg',
 'AIWQMJLI.ogg',
 'AIWTLUAW.ogg',
 'AIXFJBKY.ogg',
 'AIXHYDNK.ogg',
 'AIXPMMFQ.ogg',
 'AIXTCNBY.ogg',
 'AIXZPKTV.ogg',
 'AIYFWIBQ.ogg',
 'AIYUHKXV.ogg',
 'AIYVYURF.ogg',
 'AIYYJOTF.ogg',
 'AIZAKRGX.ogg',
 'AIZPIRKF.ogg',
 'AIZPQTGC.ogg',
 'AIZUYWLJ.ogg',
 'AJBBOGBI.ogg',
 'AJBFABSU.ogg',
 'AJBSHFMM.ogg',
 'AJBTDTLP.ogg',
 'AJBTFEKQ.ogg',
 'AJBTONYS.ogg',
 'AJBWBSLF.ogg',
 'AJBYDNEE.ogg',
 'AJCQUYEA.ogg',
 'AJDCSEFP.ogg',
 'AJDEIHLH.ogg',
 'AJDFZAST.ogg',
 'AJDJNHAX.ogg',
 'AJEEHGWH.ogg',
 'AJEEZSQV.ogg',
 'AJEOUQOA.ogg',
 'AJFGGKEV.ogg',
 'AJFNUCOQ.ogg',
 'AJFQNPMQ.ogg',
 'AJGTYVOA.ogg',
 'AJGUQXNG.ogg',
 'AJGZARXD.ogg',
 'AJHPIGHL.ogg',
 'AJIAVABC.ogg',
 'AJIHLVIK.ogg',
 'AJIRAXRP.ogg',
 'AJIRPNDJ.ogg',
 'AJJSURAR.ogg',
 'AJKFOBAY.ogg',
 'AJKICDSA.ogg',
 'AJKIDODQ.ogg',
 'AJKLDVND.ogg',
 'AJKOJSYY.ogg',
 'AJKRNRZI.ogg',
 'AJKSMJPZ.ogg',
 'AJLEKGSH.ogg',
 'AJLKWLKO.ogg',
 'AJLPHOXD.ogg',
 'AJMMMHCS.ogg',
 'AJMNXSND.ogg',
 'AJMQPQNP.ogg',
 'AJMZRSAS.ogg',
 'AJNBKOJC.ogg',
 'AJNBTLJG.ogg',
 'AJNHIQTS.ogg',
 'AJNJPVEM.ogg',
 'AJOBHLGL.ogg',
 'AJOLSXZK.ogg',
 'AJOSGWOI.ogg',
 'AJOYFNMS.ogg',
 'AJPKCXPA.ogg',
 'AJPKWURJ.ogg',
 'AJPNKBWZ.ogg',
 'AJPSSKBD.ogg',
 'AJQJHTCG.ogg',
 'AJQNRTTZ.ogg',
 'AJQUQREE.ogg',
 'AJQZKSVP.ogg',
 'AJRBNWGC.ogg',
 'AJRJNVRN.ogg',
 'AJRKDDJB.ogg',
 'AJRPMMBT.ogg',
 'AJSFXQCO.ogg',
 'AJTDNKAA.ogg',
 'AJTIBKDD.ogg',
 'AJTPMNCF.ogg',
 'AJUBTAOJ.ogg',
 'AJUQLRZT.ogg',
 'AJUSUGDF.ogg',
 'AJUUNRCL.ogg',
 'AJVGIHPT.ogg',
 'AJVNKKQZ.ogg',
 'AJVUHIKA.ogg',
 'AJVZYPZM.ogg',
 'AJWSGVNU.ogg',
 'AJWWROIZ.ogg',
 'AJWXBYDV.ogg',
 'AJWZVGYQ.ogg',
 'AJXGGEWK.ogg',
 'AJXOLTIK.ogg',
 'AJXRDEWE.ogg',
 'AJXYHFTT.ogg',
 'AJYFLCUM.ogg',
 'AJYKQUND.ogg',
 'AJYTMDPR.ogg',
 'AJYVMMXL.ogg',
 'AJYWNBUN.ogg',
 'AJYXWCSX.ogg',
 'AJZIXPAQ.ogg',
 'AJZRGJRC.ogg',
 'AKAFJQIQ.ogg',
 'AKAOQATA.ogg',
 'AKARVISS.ogg',
 'AKATDYQY.ogg',
 'AKAWIOTJ.ogg',
 'AKAXQIFV.ogg',
 'AKBOCJDQ.ogg',
 'AKBOOKWP.ogg',
 'AKBYXDIJ.ogg',
 'AKBZWEAO.ogg',
 'AKCMMVXO.ogg',
 'AKCWBZCG.ogg',
 'AKCZXFJK.ogg',
 'AKDCNLFW.ogg',
 'AKDEGHKT.ogg',
 'AKDHVILH.ogg',
 'AKEEKPEY.ogg',
 'AKEGKQNM.ogg',
 'AKENQBZF.ogg',
 'AKENWNCS.ogg',
 'AKENYJXT.ogg',
 'AKETLKSR.ogg',
 'AKEWLEVH.ogg',
 'AKFLOOHC.ogg',
 'AKGEZENQ.ogg',
 'AKGGXHQN.ogg',
 'AKGYSFGZ.ogg',
 'AKICDHVP.ogg',
 'AKICOEWM.ogg',
 'AKIJCVDI.ogg',
 'AKINHLRE.ogg',
 'AKIVXKHY.ogg',
 'AKJFWEVN.ogg',
 'AKJIAQTQ.ogg',
 'AKJWOGIJ.ogg',
 'AKKTFFGR.ogg',
 'AKKXIUZP.ogg',
 'AKLFGKDY.ogg',
 'AKLHOOFX.ogg',
 'AKLJZFUP.ogg',
 'AKLKPSUW.ogg',
 'AKLOKBGI.ogg',
 'AKLRNIEB.ogg',
 'AKOAQNHD.ogg',
 'AKOHYRJS.ogg',
 'AKOKVMAZ.ogg',
 'AKONRVMN.ogg',
 'AKOSOOMH.ogg',
 'AKPEPGAV.ogg',
 'AKPQVOME.ogg',
 'AKPSIZYR.ogg',
 'AKPUUBZJ.ogg',
 'AKQNHIAB.ogg',
 'AKQOLGKG.ogg',
 'AKQPMDCG.ogg',
 'AKRCRNDX.ogg',
 'AKRCYUMZ.ogg',
 'AKRKSEGR.ogg',
 'AKRYZNFX.ogg',
 'AKSBEDFZ.ogg',
 'AKSJTTYE.ogg',
 'AKSMPCOJ.ogg',
 'AKSRUOJV.ogg',
 'AKSZZXKT.ogg',
 'AKTHFKUH.ogg',
 'AKTUNTOW.ogg',
 'AKULBGIU.ogg',
 'AKULFXLG.ogg',
 'AKUPPIKH.ogg',
 'AKVGARWY.ogg',
 'AKVGCQDA.ogg',
 'AKVKQPFD.ogg',
 'AKVLQJIL.ogg',
 'AKVLVALO.ogg',
 'AKVYLYBQ.ogg',
 'AKWRMHMD.ogg',
 'AKWSISHL.ogg',
 'AKXEYBRY.ogg',
 'AKXFXZZG.ogg',
 'AKXLJPRX.ogg',
 'AKXLTZMU.ogg',
 'AKZRNPZD.ogg',
 'AKZTJYKP.ogg',
 'AKZUVEER.ogg',
 'AKZYHHJB.ogg',
 'ALAQUICV.ogg',
 'ALAQYZKJ.ogg',
 'ALAXYGNO.ogg',
 'ALBEXIOR.ogg',
 'ALBFNSMA.ogg',
 'ALBKCPGL.ogg',
 'ALBTVPAU.ogg',
 'ALBYWZGG.ogg',
 'ALCFUPBC.ogg',
 'ALCJGLII.ogg',
 'ALCOPRTA.ogg',
 'ALCWCCFT.ogg',
 'ALDBWRIZ.ogg',
 'ALDUCZCW.ogg',
 'ALEKIKZU.ogg',
 'ALETTBZH.ogg',
 'ALEZOAYY.ogg',
 'ALFHAZRH.ogg',
 'ALFVKBTQ.ogg',
 'ALFWKHIF.ogg',
 'ALGRYBFL.ogg',
 'ALGVLKVB.ogg',
 'ALGWJQMZ.ogg',
 'ALHTABEH.ogg',
 'ALHUUXIA.ogg',
 'ALIJEHEB.ogg',
 'ALIJNFRF.ogg',
 'ALIYGGTF.ogg',
 'ALJDGTKE.ogg',
 'ALJRZMBU.ogg',
 'ALJSBCDQ.ogg',
 'ALJUXRNQ.ogg',
 'ALKAOVNU.ogg',
 'ALKIUKHA.ogg',
 'ALKMVJWQ.ogg',
 'ALKRDVFF.ogg',
 'ALLHXIXS.ogg',
 'ALLMSOUQ.ogg',
 'ALLQOPBP.ogg',
 'ALLXCXXT.ogg',
 'ALLXYWYP.ogg',
 'ALMAPCIY.ogg',
 'ALMRKNPR.ogg',
 'ALMVHLWP.ogg',
 'ALNATJVU.ogg',
 'ALNUKCDQ.ogg',
 'ALNUYTRG.ogg',
 'ALOCVASW.ogg',
 'ALODTWUB.ogg',
 'ALOIRSSL.ogg',
 'ALOLZWEP.ogg',
 'ALOXHEML.ogg',
 'ALPDTTFM.ogg',
 'ALPFZXWE.ogg',
 'ALPXPRSG.ogg',
 'ALQFACBZ.ogg',
 'ALQQCIDE.ogg',
 'ALQSTIKZ.ogg',
 'ALRDVQWR.ogg',
 'ALRLDEKG.ogg',
 'ALRTKBMG.ogg',
 'ALSPOUQC.ogg',
 'ALSUQFDZ.ogg',
 'ALUMTIAL.ogg',
 'ALUOSDMB.ogg',
 'ALUXSHFV.ogg',
 'ALVWEEJU.ogg',
 'ALWFDQID.ogg',
 'ALWTQMZG.ogg',
 'ALXEHQLG.ogg',
 'ALXJLRDR.ogg',
 'ALXLIYVG.ogg',
 ...]

In [32]:
test=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/test.csv")
test

               id                   path
0      TEST_00000  ./test/TEST_00000.ogg
1      TEST_00001  ./test/TEST_00001.ogg
2      TEST_00002  ./test/TEST_00002.ogg
3      TEST_00003  ./test/TEST_00003.ogg
4      TEST_00004  ./test/TEST_00004.ogg
...           ...                    ...
49995  TEST_49995  ./test/TEST_49995.ogg
49996  TEST_49996  ./test/TEST_49996.ogg
49997  TEST_49997  ./test/TEST_49997.ogg
49998  TEST_49998  ./test/TEST_49998.ogg
49999  TEST_49999  ./test/TEST_49999.ogg

[50000 rows x 2 columns]

In [33]:
import librosa
import librosa.display
import numpy as np  


x=librosa.load(train_path+train_list[0])[0]

In [34]:
S = librosa.feature.melspectrogram(y=x, sr=8000, n_mels=200)
log_S = librosa.power_to_db(S, ref=np.max)
mfcc = librosa.feature.mfcc(S=log_S, n_mfcc=30)
n_mfcc = librosa.feature.delta(mfcc, order=2)
n_mfcc = n_mfcc.flatten()
n_mfcc=n_mfcc[:500]

In [35]:
n_mfcc[499]

5.36542

In [36]:
n_mfcc.shape

(500,)

In [37]:
train_len=len(train_list)
test_len=len(test_list)

In [38]:
train_data=pd.DataFrame(index=range(train_len),columns=(['id','label']))
test_data=pd.DataFrame(index=range(test_len),columns=(['id']))

In [39]:
train_data['id']=train['id']
train_data['label']=train['label']

In [40]:
train_data

             id label
0      RUNQPNJF  real
1      JFAWUOGJ  fake
2      RDKEKEVX  real
3      QYHJDOFK  real
4      RSPQNHAO  real
...         ...   ...
55433  NJGPMAJL  real
55434  SZXIACUZ  fake
55435  PXLBTGRH  fake
55436  CGGQGPOQ  fake
55437  CPMKEDIS  fake

[55438 rows x 2 columns]

In [41]:
train_feature=pd.DataFrame(index=range(train_data.shape[0]),columns=range(n_mfcc.shape[0]))

In [42]:
train_feature

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
train_feature.shape

(55438, 500)

In [44]:
train_data.iloc[0,1]

'real'

In [45]:
test_data

        id
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
...    ...
49995  NaN
49996  NaN
49997  NaN
49998  NaN
49999  NaN

[50000 rows x 1 columns]

In [46]:
train_feature=pd.DataFrame(index=range(train_data.shape[0]),columns=range(n_mfcc.shape[0]))

In [47]:
train_feature.shape

(55438, 500)

In [48]:
x=librosa.load(train_path+train_list[2])[0]
S = librosa.feature.melspectrogram(y=x, sr=8000, n_mels=200)
log_S = librosa.power_to_db(S, ref=np.max)
mfcc = librosa.feature.mfcc(S=log_S, n_mfcc=30)
n_mfcc = librosa.feature.delta(mfcc, order=2)
n_mfcc=n_mfcc.flatten()
n_mfcc=n_mfcc[:800]
n_mfcc.shape

(800,)

In [49]:
import numpy as np
import pandas as pd
import librosa

# Constants
duration = 2  # seconds
sample_rate = 16000  # Hz

# train_feature 데이터프레임의 크기에 맞게 수정
train_feature = pd.DataFrame(np.zeros((train_feature.shape[0], 500)))  # 예시로 train_feature 초기화

for i in range(train_feature.shape[0]):
    # Load audio file
    x, _ = librosa.load(train_path + train_list[i], sr=sample_rate, duration=duration)
    
    # Extract features
    S = librosa.feature.melspectrogram(y=x, sr=sample_rate, n_mels=128)
    log_S = librosa.power_to_db(S, ref=np.max)
    
    mfcc = librosa.feature.mfcc(S=log_S, n_mfcc=20)
    
    # Adjust width for delta calculations
    delta_width = min(3, mfcc.shape[1])
    
    delta_mfcc = librosa.feature.delta(mfcc, order=1, width=delta_width)
    delta2_mfcc = librosa.feature.delta(mfcc, order=2, width=delta_width)
    
    zcr = librosa.feature.zero_crossing_rate(y=x)
    spectral_centroid = librosa.feature.spectral_centroid(y=x, sr=sample_rate)
    spectral_rolloff = librosa.feature.spectral_rolloff(y=x, sr=sample_rate)
    chroma_stft = librosa.feature.chroma_stft(y=x, sr=sample_rate)
    
    features = np.concatenate((mfcc, delta_mfcc, delta2_mfcc, zcr, spectral_centroid, spectral_rolloff, chroma_stft), axis=0)
    
    # Flatten and truncate or pad the feature vector to length 300
    features = features.flatten()
    if features.shape[0] > 500:
        features = features[:500]
    elif features.shape[0] < 500:
        features = np.pad(features, (0, 500 - features.shape[0]), mode='constant')

    # Assign the features to the dataframe
    for j in range(train_feature.shape[1]):
        train_feature.iloc[i, j] = features[j]

# train_feature 데이터프레임을 이후에 모델 학습 등에 사용

/opt/anaconda3/envs/conda_cpu/lib/python3.12/site-packages/librosa/core/pitch.py:101: UserWarning: Trying to estimate tuning from empty frequency set.
  return pitch_tuning(
/opt/anaconda3/envs/conda_cpu/lib/python3.12/site-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=1690
  warnings.warn(
/opt/anaconda3/envs/conda_cpu/lib/python3.12/site-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=1891
  warnings.warn(

In [50]:
train_feature

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,-394.936279,-342.587677,-357.504242,-389.995789,-371.906921,-337.934479,-373.743652,-372.747040,-400.585815,-500.081055,...,8.905629,15.766691,17.116306,15.880061,10.258942,2.398996,-3.005361,1.636842,5.008161,5.762723
1,-581.788025,-493.333282,-410.954376,-401.585815,-452.935852,-559.960815,-639.186523,-577.563904,-549.041748,-571.204224,...,7.876628,10.167208,1.400615,-2.246990,-3.722476,-5.581533,3.678391,8.194968,11.300259,13.055321
2,-517.554138,-425.886932,-376.557495,-396.908142,-454.959808,-460.856201,-462.123627,-454.131134,-449.885803,-389.053894,...,-2.851710,-3.132828,-6.061777,-7.082493,-8.895997,-10.058793,-13.975571,-14.635300,-9.903198,-4.784858
3,-394.363861,-368.538696,-439.574280,-514.239624,-506.364410,-452.762970,-411.703979,-411.203644,-458.048096,-529.425110,...,-31.119232,-20.430134,-9.433218,-4.932928,-1.086504,-5.789751,-6.906551,1.472052,5.698291,4.222816
4,-450.617249,-434.187286,-460.728149,-434.470032,-380.399719,-363.353516,-364.176392,-368.033844,-358.251556,-349.455658,...,56.702404,56.847462,50.103600,49.273525,60.887165,67.667618,63.266319,64.867722,60.496880,23.194427
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-579.553955,-504.509705,-438.041626,-435.807068,-432.775116,-430.017151,-447.504150,-494.811523,-482.655396,-455.870026,...,4.929172,4.173687,11.923154,2.771895,4.701987,8.197219,7.459965,11.218405,5.171367,8.490377
55434,-511.036774,-456.407471,-439.349365,-490.263489,-543.329224,-540.333984,-562.810791,-515.110779,-492.389801,-524.895813,...,0.151554,-12.267236,-20.150684,-8.549176,1.822296,9.483316,17.047247,18.916973,20.175413,16.466801
55435,-223.470337,-255.177841,-401.685364,-517.920410,-651.353577,-442.551727,-376.734009,-347.039093,-342.265808,-358.595612,...,18.513523,14.305043,8.399870,4.094192,0.706241,8.824681,8.718239,6.863665,3.917936,-1.613910
55436,-613.153320,-546.741638,-530.802673,-541.177429,-515.064331,-449.687378,-443.373383,-485.865997,-513.414490,-477.019653,...,1.514391,5.071825,4.880034,3.549245,7.796243,28.495705,36.051109,24.949368,15.910053,17.942818
55437,-459.972260,-439.924774,-469.205811,-513.793701,-542.390442,-547.578491,-576.286926,-557.963806,-541.575439,-528.135193,...,-24.779848,-22.585838,-21.764986,-13.240429,14.433520,27.377146,32.313156,24.504030,7.309380,5.781779

In [51]:
Y=pd.DataFrame(train['label'])

In [52]:
save_data=pd.concat([train_feature,Y],axis=1)

In [53]:
save_data

,0,1,2,3,4,5,6,7,8,9,...,491,492,493,494,495,496,497,498,499,label
0,-394.936279,-342.587677,-357.504242,-389.995789,-371.906921,-337.934479,-373.743652,-372.747040,-400.585815,-500.081055,...,15.766691,17.116306,15.880061,10.258942,2.398996,-3.005361,1.636842,5.008161,5.762723,real
1,-581.788025,-493.333282,-410.954376,-401.585815,-452.935852,-559.960815,-639.186523,-577.563904,-549.041748,-571.204224,...,10.167208,1.400615,-2.246990,-3.722476,-5.581533,3.678391,8.194968,11.300259,13.055321,fake
2,-517.554138,-425.886932,-376.557495,-396.908142,-454.959808,-460.856201,-462.123627,-454.131134,-449.885803,-389.053894,...,-3.132828,-6.061777,-7.082493,-8.895997,-10.058793,-13.975571,-14.635300,-9.903198,-4.784858,real
3,-394.363861,-368.538696,-439.574280,-514.239624,-506.364410,-452.762970,-411.703979,-411.203644,-458.048096,-529.425110,...,-20.430134,-9.433218,-4.932928,-1.086504,-5.789751,-6.906551,1.472052,5.698291,4.222816,real
4,-450.617249,-434.187286,-460.728149,-434.470032,-380.399719,-363.353516,-364.176392,-368.033844,-358.251556,-349.455658,...,56.847462,50.103600,49.273525,60.887165,67.667618,63.266319,64.867722,60.496880,23.194427,real
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-579.553955,-504.509705,-438.041626,-435.807068,-432.775116,-430.017151,-447.504150,-494.811523,-482.655396,-455.870026,...,4.173687,11.923154,2.771895,4.701987,8.197219,7.459965,11.218405,5.171367,8.490377,real
55434,-511.036774,-456.407471,-439.349365,-490.263489,-543.329224,-540.333984,-562.810791,-515.110779,-492.389801,-524.895813,...,-12.267236,-20.150684,-8.549176,1.822296,9.483316,17.047247,18.916973,20.175413,16.466801,fake
55435,-223.470337,-255.177841,-401.685364,-517.920410,-651.353577,-442.551727,-376.734009,-347.039093,-342.265808,-358.595612,...,14.305043,8.399870,4.094192,0.706241,8.824681,8.718239,6.863665,3.917936,-1.613910,fake
55436,-613.153320,-546.741638,-530.802673,-541.177429,-515.064331,-449.687378,-443.373383,-485.865997,-513.414490,-477.019653,...,5.071825,4.880034,3.549245,7.796243,28.495705,36.051109,24.949368,15.910053,17.942818,fake
55437,-459.972260,-439.924774,-469.205811,-513.793701,-542.390442,-547.578491,-576.286926,-557.963806,-541.575439,-528.135193,...,-22.585838,-21.764986,-13.240429,14.433520,27.377146,32.313156,24.504030,7.309380,5.781779,fake

In [54]:
save_data2=save_data

In [55]:
save_data2=save_data.dropna(axis=0)

In [56]:
save_data2

,0,1,2,3,4,5,6,7,8,9,...,491,492,493,494,495,496,497,498,499,label
0,-394.936279,-342.587677,-357.504242,-389.995789,-371.906921,-337.934479,-373.743652,-372.747040,-400.585815,-500.081055,...,15.766691,17.116306,15.880061,10.258942,2.398996,-3.005361,1.636842,5.008161,5.762723,real
1,-581.788025,-493.333282,-410.954376,-401.585815,-452.935852,-559.960815,-639.186523,-577.563904,-549.041748,-571.204224,...,10.167208,1.400615,-2.246990,-3.722476,-5.581533,3.678391,8.194968,11.300259,13.055321,fake
2,-517.554138,-425.886932,-376.557495,-396.908142,-454.959808,-460.856201,-462.123627,-454.131134,-449.885803,-389.053894,...,-3.132828,-6.061777,-7.082493,-8.895997,-10.058793,-13.975571,-14.635300,-9.903198,-4.784858,real
3,-394.363861,-368.538696,-439.574280,-514.239624,-506.364410,-452.762970,-411.703979,-411.203644,-458.048096,-529.425110,...,-20.430134,-9.433218,-4.932928,-1.086504,-5.789751,-6.906551,1.472052,5.698291,4.222816,real
4,-450.617249,-434.187286,-460.728149,-434.470032,-380.399719,-363.353516,-364.176392,-368.033844,-358.251556,-349.455658,...,56.847462,50.103600,49.273525,60.887165,67.667618,63.266319,64.867722,60.496880,23.194427,real
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-579.553955,-504.509705,-438.041626,-435.807068,-432.775116,-430.017151,-447.504150,-494.811523,-482.655396,-455.870026,...,4.173687,11.923154,2.771895,4.701987,8.197219,7.459965,11.218405,5.171367,8.490377,real
55434,-511.036774,-456.407471,-439.349365,-490.263489,-543.329224,-540.333984,-562.810791,-515.110779,-492.389801,-524.895813,...,-12.267236,-20.150684,-8.549176,1.822296,9.483316,17.047247,18.916973,20.175413,16.466801,fake
55435,-223.470337,-255.177841,-401.685364,-517.920410,-651.353577,-442.551727,-376.734009,-347.039093,-342.265808,-358.595612,...,14.305043,8.399870,4.094192,0.706241,8.824681,8.718239,6.863665,3.917936,-1.613910,fake
55436,-613.153320,-546.741638,-530.802673,-541.177429,-515.064331,-449.687378,-443.373383,-485.865997,-513.414490,-477.019653,...,5.071825,4.880034,3.549245,7.796243,28.495705,36.051109,24.949368,15.910053,17.942818,fake
55437,-459.972260,-439.924774,-469.205811,-513.793701,-542.390442,-547.578491,-576.286926,-557.963806,-541.575439,-528.135193,...,-22.585838,-21.764986,-13.240429,14.433520,27.377146,32.313156,24.504030,7.309380,5.781779,fake

In [57]:
save_data2.to_csv("train data0703(500).csv")

In [58]:
save_data2.isnull().sum()

0        0
1        0
2        0
3        0
4        0
        ..
496      0
497      0
498      0
499      0
label    0
Length: 501, dtype: int64