In [1]:
import pandas as pd   

train=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/main/train/0712/train data columns.csv",index_col=0)

train

,0,1,2,3,4,5,6,7,8,9,...,1007,1008,1009,1010,1011,1012,1013,1014,1015,label
0,-10.680473,-10.065905,-8.485398,-8.471478,-8.938723,-9.573242,-9.778496,-9.528599,-9.170987,-8.849465,...,-0.322508,-0.087017,0.304063,0.404823,0.479159,0.535449,0.511438,0.202025,0.074921,fake
1,-11.071263,-11.079940,-10.551203,-10.089887,-9.634271,-9.297155,-9.277541,-9.482996,-9.715906,-10.094424,...,-0.286983,0.044365,0.068283,0.268024,0.378609,0.477951,0.543279,0.465428,0.377558,fake
2,-11.061636,-10.900703,-9.897691,-9.627090,-9.460627,-9.390776,-9.529352,-9.783495,-10.150701,-10.327344,...,0.084898,0.158464,-0.037385,-0.031830,-0.065905,-0.144708,-0.238556,-0.262587,-0.109534,real
3,-10.501434,-9.739539,-8.956120,-9.592299,-10.143098,-10.398886,-10.340263,-10.351754,-10.469296,-10.385562,...,-0.535377,0.416520,0.387058,0.726899,0.558501,0.497426,0.449314,0.332968,0.456198,real
4,-11.117754,-11.013177,-10.541680,-10.596990,-10.668945,-10.714156,-10.677109,-10.532436,-10.372413,-10.261147,...,-0.007236,0.113250,0.147934,0.123936,0.134960,0.118806,0.215570,0.201303,0.227695,real
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-11.144724,-11.137963,-10.819232,-10.458742,-10.402115,-10.462618,-10.440723,-10.395901,-10.475930,-10.594594,...,-0.305863,0.020189,0.080815,0.032809,-0.131100,-0.412744,-0.478068,-0.421102,-0.405390,fake
55434,-10.425381,-9.859460,-9.212831,-9.264336,-9.338524,-9.558168,-9.837779,-10.059920,-10.196332,-10.262708,...,-0.343358,-0.430669,-0.537894,-0.542315,-0.594209,-0.467926,-0.462328,-0.471181,-0.395152,fake
55435,-8.136928,-8.514102,-8.929909,-9.356843,-9.693064,-10.213511,-10.750908,-10.973743,-11.060165,-11.075549,...,0.033486,0.628226,0.426825,0.151324,0.045645,0.201020,0.437524,0.442280,0.383002,real
55436,-10.992670,-10.891329,-10.557309,-10.454976,-10.429793,-10.488954,-10.582969,-10.744830,-10.849541,-10.596731,...,-0.632286,0.220390,0.238211,0.220074,0.083456,0.072693,0.168384,0.335541,0.345256,fake
55437,-10.772964,-10.521650,-9.840327,-10.057259,-10.229515,-10.349794,-10.477160,-10.586072,-10.613735,-10.599486,...,0.301742,0.461116,0.283341,0.426181,0.479992,0.518039,0.563831,0.723271,0.802327,fake

In [2]:
train.isnull().sum()

0        0
1        0
2        0
3        0
4        0
        ..
1012     0
1013     0
1014     0
1015     0
label    0
Length: 1017, dtype: int64

In [3]:
train_y=pd.DataFrame(train['label'])

In [4]:
train_y

      label
0      fake
1      fake
2      real
3      real
4      real
...     ...
55433  fake
55434  fake
55435  real
55436  fake
55437  fake

[55438 rows x 1 columns]

In [5]:
train_y.iloc[2,0]

'real'

In [6]:
Y=pd.DataFrame(index=range(train_y.shape[0]),columns=['label'])
Y.columns

Index(['label'], dtype='object')

In [7]:
for i in range(train.shape[0]):     
    if train_y.iloc[i,0]=='real':
        Y.iloc[i,0]=1.0
    elif train_y.iloc[i,0]=='fake':
        Y.iloc[i,0]=0.0

In [8]:
Y

      label
0       0.0
1       0.0
2       1.0
3       1.0
4       1.0
...     ...
55433   0.0
55434   0.0
55435   1.0
55436   0.0
55437   0.0

[55438 rows x 1 columns]

In [9]:
train_y.isnull().sum()

label    0
dtype: int64

In [10]:
train_x=train.drop(columns=['label'])

In [11]:
train_x

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
0,-10.680473,-10.065905,-8.485398,-8.471478,-8.938723,-9.573242,-9.778496,-9.528599,-9.170987,-8.849465,...,-0.453353,-0.322508,-0.087017,0.304063,0.404823,0.479159,0.535449,0.511438,0.202025,0.074921
1,-11.071263,-11.079940,-10.551203,-10.089887,-9.634271,-9.297155,-9.277541,-9.482996,-9.715906,-10.094424,...,-0.193274,-0.286983,0.044365,0.068283,0.268024,0.378609,0.477951,0.543279,0.465428,0.377558
2,-11.061636,-10.900703,-9.897691,-9.627090,-9.460627,-9.390776,-9.529352,-9.783495,-10.150701,-10.327344,...,0.133401,0.084898,0.158464,-0.037385,-0.031830,-0.065905,-0.144708,-0.238556,-0.262587,-0.109534
3,-10.501434,-9.739539,-8.956120,-9.592299,-10.143098,-10.398886,-10.340263,-10.351754,-10.469296,-10.385562,...,-0.547253,-0.535377,0.416520,0.387058,0.726899,0.558501,0.497426,0.449314,0.332968,0.456198
4,-11.117754,-11.013177,-10.541680,-10.596990,-10.668945,-10.714156,-10.677109,-10.532436,-10.372413,-10.261147,...,0.029022,-0.007236,0.113250,0.147934,0.123936,0.134960,0.118806,0.215570,0.201303,0.227695
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-11.144724,-11.137963,-10.819232,-10.458742,-10.402115,-10.462618,-10.440723,-10.395901,-10.475930,-10.594594,...,-0.546889,-0.305863,0.020189,0.080815,0.032809,-0.131100,-0.412744,-0.478068,-0.421102,-0.405390
55434,-10.425381,-9.859460,-9.212831,-9.264336,-9.338524,-9.558168,-9.837779,-10.059920,-10.196332,-10.262708,...,-0.281078,-0.343358,-0.430669,-0.537894,-0.542315,-0.594209,-0.467926,-0.462328,-0.471181,-0.395152
55435,-8.136928,-8.514102,-8.929909,-9.356843,-9.693064,-10.213511,-10.750908,-10.973743,-11.060165,-11.075549,...,0.005537,0.033486,0.628226,0.426825,0.151324,0.045645,0.201020,0.437524,0.442280,0.383002
55436,-10.992670,-10.891329,-10.557309,-10.454976,-10.429793,-10.488954,-10.582969,-10.744830,-10.849541,-10.596731,...,-0.634200,-0.632286,0.220390,0.238211,0.220074,0.083456,0.072693,0.168384,0.335541,0.345256
55437,-10.772964,-10.521650,-9.840327,-10.057259,-10.229515,-10.349794,-10.477160,-10.586072,-10.613735,-10.599486,...,0.297821,0.301742,0.461116,0.283341,0.426181,0.479992,0.518039,0.563831,0.723271,0.802327

In [12]:
from sklearn.feature_selection import VarianceThreshold

# 분산이 낮은 특성 제거
#selector = VarianceThreshold(threshold=0.1)
#train_x = pd.DataFrame(selector.fit_transform(train_x))
#train_x

In [13]:
from sklearn.decomposition import PCA

# 주성분 분석을 통한 차원 축소
#pca = PCA(n_components=500)  
#train_x = pd.DataFrame(pca.fit_transform(train_x))

In [14]:
from sklearn.preprocessing import RobustScaler,StandardScaler

scaler=RobustScaler()

train_x=pd.DataFrame(scaler.fit_transform(train_x))
train_x

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
0,0.875701,1.351565,2.097948,2.224098,1.633642,0.765481,0.562562,1.102859,1.815453,2.453548,...,-0.592123,-0.447051,-0.065107,0.687512,0.692487,0.817905,0.915205,0.874687,0.354573,0.141450
1,-0.528780,-0.845305,-0.728674,-0.136786,0.570881,1.199932,1.364931,1.178070,0.904111,0.345703,...,-0.119430,-0.377040,0.196933,0.254328,0.464703,0.650230,0.818934,0.927927,0.799149,0.657639
2,-0.494179,-0.456994,0.165520,0.538328,0.836200,1.052611,0.961611,0.682475,0.176946,-0.048654,...,0.474298,0.355853,0.424504,0.060190,-0.034584,-0.091027,-0.223622,-0.379317,-0.429607,-0.173164
3,1.519161,2.058624,1.453863,0.589079,-0.206581,-0.533753,-0.337211,-0.254717,-0.355884,-0.147225,...,-0.762785,-0.866568,0.939196,0.839995,1.228777,0.950214,0.851541,0.770815,0.575581,0.791770
4,-0.695865,-0.700666,-0.715644,-0.876531,-1.010049,-1.029864,-0.876730,-0.552705,-0.193853,0.063424,...,0.284591,0.174277,0.334325,0.400666,0.224783,0.243929,0.217596,0.379991,0.353354,0.402026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-0.792793,-0.971010,-1.095417,-0.674859,-0.602345,-0.634043,-0.498115,-0.327526,-0.366979,-0.501137,...,-0.762123,-0.414248,0.148716,0.277352,0.073046,-0.199745,-0.672411,-0.779785,-0.697150,-0.677786
55434,1.792492,1.798821,1.102608,1.067502,1.022767,0.789202,0.467609,0.226586,0.100630,0.060781,...,-0.279013,-0.488143,-0.750519,-0.859367,-0.884592,-0.972014,-0.764805,-0.753467,-0.781675,-0.660323
55435,10.017083,4.713488,1.489727,0.932556,0.481049,-0.242047,-0.994932,-1.280524,-1.344074,-1.315444,...,0.241906,0.254532,1.361443,0.913055,0.270387,0.094990,0.355251,0.751103,0.760080,0.666923
55436,-0.246320,-0.436686,-0.737029,-0.669366,-0.644636,-0.675484,-0.725948,-0.902992,-0.991819,-0.504755,...,-0.920810,-1.057554,0.548016,0.566526,0.384862,0.158042,0.140385,0.301095,0.579924,0.602542
55437,0.543293,0.364210,0.244011,-0.089189,-0.338622,-0.456503,-0.556475,-0.641163,-0.597448,-0.509420,...,0.773130,0.783202,1.028142,0.649440,0.728052,0.819294,0.886056,0.962291,1.234342,1.382140

In [15]:
train_x

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
0,0.875701,1.351565,2.097948,2.224098,1.633642,0.765481,0.562562,1.102859,1.815453,2.453548,...,-0.592123,-0.447051,-0.065107,0.687512,0.692487,0.817905,0.915205,0.874687,0.354573,0.141450
1,-0.528780,-0.845305,-0.728674,-0.136786,0.570881,1.199932,1.364931,1.178070,0.904111,0.345703,...,-0.119430,-0.377040,0.196933,0.254328,0.464703,0.650230,0.818934,0.927927,0.799149,0.657639
2,-0.494179,-0.456994,0.165520,0.538328,0.836200,1.052611,0.961611,0.682475,0.176946,-0.048654,...,0.474298,0.355853,0.424504,0.060190,-0.034584,-0.091027,-0.223622,-0.379317,-0.429607,-0.173164
3,1.519161,2.058624,1.453863,0.589079,-0.206581,-0.533753,-0.337211,-0.254717,-0.355884,-0.147225,...,-0.762785,-0.866568,0.939196,0.839995,1.228777,0.950214,0.851541,0.770815,0.575581,0.791770
4,-0.695865,-0.700666,-0.715644,-0.876531,-1.010049,-1.029864,-0.876730,-0.552705,-0.193853,0.063424,...,0.284591,0.174277,0.334325,0.400666,0.224783,0.243929,0.217596,0.379991,0.353354,0.402026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-0.792793,-0.971010,-1.095417,-0.674859,-0.602345,-0.634043,-0.498115,-0.327526,-0.366979,-0.501137,...,-0.762123,-0.414248,0.148716,0.277352,0.073046,-0.199745,-0.672411,-0.779785,-0.697150,-0.677786
55434,1.792492,1.798821,1.102608,1.067502,1.022767,0.789202,0.467609,0.226586,0.100630,0.060781,...,-0.279013,-0.488143,-0.750519,-0.859367,-0.884592,-0.972014,-0.764805,-0.753467,-0.781675,-0.660323
55435,10.017083,4.713488,1.489727,0.932556,0.481049,-0.242047,-0.994932,-1.280524,-1.344074,-1.315444,...,0.241906,0.254532,1.361443,0.913055,0.270387,0.094990,0.355251,0.751103,0.760080,0.666923
55436,-0.246320,-0.436686,-0.737029,-0.669366,-0.644636,-0.675484,-0.725948,-0.902992,-0.991819,-0.504755,...,-0.920810,-1.057554,0.548016,0.566526,0.384862,0.158042,0.140385,0.301095,0.579924,0.602542
55437,0.543293,0.364210,0.244011,-0.089189,-0.338622,-0.456503,-0.556475,-0.641163,-0.597448,-0.509420,...,0.773130,0.783202,1.028142,0.649440,0.728052,0.819294,0.886056,0.962291,1.234342,1.382140

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(train_x, Y, test_size=0.3, shuffle=True)

In [17]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
11642,-0.488632,-0.501368,-0.634814,-0.634633,-0.615056,-0.633957,-0.616725,-0.581232,-0.435646,-0.377882,...,-1.085258,-1.304786,-1.604263,-1.391484,-0.926018,-0.458806,-0.070240,0.344641,0.567601,0.703517
27262,-0.786518,-0.814712,-0.785104,-0.897060,-0.966698,-0.841938,-0.571855,-0.323368,-0.168653,-0.026240,...,1.331610,0.918586,-0.160195,-0.275897,-0.653898,-0.720679,-0.679762,-0.621762,-0.507015,-0.280587
143,0.249168,0.547784,0.843871,0.920452,0.823386,0.571052,0.295833,-0.151135,-0.152762,0.239201,...,-0.545466,-0.506446,-0.590811,-0.447544,-0.535637,-0.662038,-0.655003,-0.336998,0.051474,0.339811
28445,0.393641,0.369799,0.193272,0.228920,0.319639,0.330398,0.345238,0.204510,0.036569,-0.234475,...,0.779171,0.844042,0.706140,0.607042,0.336011,0.170717,0.141291,0.289867,0.125067,0.075132
35984,0.414871,0.742361,1.126446,1.309683,1.811553,2.056909,2.018799,2.189282,1.941006,1.356600,...,-0.344996,-0.336454,-0.401254,-1.049956,-1.934121,-2.223403,-2.425657,-2.332995,-2.103987,-1.931549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8349,1.496469,1.177654,0.247196,-0.273640,-0.785648,-0.916656,-0.768198,-0.469683,-0.026314,0.361463,...,0.286567,-0.330736,-0.497433,-0.346014,-0.388512,0.189835,0.613995,0.769696,0.781820,0.866486
33625,-0.638895,-0.866891,-1.127742,-0.890624,-0.494459,0.029723,0.443633,0.518693,0.275938,-0.156960,...,0.011814,-0.154876,0.460236,0.306403,0.102427,-0.313710,-0.262097,-0.432617,-0.791344,-0.903852
23452,1.019101,0.962391,0.668526,0.668709,0.626916,0.375156,-0.112560,-0.533690,-0.437793,-0.154300,...,-0.156333,0.070654,-0.032114,-0.348857,-0.614242,-0.756648,-1.046024,-1.363285,-1.464759,-1.252179
5668,-0.292724,-0.289268,-0.201653,-0.223313,-0.318819,-0.468675,-0.592196,-0.711186,-0.860234,-0.761499,...,-0.563263,-0.359302,0.174863,0.205950,0.475218,0.775493,0.741671,0.459521,0.398572,0.373236
36713,-0.316391,-0.136439,-0.190712,-0.136363,-0.038990,0.042724,0.247327,0.494908,0.597124,0.526257,...,0.237638,0.169494,-0.450908,-0.701538,-1.162671,-0.992214,-0.855521,-0.725012,-0.604353,-0.493500

In [18]:
y_train=Y
y_train

      label
0       0.0
1       0.0
2       1.0
3       1.0
4       1.0
...     ...
55433   0.0
55434   0.0
55435   1.0
55436   0.0
55437   0.0

[55438 rows x 1 columns]

In [19]:
X_test

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
39367,-0.425163,-0.027468,0.498362,0.480558,0.161878,-0.261387,-0.389836,-0.274869,0.322387,0.951340,...,0.427609,0.178173,0.490534,-0.457257,-0.848732,-0.782437,-0.812735,-0.477401,-0.265239,-0.222022
23324,0.108822,-0.111527,-0.553763,-0.946481,-1.066313,-1.027290,-0.926604,-0.779170,-0.522610,0.085061,...,-0.210952,-0.227375,-1.721022,-1.765023,-1.169273,-1.279781,-1.238573,-1.078105,-1.043309,-0.837032
37002,0.509732,0.248362,0.061377,-0.252384,-0.517458,-0.682002,-0.684313,-0.384185,0.391505,1.093221,...,-0.707993,-0.356826,-1.327827,-1.554409,-1.155705,-1.221770,-1.340140,-1.241240,-0.939971,-0.804919
53849,-0.307585,-0.428165,0.135681,0.394587,0.559763,0.559175,0.501579,0.278550,0.070708,0.016402,...,-0.398427,-0.299141,-0.279599,-0.539838,-0.813654,-1.020778,-1.234009,-1.100097,-0.961966,-0.928258
26662,1.044084,0.974430,0.457150,0.669382,0.915160,1.031678,0.992873,0.809328,0.567129,0.417036,...,0.828055,0.869745,0.808533,0.746111,0.554157,0.099310,0.019600,0.169878,0.183784,0.156866
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16404,1.520418,1.127965,0.505332,0.034681,-0.437584,-0.328482,0.249539,0.838465,1.194573,1.297297,...,0.588645,0.593869,0.451683,0.393334,0.014617,0.043907,0.196786,0.192389,0.342549,0.437306
11458,-0.734286,-0.868743,-0.774355,-0.118549,0.128965,0.177575,0.490224,1.045090,1.229990,1.210625,...,-0.525226,-0.460391,0.503545,0.261791,0.482103,0.669117,0.465867,0.585498,0.321734,0.206500
17499,0.166103,0.133877,1.179948,1.167630,1.286800,1.377196,1.367605,1.233502,1.012561,0.811451,...,0.614065,0.423198,0.557261,0.545615,-0.250387,-0.038822,0.055154,0.322709,0.407216,0.366657
2072,-0.108386,0.203222,0.230677,0.097057,-0.000928,-0.069471,0.021420,-0.094625,-0.322953,-0.337856,...,0.216077,-0.245876,-0.396320,-0.390671,-0.588787,-0.888637,-0.762211,-0.478309,-0.301020,-0.726606
27137,-0.824683,-0.834556,-1.045789,-1.069588,-0.990602,-0.728145,-0.219098,0.450861,0.981369,1.145602,...,0.980457,0.776847,0.663543,0.604503,0.439028,0.214626,0.228585,0.521119,0.912333,1.091251

In [20]:
import tensorflow as tf
import numpy as np 

X_train = X_train.astype(np.float32)
X_test = X_test.astype(np.float32)
y_train = np.array(y_train).astype(np.float32)


X_train_tensor = tf.convert_to_tensor(X_train)
X_test_tensor = tf.convert_to_tensor(X_test)

In [21]:
import tensorflow as tf

x_train = tf.reshape(X_train,(X_train.shape[0],X_train.shape[1],1))
x_test = tf.reshape(X_test,(X_test.shape[0],X_test.shape[1],1))

In [22]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, LSTM, Bidirectional, Conv1D, MaxPooling1D, Flatten, concatenate
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, LearningRateScheduler
from tensorflow.keras.optimizers import Adamax
from tensorflow.keras.activations import elu
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Layer, MultiHeadAttention, LayerNormalization
from tensorflow.keras.layers import Dropout
from tensorflow.keras.regularizers import l2



def scheduler(epoch, lr):
    if epoch < 10:
        return np.float32(lr)
    else:
        return np.float32(lr * tf.math.exp(-0.1))



class TransformerBlock(Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super(TransformerBlock, self).__init__()
        self.att = MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)
        self.ffn = tf.keras.Sequential(
            [Dense(ff_dim, activation="relu"), Dense(embed_dim),]
        )
        self.layernorm1 = LayerNormalization(epsilon=1e-6)
        self.layernorm2 = LayerNormalization(epsilon=1e-6)

    def call(self, inputs, training):
        attn_output = self.att(inputs, inputs)
        out1 = self.layernorm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        return self.layernorm2(out1 + ffn_output)


input_layer = Input(shape=(x_train.shape[1], x_train.shape[2]))


cnn = Conv1D(filters=32, kernel_size=5, activation='elu', kernel_regularizer=l2(0.01))(input_layer)
cnn = Dropout(0.3)(cnn)
cnn = Conv1D(filters=16, kernel_size=5, activation='elu', kernel_regularizer=l2(0.01))(cnn)
cnn = Dropout(0.3)(cnn)
cnn = Conv1D(filters=8, kernel_size=5, activation='elu', kernel_regularizer=l2(0.01))(cnn)
cnn = MaxPooling1D(pool_size=2)(cnn)
cnn = Flatten()(cnn)


lstm = Bidirectional(LSTM(16, return_sequences=True, kernel_regularizer=l2(0.01)))(input_layer)
lstm = Dropout(0.3)(lstm)
lstm = Bidirectional(LSTM(8, return_sequences=True, kernel_regularizer=l2(0.01)))(lstm)
lstm = Dropout(0.3)(lstm)
lstm = Bidirectional(LSTM(4, return_sequences=False, kernel_regularizer=l2(0.01)))(lstm)


transformer = TransformerBlock(embed_dim=x_train.shape[2], num_heads=4, ff_dim=32)(input_layer, training=True)
transformer = Flatten()(transformer)


combined = concatenate([cnn, lstm, transformer])


dense = Dense(16, activation='elu', kernel_regularizer=l2(0.01))(combined)
dense = Dropout(0.3)(dense)
dense = Dense(8, activation='elu', kernel_regularizer=l2(0.01))(dense)
dense = Dropout(0.3)(dense)
output = Dense(1, activation='sigmoid')(dense)


model = Model(inputs=input_layer, outputs=output)


model.compile(optimizer=Adamax(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])


early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
model_checkpoint = ModelCheckpoint('best_model.keras', save_best_only=True)
lr_scheduler = LearningRateScheduler(scheduler)

model.summary()

Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 1016, 1)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ transformer_encoder_layer       │ (None, 1016, 128)      │        70,531 │
│ (TransformerEncoderLayer)       │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ transformer_encoder_layer_1     │ (None, 1016, 128)      │       396,032 │
│ (TransformerEncoderLayer)       │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ transformer_encoder_layer_2     │ (None, 1016, 128)      │       396,032 │
│ (TransformerEncoderLayer)       │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ transformer_encoder_layer_3     │ (None, 1016, 128)      │       396,032 │
│ (TransformerEncoderLayer)       │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d        │ (None, 128)            │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 32)             │         4,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_12 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_13 (Dropout)            │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,263,300 (4.82 MB)

 Trainable params: 1,263,300 (4.82 MB)

 Non-trainable params: 0 (0.00 B)

In [23]:
training_record = model.fit(x_train, y_train,
                    epochs=50,
                    batch_size=256,
                    callbacks=[model_checkpoint, lr_scheduler],  
                    validation_split=0.2,
                    shuffle=False,
                    verbose=1)

Epoch 1/50
  1/122 ━━━━━━━━━━━━━━━━━━━━ 2:10:33 65s/step - accuracy: 0.5039 - loss: 0.6931

In [ ]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, roc_curve, auc, precision_recall_curve
import matplotlib.pyplot as plt


y_pred_prob = model.predict(x_test)
y_pred = (y_pred_prob > 0.5).astype(int)

ValueError: Input 0 of layer "functional_5" is incompatible with the layer: expected shape=(None, 10, 128), found shape=(32, 500)

In [ ]:
fpr, tpr, _ = roc_curve(y_test, y_pred_prob)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc="lower right")
plt.show()

ValueError: y_true takes value in {'fake', 'real'} and pos_label is not specified: either make y_true take value in {0, 1} or {-1, 1} or pass pos_label explicitly.

In [ ]:
precision, recall, _ = precision_recall_curve(y_test, y_pred_prob)
plt.figure()
plt.plot(recall, precision, color='b', lw=2)
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.show()

In [ ]:
# Classification Report
print("Classification Report:\n", classification_report(y_test, y_pred))

In [ ]:
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

In [ ]:
# Accuracy Score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy Score: {:.2f}%".format(accuracy * 100))